### ISSUE TITLE
Send back an  SIP Error code when the DID in the Request URI doesn't exist

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#10]

**Comment by mackhendricks** [comment]
I'm still debating if we should do this or not...so pushing this to 0.41 .

**Comment by mackhendricks** [comment]
We will send an error message back to the carrier, but it's meant for troubleshooting.

**Comment by mackhendricks** [comment]
Let's review the Kamailio to make sure it's letting you know that the DID was requested, but didn't exist - for troubleshooting purposes.

**Comment by mackhendricks** [comment]
This potentially give an attacker some insight on the domains being managed by dSIPRouter.  So, we will mark this "wont fix"

**Comment by devopsec** [comment]
closing this issue as making this change would be a security risk
