### ISSUE TITLE
Failover for DID's 

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#100]
We will add failover support for DID's and the ability to route to Domains, which contains 1 or more PBX's

**Comment by devopsec** [comment]
Already supported by dRouting module in kamailio.
We will need to create an add destination button the create inbound route modal
On the backend we will just add to the gwlist for the route

**Comment by devopsec** [comment]
For this release we will only be adding support for 1 failover DID,
this will be enhanced in the future for more failover DID's
