### ISSUE TITLE
Extension to Extension calling not working in dSIPRouter

### ISSUE THREAD

**Issue by ncannon01** [dOpensource/dsiprouter#102]
Two phones registered directly to dSIPRouter using the same domain name are unable to call each other.  Pass-thru PBX configurations are not affected

**Comment by pcour** [comment]
this would be very useful to us as well, we have an old Asterisk box that we want to remove from our DC, and just have dSIP (on top of Kamailio) to register end user phones (Snom, Aastra, Polycom etc) , and these people just want to receive a DID, and make a call out to mobile phones ( or land lines) using our SIP Gateway, dSIP looks just the perfect solution for this, as it would be something my wife could do, or our receptionist in the office, our request is not so much ext to ext but end user voip phone registering with dSIP and being able to make outgoing calls ( and of course receive DID's )

**Comment by mackhendricks** [comment]
It actually already does extension to gateway calls.  It just doesn’t do extension to extension yet.  Give it a try.
