### ISSUE TITLE
flask and other flask deps aren't installed by default

### ISSUE THREAD

**Issue by lgg** [dOpensource/dsiprouter#11]
ubuntu 16.04

`git clone https://github.com/dOpensource/dsiprouter`

**Comment by lgg** [comment]
how to fix:
add check https://github.com/dOpensource/dsiprouter/blob/493840379aa8b915916a6ae6135ed8ccc3038bea/dsiprouter.sh#L374

that pip exists

**Comment by mackhendricks** [comment]
Added to the 0.31 branch
