### ISSUE TITLE
PBX and Domain Routed Extensions from same IP Fail

### ISSUE THREAD

**Issue by matmurdock** [dOpensource/dsiprouter#114]
If you enter a PBX the system that has the same IP of extensions that will be using pass through registration  then calls made from those extensions will be routed incorrectly.

Mat

**Comment by devopsec** [comment]
Could you attach a PCAP and a screenshot, also what version of dSIPRouter is this occuring on?

**Comment by matmurdock** [comment]
This can be closed.  It was resolved by specifying a different port for the trunk vs the port used by pbx extensions registering with the internal pbx.

Mat
