### ISSUE TITLE
Load Balance / Fail Over

### ISSUE THREAD

**Issue by tiefighter** [dOpensource/dsiprouter#119]
I did setup one domain as Pass Thru to PBX to 2 Asteirsk boxes. Each Asterisk has same extension/secret. Extension is registering only on first PBX ID. 
I suppose this setup would allow extension register on 1st, or 2nd PBX in load balance or fail over fashion. Am I wrong?

**Comment by mackhendricks** [comment]
Hi,

You will need to use Realtime DB or Local Subscriber Table for auth if you want load balancing

**Comment by devopsec** [comment]
As @mackhendricks  already mentioned this is currently supported using Realtime DB or Local Subscriber Table for auth.
This feature is already standard in our enterprise platform, please refer to [dsiprouter enterprise](https://dopensource.com/product/dsiprouter-annual-support/) for more information
