### ISSUE TITLE
.container padding

### ISSUE THREAD

**Issue by lgg** [dOpensource/dsiprouter#12]
![image](https://user-images.githubusercontent.com/12018713/31323284-6bd433ac-acae-11e7-8270-99b10b9f7cee.png)

**Comment by lgg** [comment]
![image](https://user-images.githubusercontent.com/12018713/31323289-86906f3a-acae-11e7-8a1a-a6e9d77f1461.png)
![image](https://user-images.githubusercontent.com/12018713/31323292-90353084-acae-11e7-8d48-fa0d8474ac04.png)

the trouble is .container padding

**Comment by mackhendricks** [comment]
Added 0.31 branch
