### ISSUE TITLE
Calling 911 through dsiprouter

### ISSUE THREAD

**Issue by jzrlost** [dOpensource/dsiprouter#121]
We are unable to get 911 calls through dsiprouter.  When we call we receive a "rejected" and it shows an error "SIP/2.0 404 Not Found".  Is this an issue with dsiprouter or kamailio configuration?  I don't remember having this issue before switching over.

In our asterisk we get an error "Dial failed due to trunk reporting Address Incomplete - giving up"

thx josh

**Comment by matmurdock** [comment]
I am not having an issue with this.  Who is your SIP provider?  Can you
tell me more of your setup?

Mat

**Comment by mackhendricks** [comment]
Also, what version are you running?

**Comment by jzrlost** [comment]
I believe the version is 51.  We have trunks from our asterisk server to dsiprouter (single nic) that then passes the traffic to opensips which then passes the traffic to the carrier.I will do some testing bypassing the dsiprouter and see if that makes a difference or not.  Just not sure if its dsiprouter having issues or our opensips having the issue.Sent from my T-Mobile 4G LTE Device<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Mack Hendricks <notifications@github.com> </div><div>Date: 2/26/19  1:18 PM  (GMT-08:00) </div><div>To: dOpensource/dsiprouter <dsiprouter@noreply.github.com> </div><div>Cc: jzrlost <josh@netsteller.com>, Author <author@noreply.github.com> </div><div>Subject: Re: [dOpensource/dsiprouter] Calling 911 through dsiprouter (#121) </div><div>
</div>Also, what version are you running?

**Comment by jzrlost** [comment]
Just wanted to update this ticket.  I went ahead and setup a trunk that bypassed the dsiprouter and went straight to our opensips server.  I was able to make a call to 911 and it went through and had the correct 911 address.  When we try to call 911 using dsiprouter between the PBX and opensips we get the error.  Is there something that we need to adjust for 3 digit dialing through dsiprouter maybe?

**Comment by matmurdock** [comment]
I thought I saw you were prefixing 911 with something right?

Mat

**Comment by jzrlost** [comment]
No prefix just straight 911. I did see another issue posted after mine about prefixing 911, but we use 3 digit only "911". 


thx 

Josh Zeitz 
Netsteller IT Solutions, LLC 
909.583.9770 (office) 
909.583.9771 (fax) 
[ http://www.netsteller.com/ | www.netsteller.com ]

**Comment by matmurdock** [comment]
Ok, that is weird 911 is working for me.

Mat

**Comment by jzrlost** [comment]
Are there logs somewhere I can check to see where the issue maybe? 


thx 

Josh Zeitz 
Netsteller IT Solutions, LLC 
909.583.9770 (office) 
909.583.9771 (fax) 
[ http://www.netsteller.com/ | www.netsteller.com ]

**Comment by matmurdock** [comment]
Try this.  Under Global routes add and entry and under the to prefix add
911 and then reference the gateway you want to use.

Mat

[image: image.png]

**Comment by jzrlost** [comment]
Same thing. The call is rejected at the dsiprouter with SIP/2.0 404 Not Found. 


thx 

Josh Zeitz 
Netsteller IT Solutions, LLC 
909.583.9770 (office) 
909.583.9771 (fax) 
[ http://www.netsteller.com/ | www.netsteller.com ]

**Comment by mackhendricks** [comment]
You can change dSIP configure to support this. We will send you a patch in the morning.

**Comment by jzrlost** [comment]
Any update or patch to get the 911 working?

thx Josh

**Comment by mackhendricks** [comment]
The patch is attached and available on the hotfix branch <https://github.com/dOpensource/dsiprouter/tree/hotfix/911>   It will be merged in with 0.52.  

You can apply the patch by copying the patch to the directory that contains dsiprouter (default: /opt/dsiprouter)

git apply hotfix_911.patch
systemctl restart kamailio

**Comment by kristapsdravnieks** [comment]
I just looked on fix for 911
In ireland emergency numbers can be used 112 as rest of europe or 999 as UK
we also have operator helplines on 19xx 
If I would add more lines just after 911 fixes in kamailio51_dsiprouter.tpl and kamailio51_dsiprouter.cfg

#Europe Emergency services
if($rU=~"^112$")
	return;
#Irish Provider helpline 19XX
if($rU=~"^19[0-9][0-9]$")
	return;

should it work?

**Comment by mackhendricks** [comment]
Yes..that should work.
