### ISSUE TITLE
Optional Suffix Strip for Gateways

### ISSUE THREAD

**Issue by devopsec** [dOpensource/dsiprouter#122]
Prefix stripping is supported by default in dRouting module but suffix stripping is not, we should add the ability to strip from end of request username as well.

## Use Case:

- E911 routing

Any outbound routes the user creates must be over the length of 5 digits, as set by $var(pbx_max_local_digits), in order to route outbound.
For E911 routing this means the user has to prefix the request username from PBX to kamailio and add a rule for stripping the prefix in carrier endpoint configs.

![tmp1](https://user-images.githubusercontent.com/18452447/53451189-3a9ddc80-39ec-11e9-8d9d-65256a325be9.png)

This has a side effect that their E911 outbound routes will all contain the prefix, and clutters up the interface for the user.

![tmp2](https://user-images.githubusercontent.com/18452447/53451203-4093bd80-39ec-11e9-88f6-f76de58f3918.png)

If user could suffix the request username instead, the outbound routes would not need the prefix and would look more intuitive to the user, i.e. 911 would match 911.* (least to most discriminate matching as dRouting does).

There may be some other benefits to this as well, please let me know your thoughts.

**Comment by mackhendricks** [comment]
Or we can just put in an option that always forces 911 calls to be pushed out a carrier.
