### ISSUE TITLE
Rename PBX or Endpoint Bug

### ISSUE THREAD

**Issue by matmurdock** [dOpensource/dsiprouter#125]
When you rename a PBX or Endpoint the entry in the address table is not recreated.  This one was fun to track down.

Mat

**Comment by matmurdock** [comment]
Ok.  Some clarification.  The tag field in the address table is not being updated.  Normally this isn't and issue, however if you also change the IP then that record does not get updated with the new IP.  You will have a record with the previous tag name and an old IP.

Mat

**Comment by mackhendricks** [comment]
Scheduled to be fixed in 0.60

**Comment by mackhendricks** [comment]
Also, removing an endpoint with an assigned Inbound DID will cause the DID not to show up.

**Comment by RichSosa28** [comment]
Validated that this issue is fixed by:
1. Installing dSIPRouter
2. Creating an endpoint group
3. Changing the name and hostname/ip of the endpoint group
4. Running the following commands to see if the address table was updated:
     mysql kamailio;
     select * from address;
Closing this issue now because it is no longer valid.
