### ISSUE TITLE
Add a P-Asserted-Identity (PAI) per PBX

### ISSUE THREAD

**Issue by ftwrobert** [dOpensource/dsiprouter#126]
This is a feature request.

Would it be possible to add a field for the insertion of a PAI when creating a PBX Endpoint? The PAI would be passed upstream when routing to a Carrier, the Carrier would then be able to associate a call with a the carrier's billing group.

**Comment by devopsec** [comment]
P-Asserted-Identity and Remote-Party-ID headers are typically inserted by the PBX.
Adding custom headers per pbx could be a feature to look into though

**Comment by ftwrobert** [comment]
That's a good option, and honestly I hadn't considered it.
One big draw back I do see with setting it on the PBX is that you must trust the PBX to give you the correct information.
If the ITSP provides the sole administration of the PBX's, then this is not an issue, however, once end users have access to the administration GUI, that trust is lost.

**Comment by devopsec** [comment]
Carriers may also set the P-Asserted-Identity or Remote-Party-ID headers depending on your carrier, but it sounds like you are worried about outbound dialing not inbound dialing for this use case.
I think this is a good use case for release v0.60, adding to the roadmap.

If you would like to fork and make a PR you are more than welcome.
Also if you would like to sponsor this feature you can buy support on our regular website and we will get to this quicker: https://dopensource.com/shop/
