### ISSUE TITLE
Installer, Kamailio and WebUI assume /24 subnet for variable INTERNAL_NET

### ISSUE THREAD

**Issue by ftwrobert** [dOpensource/dsiprouter#128]
There are multiple locations where a /24 internal subnet is assumed.
In my case, I am attempting to use a /20 internal subnet.
The best solution would to use proper subnet tools when possible.

Examples of the problem:

dsiprouter.sh
```
#================= DYNAMIC_CONFIG_SETTINGS =================#
# updated dynamically!

export DSIP_PORT=$(getConfigAttrib 'DSIP_PORT' ${DSIP_CONFIG_FILE})
export EXTERNAL_IP=$(curl -s https://api.ipify.org)
export INTERNAL_IP=$(hostname -I | awk '{print $1}')
export INTERNAL_NET=$(awk -F"." '{print $1"."$2"."$3".*"}' <<<$INTERNAL_IP)

#===========================================================#
```

kamailio/kamailio51_dsiprouter.tpl
```
#!define WITH_ANTIFLOOD
##!define WITH_DBCLUSTER
#
#!substdef "!INTERNAL_IP_ADDR!198.211.102.60!g"
#!substdef "!INTERNAL_IP_NET!198.211.102.*!g"
#!substdef "!EXTERNAL_IP_ADDR!207.91.179.59!g"
#
# Kamailio (OpenSER) SIP Server v5.1 - default configuration script
#     - web: http://www.kamailio.org
#     - git: http://sip-router.org
```
```
#!ifdef WITH_SERVERNAT

                        # Create a Record Route based on the destination network
                        $var(local_subnet) = "INTERNAL_IP_NET";
                        # Replace the dots with \.
                        $var(local_subnet) = $(var(local_subnet){s.replace,.,\.});
                        # Repace the 0 with .*
                        $var(local_subnet) = $(var(local_subnet){s.replace,*,.*});

                        if ($rd=~$var(local_subnet)){
                                record_route_advertised_address("INTERNAL_IP_ADDR");
                        }
                        else {
                                record_route();
                        }
#!else
```
```
#!ifdef WITH_SERVERNAT
        #Build a regular expression for figuring out if the request is going towards a local machine
        $var(local_subnet) = "INTERNAL_IP_NET";
        # Replace the dots with \.
        $var(local_subnet) = $(var(local_subnet){s.replace,.,\.});
        # Repace the 0 with .*
        $var(local_subnet) = $(var(local_subnet){s.replace,*,.*});

        xlog("L_DEBUG", "[NATMANAGE] SERVERNAT ENABLED  - rd: $rd, local_subnet: $var(local_subnet) branch(send_socket): $branch(send_socket)");

        if (($rd=~$var(local_subnet)) || (allow_source_address(FLT_CARRIER)))
                rtpengine_manage("media-address=INTERNAL_IP_ADDR");
        else
                rtpengine_manage();
#!else
```

gui/dsiprouter.py
```
    # Dynamically update settings
    fields = {}
    fields['TELEBLOCK_GW_ENABLED'] = 0
    fields['TELEBLOCK_GW_IP'] = '62.34.24.22'
    fields['INTERNAL_IP_ADDR'] = getInternalIP()
    fields['INTERNAL_IP_NET'] = "{}.*".format(getInternalIP().rsplit(".", 1)[0])
    fields['EXTERNAL_IP_ADDR'] = getExternalIP()
    updateConfig(settings, fields)
    reload(settings)
```

gui/settings.py
```
# updated dynamically! ONLY set here if you need static values
INTERNAL_IP_ADDR = '10.148.192.2'
INTERNAL_IP_NET = '10.148.192.*'
EXTERNAL_IP_ADDR = '??.??.??.??'
```

**Comment by devopsec** [comment]
@ftwrobert  I 100% agree, as you've shown in your last message we need a few tools to support this:

1. stable tool for bash scripts, some examples: https://www.cyberciti.biz/faq/linux-subnet-calculator-cidr/
2. either a python package or custom function for subnet calculation (preferably no outside dependencies)
3. a kamailio module for subnet matching, ipops seems to be a good match for this: https://www.kamailio.org/docs/modules/5.1.x/modules/ipops.html

**Comment by mackhendricks** [comment]
@ftwrobert I 100% agree as well.  For ease of development we just assumed a CIDR of 24.  But, we should make this configurable.  We will try to fit this into the release cycle very soon.

**Comment by ftwrobert** [comment]
Thanks guys!
I'm a big fan of this project and hope to be able to contribute as soon as I get some projects off my plate.

**Comment by mackhendricks** [comment]
We will start adding support for different subnet ranges in Endpoint Groups.  The user will be able to select the subnet range.  It would look something like this:

![image](https://user-images.githubusercontent.com/5568984/81697440-0668dd00-9433-11ea-8817-b507bfdd26a6.png)

**Comment by devopsec** [comment]
So from our discussion this is kind of 2 separate issues in one:

1. Ability to use subnet for gateway group media endpoints
2. Ability to use subnet for gateway group routable endpoints

The difference is that media endpoints only need to be able to auth with dsiprouter and send media through rtpengine.
The routes in `kamailio.cfg` that use the 24 CIDR wont be hit by media endpoints.
This is also supported by the `address` table already and would just need and association with the gateway group.

For routable endpoints its another can of worms, because we would somehow have to look up the subnet within the route instead of using the 24 CIDR.
This also is not supported by `dr_gateways` which is the table of routeable gateways.
I don't think this second use case is in very high demand, and would require much more work than the first.

In my opinion, for the first use case we could change the "Endpoints" tab in carrier groups and endpoint groups to "Routable Endpoints" and add a tab called "Media Endpoints".
Association can be done in the `address` table in the description field.

**Comment by devopsec** [comment]
I have some of this implemented in an older version of the repo that didn't make it into a release yet.  
Will take this issue
