### ISSUE TITLE
fix firewall-cmd on ubuntu system

### ISSUE THREAD

**Issue by lgg** [dOpensource/dsiprouter#13]
change firewall-cmd to autodetect?(ufw, iptables)
create other script for firewall needs?

**Comment by mackhendricks** [comment]
Will target this for 0.40 release

**Comment by devopsec** [comment]
Iptables would be underlying api for all the above

**Comment by mackhendricks** [comment]
We don't support Ubuntu right now...so, will close this for right now.  But, looking for help to support more platforms.
