### ISSUE TITLE
Incorrect Port Number When Using TLS

### ISSUE THREAD

**Issue by samehawwad** [dOpensource/dsiprouter#132]
I installed dSIPRouter with RTP and NAT support. My goal is to perform Pass Thru authentication over the TLS protocol. It works just fine over the UDP protocol, but I've managed to compile the TLS module manually and transfer it to dSIPRouter. When using TLS, the source port number Kamailio used to establish a session with the PBX is incorrectly defined in the SIP headers when sending replies back to the clients. So clients communicate with dSIPRouter over TLS port 5061, dSIPRouter communicates with the PBX using a dynamic source port number, and then replies to the clients with that dynamic port number defined in SIP headers (record-route). Finally, the clients try to communicates with dSIPRouter over that port in which Kamailio doesn't even listen on it. Your help is appreciated.

**Comment by devopsec** [comment]
This is the default behavior of the TLS protocol.
That being said dSIPRouter has not been tested with TLS support enabled in kamailio.
This would be a good feature for v0.60.

I'll tag this for v0.60 and please reply with your current TLS settings in your `kamailio.cfg`

**Comment by samehawwad** [comment]
These are the settings used for testing. We will be waiting for version 0.60. Thank you.

#!define WITH_TLS
enable_tls=yes
listen=tls:INTERNAL_IP_ADDR:5061 advertise EXTERNAL_IP_ADDR:5061;
modparam("tls", "config", "/etc/kamailio/tls/tls.cfg")


tls.cfg contains:

[server:default]
method = TLSv1
verify_certificate = no
require_certificate = no
private_key = /etc/kamailio/tls/key.pem
certificate = /etc/kamailio/tls/cert.pem
ca_list = /etc/kamailio/tls/cafile.pem

[client:default]
verify_certificate = no
require_certificate = no

**Comment by voipexpert** [comment]
How far away from version 0.60?

**Comment by pcour** [comment]
please could we have a rough idea when TLS module support in ve 0.60 will be in beta, or released

https://kamailio.org/docs/modules/4.3.x/modules/tls.html

thank you -  we are desparate for this :-)

**Comment by mackhendricks** [comment]
We have added support for TLS into 0.60.  It's now enabled by default.  Please validate your use case and re-open the issue if needed
