### ISSUE TITLE
Feature Requests: PBX Limits

### ISSUE THREAD

**Issue by demonspork** [dOpensource/dsiprouter#136]
We really like this product and it hits exactly on the head what we wanted as a basic SIP trunk platform. There are a few features that are on our list that it is still missing.

I am going to list them here, but let me know if you would prefer an issue per feature. I imagine some of them already exist. 1 and 2 are actually our only current sticking points before going all in.

1) Limit Simultaneous calls Per PBX/Endpoint
2) Failover - Per DID and Per Endpoint Both alternate endpoints or outside numbers.
3) More Bulk Actions like Delete and Edit DID destinations in Bulk
4) PBX/Endpoint filter in Outbound Routes
5) Documentation on setting up alternate listening ports - we often need to get "around" sip helpers and the easiest way is to use ports other than 5060 for SIP.
6) Co-Existence with Siremis. Sometimes you just gotta change that one variable for the snowflake customer and having Siremis available for Tier 3 to jump in and tweak something would probably be helpful.

**Comment by devopsec** [comment]
Preferably we would have an issue per feature but this is fine for figuring out what is viable, for now.

Number 1 is a future feature on our enterprise platform roadmap, that project is in alpha status and will be available through the yearly subscription.
ref: https://dopensource.com/product/dsiprouter-annual-support/

Number 2 is already implemented, carrier groups for outbound failover, secondary DID's for inbound failover (will be expanded in the future)

3: Edit and delete bulk actions are not supported yet and would be good candidates for the next release.
delete in bulk could be done for pretty much all api endpoints but edit in bulk would not be very feasible with the current setup, this may be feasible using bulk uploads to overwrite values, such as in the DID import tool.

Elaborate on number 4.. There are multiple forms of routing and filtering in outbound routes.

5: dynamic SIP port for kamailio would be an easy to implement feature, currently if needed you can edit the kamailio.cfg, but for the project we would have other considerations to add such as updating rtpengine as well.

Number 6: you could install siremis alongside dSIPRouter there is nothing stopping you from doing so.
Is your suggesiton to add that to the install process?

Please keep in mind that we are opensource and do accept PR's! :)

**Comment by demonspork** [comment]
Thank you, that answers most of my questions. Especially about Siremis. Do you have any tips or general rules on making sure no edits I make on that end will impact dsiprouter's functionality?

On question 4 I want to be able to choose which endpoints use which outbound routes and I don't see a way to do that.

![image](https://user-images.githubusercontent.com/432305/55278412-eb441800-52d9-11e9-9441-cc3ae5f1f751.png)


This route also doesn't work at all at the moment, see the Groups thread discussing it https://groups.google.com/forum/#!topic/dsiprouter/bNky4epOVJ4

**Comment by mackhendricks** [comment]
The following two requests have been added to 0.60:

-Limit Simultaneous calls Per PBX/Endpoint
-Failover - Per DID and Per Endpoint Both alternate endpoints or outside numbers.
