### ISSUE TITLE
Change Endpoint Delete Rule Text

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#140]
If you try to delete a Carrier Group Endpoint that's used by a Global Outbound Rules you will get an error message.  The error message needs to be more clear.  Perhaps, "Deleting this rule will cause the following Global Outbound Routes to be deleted"   The current message is displayed below

![image](https://user-images.githubusercontent.com/5568984/55386949-89b0c300-54fe-11e9-9db3-cd62218dab50.png)

**Comment by OmariKing** [comment]
Hey Mack, would I access this through my dsiprouter instance or through my
virtualbox?

**Comment by OmariKing** [comment]
![ithinkididit](https://user-images.githubusercontent.com/46901954/57467637-e5364500-7250-11e9-84c1-3fee9db4c1fc.PNG)
Was this the change you wanted me to make to it?

**Comment by mackhendricks** [comment]
Use your test instance - that’s why you have it.

**Comment by OmariKing** [comment]
I tested it and it works, I realized that It was a change that was specific
to editing endpoints in the carrier groups like the error stated

**Comment by mackhendricks** [comment]
This has been resolved in 0.522
