### ISSUE TITLE
Change Kamailio Mysql password 

### ISSUE THREAD

**Issue by Noksee** [dOpensource/dsiprouter#141]
I want to change the default kamailio database r/w and r/o passwords. Other than the modifications in /etc/kamailio/kamctlrc , is there any other file that needs to be modified for dsiprouter to be aware of the update?

**Comment by mackhendricks** [comment]
This also needs to be changed in the /opt/dsiprouter/gui/settings.py

**Comment by mackhendricks** [comment]
Closing
