### ISSUE TITLE
Add New Domain - Mapped PBX truncates PBX ID

### ISSUE THREAD

**Issue by ftwrobert** [dOpensource/dsiprouter#142]
When adding a new domain, the PBX ID is truncated.

Steps to reproduce:
Turned up a new dSIPRouter install with
`./dsiprouter.sh install -all -servernat`
Add a new PBX with an Internal IP and IP Auth (The first entry get's a PBX ID of 64)
Add a new Domain by setting 64 as the PBX ID and choose Pass Thru to PBX

The web interface and the database now show Mapped PBX as 6 rather then 64.

**Comment by marc8lange** [comment]
I can confirm the same exact error using ./dsiprouter.sh install

**Comment by ncannon01** [comment]
After reproducing this use case we have noticed this bug for the domain feature. An update is targeted for Friday.
