### ISSUE TITLE
Installation instructions do not work for 0.52

### ISSUE THREAD

**Issue by YourHuckleberry** [dOpensource/dsiprouter#143]
Install instructions for 0.51 do not work with 0.52.  

Old version was 'install -rtpengine -nat'

New version appears to require 'install -servernat -all' as equivalent.

**Comment by YourHuckleberry** [comment]
Found updated instructions.  Problem appears to be that the main README.md in master branch still links specifically to 0.51 instructions.

**Comment by devopsec** [comment]
I see what you mean, will update the README link to the docs

**Comment by mackhendricks** [comment]
Fixed in v0.521
