### ISSUE TITLE
FusionPBX Domain Support Causes Domains not to work

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#144]
When I enable FusionPBX Domain Support it breaks the ability to use the Domain menu option to view the domains or to manually add domains

**Comment by devopsec** [comment]
Hmmm that’s an odd compatibility break, what’s the error?

**Comment by mackhendricks** [comment]
It’s the attributes being rendered on the Domain page.  They don’t exit when a dynamic domain is created.  I believe we have a fix for this
