### ISSUE TITLE
Admin Password is being Reset on Reboot

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#146]
The Admin Password is being reset due to the logic used to figure out if the instance is running on AWS.   

Why are we checking if the instance is running on AWS?  

Good question, we added in support to run on AWS so that we could create an Amazon AMI that we could offer on the AWS Marketplace.

But, this logic along with some other change has caused this issue.

**Comment by mackhendricks** [comment]
The issue is not fixed in the v0.521 branch

**Comment by devopsec** [comment]
What environment is this happening in? This should only effect AMI’s at this point.
Easy fix tho, we’ll have the startup command removed from dsip-init service after the image resets the password (initial boot after creating instance)

**Comment by mackhendricks** [comment]
Fixed in v0.521
