### ISSUE TITLE
Anti-Flood Module is blocking Defined Carriers and PBXS

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#148]
The Anti-Flood features need to be updated so that it doesn't block defined Carriers and PBX's.   So, Carriers and PBX's are chatty and will trigger the Anti-Flood Module

**Comment by devopsec** [comment]
It would be nice if there was a way to configure the module settings per IP, to make the settings more lenient for known carriers. That would be ideal, bcuz if we add all the carriers and pbx to a whitelist then all an attacker has to do is spoof the IP to one of the carriers or pbx and they can flood unfiltered
