### ISSUE TITLE
for what .settings.py.swp file is needed?

### ISSUE THREAD

**Issue by lgg** [dOpensource/dsiprouter#15]
i think that it's an error, that .settings.py.swp is in repo

**Comment by lgg** [comment]
ping @mackhendricks

**Comment by mackhendricks** [comment]
Hey...Good stuff on all the issues and the pull request.  I will review and merge.  

In regards to this issue, this was mistake.  I will update the ignore file

**Comment by mackhendricks** [comment]
Added to 0.31 branch
