### ISSUE TITLE
Feature Request: Transcoding with RTPEngine

### ISSUE THREAD

**Issue by jzrlost** [dOpensource/dsiprouter#152]
I have read that RTPEngine has a transcoding ability already.  Would it be hard to get this feature enabled or configurable?  There seem to be settings to have it only transcode when both sides cannot agree on the same codec or maybe they both don't support the same codec.

**Comment by mackhendricks** [comment]
I think Transcoding is on by default based on the readme: https://github.com/sipwise/rtpengine

But, I don't think we tested this as of yet.  Have you validated that transcoding is not working

**Comment by jzrlost** [comment]
If I change my PBX to anything besides the standard ulaw then I get a "488 Not Acceptable Here" from Dsiprouter with calls.

**Comment by jzrlost** [comment]
According to sipwise the transcoding has to be engaged. - "Even though the transcoding feature is available by default, it is not automatically engaged for normal calls. Normally rtpengine leaves codec negotiation up to the clients involved in the call and does not interfere. In this case, if the clients fail to agree on a codec, the call will fail.  The transcoding feature can be engaged for a call by instructing rtpengine to do so by using one of the transcoding options in the ng control protocol, such as transcode or ptime (see below)."

**Comment by mackhendricks** [comment]
We will evaluate adding this to 0.523

**Comment by devopsec** [comment]
allowing this is the kamailio config is not very hard to do, see section 5.2 of kamailio's rtpengine documentation:
https://www.kamailio.org/docs/modules/stable/modules/rtpengine.html

The issue is implementing in the install process all these codecs will quickly become hard to keep up with, especially when webrtc encoding and encryption  / decyption on the wire come into the picture.

I recommend we add the ability to enable this feature in kam configs through our dsiprouter.sh script, but either fund codec support per sponsorship / customer or we could move it to the enterprise version

**Comment by jzrlost** [comment]
What do you mean "implementing in the install process all these codecs will quickly become hard to keep up with"?  Isn't there maybe a dozen (give or take) codecs out there and probably only half of those are main stream.  Besides G729 all the codecs are free also.  With the newer Opus codec I have a feeling that most of the others will end up going to the way side.  Opus with encryption will probably become the defacto in the next few years.  I'm not saying that paying to have the option is a big deal either if the price is fair.  This software has come a long way and does a great job (looking forward to the improvements).  I would just hate to see it turn into the standard "free" in the beginning or basic uses and then start to nickel and dime it's users down the road.  We have all seen it happen to great software.

**Comment by devopsec** [comment]
@jzrlost I 100% understand your concerns. There is always a balancing act between giving back to the community and funding the project itself. 

Specifically with this issue we can make transcoding available in RTPEngine but I think the number of codecs is large enough that we would need some help to support them out of the box. Yes its true that there are around 9 mainstream codecs and opus is very promising but that is still a considerable amount of work.

Don't forget that we are Opensource and you can submit a PR at anytime!

**Comment by mackhendricks** [comment]
@devopsec Does RTPEngine come with the codecs or would we have to manage the install of the codec?

**Comment by devopsec** [comment]
According to their github: https://github.com/sipwise/rtpengine#transcoding
