### ISSUE TITLE
Invite contains extraneous SIP information in the message body

### ISSUE THREAD

**Issue by jzrlost** [dOpensource/dsiprouter#153]
We have a PBX that connects through a VPN to our internal network.  So the PBX has 2 IP addresses, but only pass one to Kamailio (Kamailio is picking up 2).  The BPX has the local remote address (192.168.1.250) and it has the VPN assigned address (172.17.1.100).  Kamailio has IP address 172.17.1.12.  Once the traffic passes through Kamailio instead of just using the VPN address it picks up both address and adds them to the header.  This normally is not an issue but we have found that sometimes the calls fail with a "513 Message too large" from the remote SIP server of the number we are calling.  We are running .51 (didn't want to switch to .52 until the bugs are fixed) with -rtpengine -servernat.  Anyone see this issue before?

**Comment by mackhendricks** [comment]
Hey,

I have not seen this issue before.
