### ISSUE TITLE
CDRs

### ISSUE THREAD

**Issue by Noksee** [dOpensource/dsiprouter#157]
I'm trying to integrate Siremis with dSIP. So far so good. However, I can't seem to get the CDRs working. The only difference I see between the dSIP kamailio.cfg and the Siremis' is **calltype=$avp(calltype)"** added to **modparam("acc", "db_extra",**
Anyone have CDRs working?

**Comment by mackhendricks** [comment]
Hey Noksee...can you ask this question on the dSIPRouter forums: https://groups.google.com/forum/#!forum/dsiprouter

But, CDR's should be working in the 0.52 release.
