### ISSUE TITLE
A DID assigned a Primary and Secondary PBX can't go back to just a Primary PBX

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#160]
Once, a DID is configured to have a Primary and Secondary PBX it can not be undone.  We need a way to specify "None" in the Secondary List.    This should cause the secondary server to be removed from the dr_rules table and whatever else we need to do.

**Comment by OmariKing** [comment]
I think that they may both be pointing to a PBX and since its like that they point to the same copy and cant be edited to go from primary and secondary to just primary. I suggest having the secondary point to its own copy so that when we switch back we can still keep the primary.
