### ISSUE TITLE
No New INVITE after challenge 

### ISSUE THREAD

**Issue by tiefighter** [dOpensource/dsiprouter#166]
I'm testing version 0.522
Fresh install, one PBX and one domain in passthru mode.
Usually, after asterisk challenge authentication, sip proxy should send authentication hash on new INVITE. But It's not happening.
![image](https://user-images.githubusercontent.com/4549323/57855442-0eab1f80-77c1-11e9-98b9-52909c43bcb2.png)

**Comment by mackhendricks** [comment]
We will look into this issue and try and reproduce

**Comment by mackhendricks** [comment]
Please try a new install from the master branch.  We did find a regression that might of caused this.
