### ISSUE TITLE
[bug] reload kamailio from web

### ISSUE THREAD

**Issue by lgg** [dOpensource/dsiprouter#17]
* kamailio.cfg is broken -> kamailio not running
* in web gui press "reload kamailio" -> got success notification
but kamailio still not running

**Comment by khorsmann** [comment]
Okay - i found it - Patch will follow tommorow

**Comment by lgg** [comment]
@khorsmann let's create it together? 

Also, i think there is no check in code for kamailio process existence.

bug reproduce:
```
1. service kamailio stop
2. in web gui press "reload kamailio" -> got success notification
but kamailio still not running
```

but on step 2 there should be a warning: kamailio not running, check logs


or you think 
```
ERROR: connect_unix_sock: connect(/var/run/kamailio//kamailio_ctl): No such file or directory [2]
ERROR: connect_unix_sock: connect(/var/run/kamailio//kamailio_ctl): No such file or directory [2]
```

is reason for this?

**Comment by khorsmann** [comment]
It's shell vs Javascript. The Python executed commands don't return a return code.
The shell return code should be 0 for true. 
In js it is 1 for true. 

```
@app.route('/reloadkam')
def reloadkam():
       try:
           subprocess.call(['kamcmd' ,'permissions.addressReload'])
           subprocess.call(['kamcmd','drouting.reload'])
           session['last_page'] = request.headers['Referer']
           return json.dumps({"status":"1"})
       except:
               return json.dumps({"status":"0"})
```     

Should be 

```
@app.route('/reloadkam')
def reloadkam():
    return_code = subprocess.call(['kamcmd' ,'permissions.addressReload'])
    return_code += subprocess.call(['kamcmd','drouting.reload'])
    session['last_page'] = request.headers['Referer']
    if return_code == 0:
        status_code = 1
    else:
        status_code = 0
    return json.dumps({"status": status_code})
```

**Comment by mackhendricks** [comment]
Hey Guy's,

Great stuff.  I will incorporate it in right away.

**Comment by khorsmann** [comment]
@mackhendricks i add an pull-request for this. In my case this is enough and not over-engineered. 

Later i will try to use this route with an api-request directly to kamailio via network cos my dsiprouter will not sit on the same maschine as the kamailio-proxy.

**Comment by mackhendricks** [comment]
Has been added to 0.31 branch
