### ISSUE TITLE
Dashboard not working

### ISSUE THREAD

**Issue by YourHuckleberry** [dOpensource/dsiprouter#170]
I recently upgraded from 0.52 to 0.522.  The dashboard is not working.  Running in -debug mode shows that API calls are failing (which is how I presume it is getting the numbers).

![image](https://user-images.githubusercontent.com/5511530/58061938-4827b600-7b46-11e9-92ef-2f3a243461ad.png)

Thinking it might have something to do with my upgrade, I spun up a fresh Digital Ocean instance and installed clean - Same result, same errors.

((( EXCEPTION )))
[CLASS]: <class 'requests.exceptions.ConnectionError'>
[VALUE]: HTTPConnectionPool(host='127.0.0.1', port=5060): Max retries exceeded with url: /api/kamailio (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd0f94a0a58>: Failed to establish a new connection: [Errno 111] Connection refused',))
[RESPONSE]: None
[REQUEST]: <PreparedRequest [GET]>
((( BACKTRACE )))
[FILE]: /opt/dsiprouter/gui/modules/api/api_routes.py
[LINE NUM]: 23
[FUNCTION]: getKamailioStats()
[SOURCE]: r = requests.get('http://127.0.0.1:5060/api/kamailio',json=payload)

**Comment by mackhendricks** [comment]
Hi, what OS are you using.  I want to try to reproduce.

**Comment by YourHuckleberry** [comment]
I'm having this problem with Debian 9.7 and CentOS 7.6.

The fresh install attempt was CentOS.  Can try with Deb/buntu and see if it
works.

**Comment by YourHuckleberry** [comment]
Found the problem.  Kam is only listening UDP on 5060 and these requests are coming TCP.

Added to kamailio.cfg and now working:

>listen=tcp:127.0.0.1:5060

**Comment by mackhendricks** [comment]
Is this on CentOS 7?  Because Debian 9.9 with Kamailio 5.1.8 works without an issue.  5060 is automatically listening on tcp for me.   But, we can be explicit and add that listen attribute into the configuration.

**Comment by mackhendricks** [comment]
Was this on Amazon?  I just had the same thing happen on an Amazon image running Debian 9.6.  I’m not sure how Kamailio figures out when to expose tcp and when not.  Our configuration file doesn’t disable tcp support.   We will figure it out or we will explicitly specify a listen attribute.

**Comment by YourHuckleberry** [comment]
This was digital ocean.  It happened on both CentOS and Debian installs.
