### ISSUE TITLE
kamailio_rating stored procedure calls billing_rates table that doesn't exist unless Siremis is installed

### ISSUE THREAD

**Issue by stancel** [dOpensource/dsiprouter#182]
I was trying to get up and running with a fresh install of the current latest stable release (0.522). However after installing and configuring everything, I noticed errors in the kamailio.log file around the `kamailio.billing_rates` table not being found.

Here is a sampling of the errors from kamailio.log:

		Jun  9 02:47:24 sip /usr/sbin/kamailio[23243]: ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: Table 'kamailio.billing_rates' doesn't exist (1146)
		Jun  9 02:47:24 sip /usr/sbin/kamailio[23243]: ERROR: <core> [db_query.c:189]: db_do_raw_query(): error while submitting query
		Jun  9 02:47:24 sip /usr/sbin/kamailio[23243]: ERROR: sqlops [sql_api.c:264]: sql_do_query(): cannot do the query [call kamailio_rating('default')]

When grepping through the kamailio configuration file `kamailio/kamailio51_dsiprouter.cfg `, I noticed this stored procedure is used in a customized CDR route from Siremis:

	route[CDRS] {
	    sql_query("cb","call kamailio_cdrs()","rb");
	    sql_query("cb","call kamailio_rating('default')","rb");
	}

If the tables from Siremis are needed I would propose that they either:  

* be listed as a dependency
* should be setup in the installer script
* the needed tables should be created as part of the installation process

**Comment by stancel** [comment]
Seems related to #88

**Comment by mackhendricks** [comment]
Good catch...we will remove this line for now.  We aren't planning on adding billing and rating at this time.

**Comment by devopsec** [comment]
from @mackhendricks and my discussion we are not using the billing portion of CDR's so we are going to remove the billing_rating call
