### ISSUE TITLE
Discovered ipv6 addresses are not correct

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#183]
I notice that during install we are using the ipv6 address in the RTPEngine configs.  I don't think that is a problem, but the installer isn't finding the right ipv6 address.  I'm using DigitalOcean so the problem might be isolated to DigitalOcean

**Comment by devopsec** [comment]
ipv6 is not fully supported yet, will be turning it off by default in this release.
will create issue to fully support in v0.55
