### ISSUE TITLE
[bug] original kamailio config was deleted

### ISSUE THREAD

**Issue by lgg** [dOpensource/dsiprouter#19]
![image](https://user-images.githubusercontent.com/12018713/31461904-86bfe1f8-aed3-11e7-897b-5ac6e12d383d.png)

i don't know how this happened, but i think it's something with this line
https://github.com/dOpensource/dsiprouter/blob/5cbd3ea1b5a3b584b4fea043c9ecfec6396d9ee8/dsiprouter.sh#L90

**Comment by lgg** [comment]
hmm i think the cause might be few `./dsiprouter.sh install` repeatedly one by one

**Comment by lgg** [comment]
fix: add unixtime to file backup

**Comment by khorsmann** [comment]
I would prefer that the installer only informs you and don't do anything with the system Kamailio config.
