### ISSUE TITLE
PBX - Inbound: PBX INVITE TIMER 

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#195]
The global PBX INVITE TIMER is set to 32 seconds.  In some cases, the PBX will send a 100 (trying) or 180 (ringing).  But, currently, if it takes longer then 32 seconds the call is considered a failure and SIP error code 503 (Service Unavailable) is sent back.   

We need to force the timer to stop counting once we receive a SIP code of 100 or 180

**Comment by devopsec** [comment]
seems like we are resetting this in the location route to 120 sec for INVITE and 10 sec for non invite
see the following: https://github.com/dOpensource/dsiprouter/blob/v0.523/kamailio/kamailio51_dsiprouter.cfg#L1353
seems like there was a discussion on this in the sr-users mailing list not too long ago:
https://lists.kamailio.org/pipermail/sr-users/2016-November/095098.html

**Comment by mackhendricks** [comment]
This is tricky problem.  In testing this, I realized that we don't want to stop the counter because Kamailio would never move onto the second server if the primary server never responds to the 100 or 180.  

I lowered the scope to only dealing with SIP 100 messages coming from PBX's- we can add SIP 180 (ringing) messages at a later date if needed.

So, I just increased the INVITE TIMER by two once we see a SIP 100 Message.  This will give the endpoint more time to respond to the invite and it will trigger the secondary server if it doesn't answer. This protects us from situations where the primary server doesn't respond after the SIP 100 message and causes a situation where the secondary server is never invoked. 

The default value of the INVITE TIMER is now 32 seconds, so it would be extended to 64 seconds if primary server responds with a SIP 100 message.  

Note, the SIP client may cancel the call before it reaches the second server.  So, the pbx_invite_timeout will need to be adjusted to your environment.  This setting is in the /etc/kamailio.cfg file after installation.

**Comment by mackhendricks** [comment]
In talking with the stakeholder for this feature request they felt that the logic for this needs to consist of:

- If an INVITE going to a PBX receives a SIP 100 (Trying) then we should reset the INVITE Timeout value to a different value.  We named that value pbx_invite_timeout_aftertry.  The main intent is that we at least know the PBX is alive and theirs a high probability that it will respond, but it just needs more time.

- If the INVITE doesn't receive a SIP 100 then the default INVITE Timeout will be adhered too, which is pbx_invite_timeout.  This will cause the system to failover to the secondary PBX after the timeout is reached.
