### ISSUE TITLE
Inbound DID Mappings not Displayed After Deleting PBX

### ISSUE THREAD

**Issue by devopsec** [dOpensource/dsiprouter#197]
When PBX's are deleted the query for inbound mappings does not return the rules that are related to those PBX's
This is related to #181 
We should display a warning and delete the related inbound mappings from dr_rules table when a PBX is deleted, similar to how we are doing for carriers and outbound routes

**Comment by jzrlost** [comment]
We deleted a PBX and now have those numbers stuck in the database.  When we try to add the number again it gives an error: Duplicate DID's are not allowed.  How do we remove these numbers from the database?

**Comment by RichSosa28** [comment]
Validated this issue. Reproduced it by:
1. Installing dSIPRouter
2. Creating an Endpoint Group
3. Creating an Inbound DID and map it to the Endpoint Group created
4. Delete the Endpoint Group
5. Run these commands to view the dr_rules table

mysql kamailio;
select * from dr_rules;

The related inbound mappings are still present in the table even after deletion of the endpoint group.
Possible Solution:
Tell user that when deleting an endpoint group, the corresponding inbound DID mapped to that endpoint group will be deleted from the table.

**Comment by RichSosa28** [comment]
This issue correlates to issue #78.

**Comment by devopsec** [comment]
@RichSosa28 thanks for checking this out, closing this one in favor of tracking this via issue #78
