### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by bshirazi** [dOpensource/dsiprouter#209]
Hi
Thanks for good product.
Please consider supporting  Ubuntu 18.04.
If your install script support just installing rtpengine you will attract many new users.
Regards
M.Shirazi

**Comment by mackhendricks** [comment]
Closing due to no response

**Comment by bshirazi** [comment]
Hi
Sorry for delay
Actually this is 2 feature request:
1- supporting ubuntu 18.04
2-Supporting just rtpengine installs. Imagine sometimes rtpengine located near the customer and kamailio is in cloud or sometimes we have one kamailio and multiple rtpengine

Regards
M.Shirazi
