### ISSUE TITLE
Support different Caller ID for each outbound Carrier

### ISSUE THREAD

**Issue by marcioconceicao** [dOpensource/dsiprouter#213]
Hi,

@mackhendricks this is a feature request.

Some providers/carriers need different caller id formats, then we need a feature to make this possible.

We need to strip characters and prefix others. 

Bellow is a sample case.

Provider A requires caller id in local format eg. 01223132
Provider B requires caller id in e164 format eg 3531223132
Provider C requires caller id in e164 format with + prefix eg. +3531223132

Thank You

Marcio

**Comment by devopsec** [comment]
Is the carrier strip & prefix feature not enough to cover your use cases?
I believe this is covered already

**Comment by RichSosa28** [comment]
This feature request is already implemented. Closing this issue because it is no longer valid.
