### ISSUE TITLE
P-Registrar-Error: usrloc_contact_insert failed

### ISSUE THREAD

**Issue by areaeuro** [dOpensource/dsiprouter#214]
After a variable amount of time (10+ Days), I get the following error when trying to register freeswitch (Fusion PBX) end points.
This is the SIP packet sent back to the end point:

> SIP/2.0 500 I'm terribly sorry, server error occurred (1/SL)
> Via: SIP/2.0/UDP .....
> From: .....
> To: .......
> Call-ID: ......
> CSeq: 13362270 REGISTER
> P-Registrar-Error: usrloc_contact_insert failed
> Content-Length: 0

The only way around this error I have found so far is rebooting the server.

Any ideas on how to get this stable ?

**Notes**
dSipRouter Version: 0.523
Debian 4.9.189-3+deb9u2

**Comment by RichSosa28** [comment]
Closing this issue because it is no longer valid.
