### ISSUE TITLE
Log the PBX that we send to

### ISSUE THREAD

**Issue by jtc267** [dOpensource/dsiprouter#215]
We're doing round robin load balancing using `v0.5221-rel`

The only significant change we made to the config file is changing
```
      if (\$avp(domain_auth_type) == "local") {
        if (!auth_check("\$fd", "subscriber", "3")) {
            auth_challenge("\$fd", "0");
            exit;
        }
      }

```
to
```
                if ($avp(domain_auth_type) == "local") {
                    #if (!auth_check("$fd", "subscriber", "3")) {
                    #   auth_challenge("$fd", "0");
                    #   exit;
                    #}
                    xlog("L_DEBUG","[AUTH: DOMAIN AUTH]: Skipping authentication for local subscriber table");
                }
```

We'd like to log the PBX that we're sending calls to. Ideally the IP address of the PBX we're sending calls to. We're using asterisk realtime to authenticate. Can someone please help me with this?

(I would've posted in the support forum but I could not find a way to submit a request)

**Comment by Mackey22** [comment]
I would also love an answer to the above!

**Comment by mackhendricks** [comment]
Let me look into this.

**Comment by Mackey22** [comment]
Thanks Mack - let me know what you find!

**Comment by mackhendricks** [comment]
Closing this ticket because we added the capability via CDR's
