### ISSUE TITLE
Debian 10 support?

### ISSUE THREAD

**Issue by blackyzero** [dOpensource/dsiprouter#217]
Hello,

Is that possible to run dsiprouter on Debian 10?
Thank you.

**Comment by devopsec** [comment]
debian 10 support isn't planned yet, but will eventually come in the future.
You are more than welcome to test yourself and commit back in a PR any issues you end up resolving.
The install script currently doesn't check for debian 10 so you would have to add that in first

**Comment by matmurdock** [comment]
Side question, what is the recommended os?

Mat

**Comment by devopsec** [comment]
Debian 9 is our high priority OS, Centos 7 also gets the same patches but we typically develop on Debian 9 first before pushing the updates to Centos.

**Comment by matmurdock** [comment]
Sounds good.  That is what I have been using.

Mat

**Comment by andrew867** [comment]
When installing on a Digital Ocean Debian 10 droplet I had to manually install gnupg using:

apt install -y gnupg
