### ISSUE TITLE
Grandstream UCM6202

### ISSUE THREAD

**Issue by jzrlost** [dOpensource/dsiprouter#219]
We have disrouter .523 with an internal IP and NAT setup.  Asterisk PBX works fine (internal LAN), both inbound and outbound.  We just picked up a UCM6202 which is suppose to be using asterisk, but we cannot get the outbound to work properly.  Inbound works great, outbound hangs up when the remote party answers.  We do get 2 way audio during the 2 second call before it hangs up.  We bypassed dsiprouter and everything seems to work fine.  Any ideas?

**Comment by matmurdock** [comment]
Can you post a packet capture?

Mat

**Comment by jzrlost** [comment]
Is there a way to attach a pcap?Sent from my T-Mobile 4G LTE Device<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: matmurdock <notifications@github.com> </div><div>Date: 1/6/20  7:15 PM  (GMT-08:00) </div><div>To: dOpensource/dsiprouter <dsiprouter@noreply.github.com> </div><div>Cc: jzrlost <josh@netsteller.com>, Author <author@noreply.github.com> </div><div>Subject: Re: [dOpensource/dsiprouter] Grandstream UCM6202 (#219) </div><div>
</div>Can you post a packet capture?

Mat

**Comment by matmurdock** [comment]
You can.

Mat

**Comment by jzrlost** [comment]
Finally was able to do a packet capture on disprouter.  172.31.0.100 (pbx) <-VPN->172.17.1.14 (dsiprouter) <-> 64.136.174.30 (carriers signaling IP) 69.85.181.73 (carriers RTP IP).  The call works good inbound.  Outbound you can hear me answer my cell phone and even hear the feed back from the VoIP phone.  Sounds like 2 way audio then the outbound call drops after 2 seconds.
[outbound_failed.zip](https://github.com/dOpensource/dsiprouter/files/4057175/outbound_failed.zip)

**Comment by jzrlost** [comment]
Mat,
   You have any suggestions or idea why the call is dropping after 2 seconds?  It seems like the carrier is sending the bye command as soon as the call is answered.  Very strange.  I may open a ticket with them to see what they are getting or not getting on their end.  If we bypass dsiprouter the call seems to work fine.

**Comment by jzrlost** [comment]
Opened a ticket with the carrier.  This was their reply after looking at the capture "Looking at the call it appears we are not receiving an ACK to the 200 we send thus causing a resend before disconnecting the call."  Is this something that DSiprouter is doing or not doing?  If we connect the UCM directly to the carrier it works fine.

**Comment by jzrlost** [comment]
No resolution found at this time.  May try the UCM again later on a newer version.
