### ISSUE TITLE
407 Proxy Authentication Required in DID Call

### ISSUE THREAD

**Issue by irfanrifai** [dOpensource/dsiprouter#22]
I had add carriers and add my pbxs. outgoing call already okay, but while incoming call come from carrier to DID number its come 407 Proxy auth required. Whats wrong? 

U X.X.X.X:5060 -> X.X.X.X:5080
SIP/2.0 407 Proxy Authentication Required. Add the PBX or Carrier IP using GUI.
Via: SIP/2.0/UDP X.X.X.X:5080;rport=5080;branch=z9hG4bKNygKtcU9j87ZH;received=X.X.X.X.
From: "Haha" <sip:someone@X.X.X.X>;tag=Xa4Fg0p0NamyS.
To: <sip:+someone@X.X.X.X>;tag=e2cb51a352b1911fcfae7d572feeeca4.9486.
Call-ID: 768f81ec-4646-1236-4e91-f40343033e34.
CSeq: 115128399 INVITE.
Server: kamailio (4.2.0 (x86_64/linux)).
Content-Length: 0.

Im already newbie with kamailio

**Comment by mackhendricks** [comment]
Did you click the reload Kamailio button?  Also,  did you restart Kamailio once you installed DSIPRouter

**Comment by irfanrifai** [comment]
yes, im already reload the button and also restart Kamailio. its necessary to restart kamailio after first installation of DSIProuter?

**Comment by mackhendricks** [comment]
Correct.  Because it replaces the Kamailio.cfg file with it’s version.

Is the carrier ip that is sending the invite in the carrier list.  Sometime a carrier has multiple signaling ip’s.  Look in the invite and see if the ip coming from the carrier matches what’s in the carrier GUI.

If still having a problem, then I can schedule a screenshare to see what’s going on.

**Comment by irfanrifai** [comment]
i think its no problem with the carrier because invites is come from carriers ip to. and the carriers  has single signaling ip only. like in WEB GUI.

**Comment by mackhendricks** [comment]
Okay...let’s do quick session.  Send an email to support@dopensource.com and I will schedule it for later today.  Specify your time zone in the email.

**Comment by mackhendricks** [comment]
Let me know when you are ready to do a screenshare.  I want to see if you are hitting a bug or some other issues.

**Comment by irfanrifai** [comment]
Hello mack, im sorry cant reply quickly. btw my dsiprouter installation had uninstalled. i will reinstall it immediately and tell you if i have this problem again. Thanks for your advice :)

**Comment by mackhendricks** [comment]
I will close this for now...but, please re-open once you are ready
