### ISSUE TITLE
Updating "Carrier Groups" Breaks IP authentication in dsiprouter version 0.524

### ISSUE THREAD

**Issue by jbarfield** [dOpensource/dsiprouter#223]
**Release Version 0.524**

**Issue:**
Updating carrier IP's in the UI appears to break the way that the database records are read when the ID's are out of order or if there are large blocks of unused numerals (like skipping from 10-20). It feels like an ID mismatch or out of order issue which may be related to SQLAlchemy I am assuming. I am not a dev though I'm just guessing based off of the behavior of Kamailio, when backed by what appears to be a good table structure in 'dr_gatways' and 'dr_rules' tables. When this happens calls suddenly start getting rejected with 407 errors as soon as you either edit or update an IP address in an existing carrier group. I did determine that if I delete the carrier and then add it back in that it seems to restore services. But if you go to a carrier that has a lower ID in the list and make any changes it will break the newly added carrier and you have to do it all over again.  I just kind-of resolved a several day (in one carrier/customer issue) and a several hour production outage in several others over this issue.  I wonder if it is somehow related to: https://github.com/dOpensource/dsiprouter/issues/163 which I reported on recently as well pertaining to outbound route's not updating properly with prefix'es. 

**Work around:**
I downloaded the 'dr_gateways' and the 'dr_rules' tables to csv files and updated the numeric index order, group ID's, etc to the now current settings. I then stopped kamailio, overwrote the table from the new CSV file, restarted dsiprouter and kamilio then Voila all was good again. It seems to me like using the freeswitch/fusion method of `uuid` for ID column indices on a table makes more sense then the current auto-increment method because Kamailio or sqlalchemy or some part of dsipr appears to dislike gaps in ID numbers when traversing through and building the internal Auth ACL's.

**Comment by cruzer45** [comment]
hey @jbarfield.

Cleaning up these issues. 
Is this still happening in recent versions of the app?

**Comment by mackhendricks** [comment]
This is no longer an issue - closing ticket
