### ISSUE TITLE
Installation stops on collecting pyspark

### ISSUE THREAD

**Issue by mrkp71** [dOpensource/dsiprouter#224]
Hi, I installed fresh Debian 9.6.
after executing install command of dsiprouter all things are ok until collecting pyspark.
I waited about 1h but no change.
Any idea and help?

**Comment by mackhendricks** [comment]
We are removing pyspark from the install.  It will only be installed if needed.

**Comment by mackhendricks** [comment]
We have removed pyspark from the install starting at 0.60
