### ISSUE TITLE
Password blank with Debian 9 install on Proxmox

### ISSUE THREAD

**Issue by compuwizz** [dOpensource/dsiprouter#228]
When doing a fresh install, the password is blank for the GUI. I can set a password in /opt/dsiprouter/gui/settings.py and issue the dsiprouter restart command to set the password. However when I reboot the VM, the password is removed. 

Tracing things down, the instance is being identified as an AWS instance and thinks it needs to regenerate a new password and API key every time it boots.

**Comment by mackhendricks** [comment]
This is scheduled for 0.62
