### ISSUE TITLE
auth.log - Unable to open env file: /etc/default/locale: No such file or directory

### ISSUE THREAD

**Issue by marcosviniciusb** [dOpensource/dsiprouter#231]
Unable to open env file: /etc/default/locale: No such file or directory
session opened for user root by (uid=0)

**tail -f /var/log/auth.log:**                                                                                                         

May 2014:35:01 dSIPRouter CRON[48573]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory
May 20 14:35:01 dSIPRouter CRON[48573]: pam_unix(cron:session): session opened for user root by (uid=0)
May 20 14:35:01 dSIPRouter CRON[48574]: pam_unix(cron:session): session closed for user root
May 20 14:35:01 dSIPRouter CRON[48573]: pam_unix(cron:session): session closed for user root
May 20 14:36:01 dSIPRouter CRON[48608]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory
May 20 14:36:01 dSIPRouter CRON[48608]: pam_unix(cron:session): session opened for user root by (uid=0)
May 20 14:36:01 dSIPRouter CRON[48608]: pam_unix(cron:session): session closed for user root
May 20 14:37:01 dSIPRouter CRON[48670]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory
May 20 14:37:01 dSIPRouter CRON[48670]: pam_unix(cron:session): session opened for user root by (uid=0)
May 20 14:37:01 dSIPRouter CRON[48670]: pam_unix(cron:session): session closed for user root
May 20 14:38:01 dSIPRouter CRON[48709]: pam_env(cron:session): Unable to open env file: /etc/default/locale: No such file or directory
May 20 14:38:01 dSIPRouter CRON[48709]: pam_unix(cron:session): session opened for user root by (uid=0)
May 20 14:38:01 dSIPRouter CRON[48709]: pam_unix(cron:session): session closed for user root

**Comment by mackhendricks** [comment]
I'm trying to reproduce.  What OS is this?

**Comment by RichSosa28** [comment]
Was able to open this file with Debian 10 on the latest release. Closing this issue since there isn't a valid reproducible use case.
