### ISSUE TITLE
v0.61 Global Outbound Routes adding and removing From Prefix

### ISSUE THREAD

**Issue by ednt** [dOpensource/dsiprouter#234]
select * from dr_rules;
shows goupid 8000

I add a From Prefix and apply it.

select * from dr_rules;
shows goupid 10000 and no entry in prefix.

If I remove the From Prefix

select * from dr_rules;
shows goupid 10000 and no entry in prefix.

No call was possible.

If I edit the entry again without any change and press update

select * from dr_rules;
shows goupid 8000

and the world is Ok again.

**Comment by devopsec** [comment]
@ednt 10000-19999 is reserved for the LCR functionality and 20000-29999 is reserved for the failover functionality.  
Are you still having this issue in the latest release?
