### ISSUE TITLE
v0.61 and CARP vip address

### ISSUE THREAD

**Issue by ednt** [dOpensource/dsiprouter#236]
We use ucarp for a redundant solution.
This means we have 2 addresses on the outgoing interface.
This results in many problems:

If you add a domain, the ip address is wrong, it gets the host ip and not the vip
and you have no chance to change it. You have to manually update the database table entries.

If the server starts the service of dsiprouter always want to update the config files with the wrong ip address. There is no 'simple' way to avoid this.
I had to edit the system files to disable this feature.

**Comment by mackhendricks** [comment]
Hi,

We plan to focus on HA at the end of the year.  So, perhaps we need to look at supporting ucarp.

**Comment by devopsec** [comment]
@ednt the latest "auto" networking mode will use the default route as the address.  
There is also a "static" mode if you need more fine grained control (you can manually set the network configuration).  
See the default settings for more details: https://github.com/dOpensource/dsiprouter/blob/a0da366320401cf5fe8d166d6c093dad1896e315/gui/settings.py#L104
