### ISSUE TITLE
Install Kamailio during Install for Debian 8.9

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#24]
If Kamailio isn't already installed then install it.  We will only support Debian Jessie to start

**Comment by mackhendricks** [comment]
We have added support for Debian Jessie 8.9 into the master trunk.  It still prompts for a MYSQL passwords and during the kamailio database creation process.  But, this will be cleaned up by the 0.40 release.

**Comment by mackhendricks** [comment]
Based on other requests - we don't plan to officially support Debian 8.9

**Comment by devopsec** [comment]
Our supported OS are currently listed as (dsiprouter.sh):
# Supported OS:
# Debian 9 (stretch)
# Debian 8 (jessie)
# Debian 7 (wheezy)
# CentOS 7

currently this is already supported, but should be added to the documentation
