### ISSUE TITLE
Asterisk Realtime DB support is not ready out-of-the-box.

### ISSUE THREAD

**Issue by tiefighter** [dOpensource/dsiprouter#240]
After while, I figured out that dsiprouter doesn't support Asterisk Realtime DB out-of-the-box. So, I started look around to make it works.

Changed SQLCONN_AST to connect to remove Asterisk Realtime db.
Changed asterisk db query from sipuser to sippeers, and sippasswd to secret (my realtime setup on Asterisk 17.x)

Looking on logs, I figured out kamailio wasn't send correct query to remote realtime db.

Variable on this line:
`$var(query) = "select secret from sippeers where name=$fU";`
Resulted a query on remote DB like this:
`"select secret from sippeers where name=$fU"`
So, no secret found where user is "$fU".

I changed sql query from/to this:
```
#sql_xquery("asterisk","$var(query)","ra");
sql_xquery("asterisk","select secret from sippeers where name='$fU'","ra");

```
It might broke some features, but I got it working correctly.
Any plan to make easier Dsip works with Asterisk Realtime DB?

**Comment by mackhendricks** [comment]
Great work.  We will update the SQL string in 0.63.  But, we don't have better support planned for Asterisk Realtime as of yet.  But, if other users or customers vote for this then we will focus on it.

**Comment by tiefighter** [comment]
Thanks
