### ISSUE TITLE
Deleting endpoint does not remove ip in address table

### ISSUE THREAD

**Issue by beres** [dOpensource/dsiprouter#248]
Hi,

Updating endpoint group by deleting an item updateEndpointGroups() does not remove ip from address table, 
is it a desired behavior?

**Comment by mackhendricks** [comment]
Hi,

What version of dSIPRouter?

**Comment by beres** [comment]
0.621 from git master 

Only when auth is in ip mode. Ip was added in address table but never removed

**Comment by beres** [comment]
Hi Mark,

feel free to trash the pull, probably a better solutions is to delete all address matching gwgroup_filter and then re add the new/modified ones.

I don't think that deleting  and recreating all the addresses can cause problems to kamailio, but I'm not sure for the rest of dsip. Finally if you switch from authtype ip or not, addresses will be cleaned, now not.

**Comment by mackhendricks** [comment]
Hey Mark,

I really appreciate the pull request.  Let me review and I'm sure we can make it work one way or another.

**Comment by beres** [comment]
@mackhendricks  sorry Mack :P

**Comment by RichSosa28** [comment]
Validated this issue by:
1. Installing dSIPRouter
2. Create Endpoint Group using IP auth
3. Delete the Endpoint Group
4. Ran the following commands to check if it was removed from the address table:
     mysql kamailio;
     select * from address;

Closing this issue because it is no longer valid.
