### ISSUE TITLE
Feature question

### ISSUE THREAD

**Issue by beres** [dOpensource/dsiprouter#250]
Hey,

Thanks for dsip, I need to add different use case, as SIP Register, i would like user register to local subscriber and than dispatch the call trought customized freeswitch, passing additional sip header. 

Could you be interested to merge something like that? 
Do you have a roadmap for dsip?

**Comment by mackhendricks** [comment]
This feature can be implemented today with support for our professional services team.  Please send them an email to support@dopensource.com

We have an updated roadmap coming out in August

**Comment by beres** [comment]
Thank you, I'll keep in mind in case of need
