### ISSUE TITLE
Correctly handling FreePBX and FUSIONPBX alphanumeric usernames

### ISSUE THREAD

**Issue by legithasmit** [dOpensource/dsiprouter#251]
Through the latest patch, numeric usernames have calls working fine. However, if I create a extension with an alphanumeric username and a numeric alias on fusion, the extension is unable to receive calls. Looking at the SIP trace, the only difference that I can see is that Fusion tries to send the call to username@ip which dSIProuter is not forwarding on correctly. I think a small patch in the Kamilio config should be able to solve this usecase?

**Comment by mackhendricks** [comment]
Please look into this for FreePBX as well

**Comment by RichSosa28** [comment]
Tested with freepbx and it doesn't allow underscores in the username and also looking at the location route in kamailio config (line 1610-1663) and we don't have anything in there that prevents the use of underscores. With regards to it not working on asterisk we didn't set up an asterisk server but you can engage our support if you want this issue resolved.
