### ISSUE TITLE
Error when create user

### ISSUE THREAD

**Issue by amen160** [dOpensource/dsiprouter#254]
1. When I create 2 users from the database, then use to call, it shows error: Authen when call.
- REGISTER is OK
- INVITE it to show error Authen
2. When I use kamctl to create 2 users its show error "use usernames with domain or set default domain in SIP_DOMAIN" .
Please help me check
<img width="621" alt="Screen Shot 2020-07-28 at 11 13 01" src="https://user-images.githubusercontent.com/6201829/88618632-cd501880-d0c3-11ea-80c0-c68140e0682f.png">

**Comment by mackhendricks** [comment]
I never tested it that way. I would create the users thru the Endpoint Group Interface.  This will allow two endpoints to register and send calls out of a carrier.  I'm not sure if you will be able to dial between them.  That's not a use case we focus on.  What are you trying to achieve?

**Comment by amen160** [comment]
thank @mackhendricks , When I Crete user Endpoint Group Interface, and call 2 Endpoint, it errors Auth.
<img width="417" alt="Screen Shot 2020-08-03 at 16 54 06" src="https://user-images.githubusercontent.com/6201829/89170517-f3852500-d5a9-11ea-85a4-ae457718184b.png">

**Comment by mackhendricks** [comment]
This is not a use case we support.  Closing issue
