### ISSUE TITLE
TCP 5060 not Bound during default install

### ISSUE THREAD

**Issue by demonspork** [dOpensource/dsiprouter#255]
Fresh Installation on Debian 9 of 0.621 results in Kamalio not binding to the local ipv4 interface for tcp port 5060. It binds to 127.0.0.1:5060 but that doesn't allow external registration on TCP.

Related note: The installer doesn't have an option to specify alternate/additional binding ports, which would be useful.

**Comment by devopsec** [comment]
Validated, add listen directive for tcp on external interfaces:  
https://github.com/dOpensource/dsiprouter/blob/master/kamailio/kamailio_dsiprouter.cfg#L139
