### ISSUE TITLE
Update VoIP Innovations  Carrier Info

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#256]
The default VI CarrierGroup settings aren't completely functional because they assume all server IP addresses can be used for Termination. Their Signalling IPs are split into separate termination and origination IP addresses with only some overlap. This causes calls to not complete when the call selects an IP not valid for outbound calls.

4 Potential solutions:
IP Prioritization of some kind. I noticed they don't have any weights/priorities as part of the configuration in the GUI. Is that something possible with how it is configured in Kamailio and just needs to be controllable in dsiprouter? or is that a huge project?

-or-

Default to 2 VI groups as the pre-made groups, one that includes the standard Outbound/Term IPs and one that includes all IPs for matching of inbound/Origination calls to be allowed on the inbound DID mapping table.

-or- 

Directional settings in the carrier endpoint IPs so that they can be selected for Inbound/Outbound/Both

-or-

Carrier Group Endpoint Fallback so that it falls back to a different IP in the carrier group if an invalid response like Authorization Required or no response within 100ms or something along those lines

**Comment by demonspork** [comment]
According to their documentation, all IPs could be the source of an Origination (inbound) call, so the end result must allow incoming calls from all IP Addresses they list. The termination (outbound) calling is limited to this list of servers:
Conversational (standard voice)
64.136.174.30
64.136.173.22
209.166.128.200
192.240.151.100
Conversational (Advanced Server) Use for some advanced features
64.136.174.65
64.136.173.23
209.166.128.201
192.240.151.101
Dialer (all automated outbound traffic should reach these IPs)
64.136.174.35
64.136.173.32
209.166.128.200 - OVERLAP
192.240.151.100 - OVERLAP
Dialer (Advanced Server)
64.136.164.215
64.136.173.34
209.166.128.201 - OVERLAP
192.240.151.101 - OVERLAP

So before we have Affinity, the most "compliant" version would be a VI carrier group containing only the 4 Conversational IPs to be used for outbound calls, and then a separate VI carrier group that contains all IP addresses in their documentation, which I think is covered by the existing group. People using Advanced Server or Dialer features should probably just add a separate group for those features?

**Comment by mackhendricks** [comment]
I think we need to update these for 0.641, but we also need to start thinking how are we going to support adding/updating carriers.  Right now it takes a little work to make sure everything maps out correctly.  I propose that we add/update the VoIP Innovations Carrier info and start working on a process that's inline with Linux configuration directories.  So, we should have a directory called carriers.d/.  This directory would have vi.conf, twillio.conf, flowroute.conf, skyetel.conf, etc.  The conf file would contain a list of signaling addresses, inbound ip's, etc.  We would process this directory each time dsiprouter starts up and we can have a rescan button on the Carrier Group UI page so that we can import new ones.  We can also have an import button on the UI that would upload one of these carrier configuration files.

**Comment by mackhendricks** [comment]
I agree with @demonspork that we only need to rename the existing VI CarrierGroup to VoIP Innovations Conversational IP's and add another Carrier Group called VoIP Innovations Inbound IP's, which should just be used by dSIPRouter to allow calls inbound - not for signaling.  Folks that need the advanced features can just add the corresponding carrier groups
