### ISSUE TITLE
No Rules Defined Error Message on Inbound Number mapped to Username/Password Endpoint Group

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#258]
This error is happening when an inbound call tries to route a call to an Endpoint Group thats using Username/Password Registration.

Reproduce doing this:

1) Register a PBX or Endpoint to an Endpoint Group

2)  Re-Register a PBX or Endpoint to an Endpoint Group

3) Attempt to call an inbound number that's mapped to the Endpoint Group

**Comment by devopsec** [comment]
This was partially resolved already by adding a flag for "unregistration" in the REGISTRAR route and updating the endpoint registration part of that same route.  
Needs validation...

**Comment by qmex-mp** [comment]
Hi, if this would help you. if you could get me access to the changes (eg in Github) I can do a Test on our staging System.

**Comment by mackhendricks** [comment]
The outcome in the database looks like this.  Notice the comma on line 13.  This is causing an issue

![image](https://user-images.githubusercontent.com/5568984/92951764-ee2ebc00-f42c-11ea-998c-0853185fbfb2.png)

**Comment by devopsec** [comment]
Patch is commited for v0.63 and backported for v0.621.  
Simply pull down the latest and rebuild your kamailio config (`dsiprouter -h` for more info).  
Or you can simply copy this line to your current kamailio config: https://github.com/dOpensource/dsiprouter/blob/v0.63/kamailio/kamailio_dsiprouter.cfg#L1436
