### ISSUE TITLE
No Record-Route in v0.63

### ISSUE THREAD

**Issue by qmex-mp** [dOpensource/dsiprouter#259]
I found an error in upcomming v0.63:
https://github.com/dOpensource/dsiprouter/blob/v0.63/kamailio/kamailio_dsiprouter.cfg#L998

This is commented out, outgoing calls are not working correctly (no record route header, so BYE goes directly to Contact which cant be reached by Carrier and this is also wrong behaviour). This also disables CDRs as there is never any BYE in acct table, which is necessary for kamailio_cdr stored procedure.

Afer commenting this line in again everything is working, there is a record-route header and cdrs are working.

Only commenting that in again is probably no clean solution, as I have no know how with kamailio whatsoever I didnt make any PR for that.

**Comment by mackhendricks** [comment]
We will update this...there should be an else statement.
