### ISSUE TITLE
New install on Fresh Debian 9.13 fails - worked fine 4 or 5 hours ago but stopped working 

### ISSUE THREAD

**Issue by DForester-FTC** [dOpensource/dsiprouter#260]
Synchronizing state of firewalld.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable firewalld
success
success
success
success
success
success
success
cp: cannot stat '/opt/dsiprouter/kamailio/debian/modules/dsiprouter_536.so': No such file or directory
No dSIPRouter module for Kamailio version 536
kamailio install failed

**Comment by DForester-FTC** [comment]
I just ran the install on CenOS 7 and it installed
[root@centos-7 dsiprouter]# uname -a
Linux centos-7 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by DForester-FTC** [comment]
Recreated a Debian 9 system on Azure to retest the install:
root@Debian9-13:~# uname -a
Linux Debian9-13 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 GNU/Linux
Command used:
root@Debian9-13:~# apt-get update -y && apt-get install -y git && cd /opt && git clone https://github.com/dOpensource/dsiprouter.git && cd dsiprouter && ./dsiprouter.sh install -all
Ign:1 http://debian-archive.trafficmanager.net/debian stretch InRelease
Hit:2 http://debian-archive.trafficmanager.net/debian-security stretch/updates InRelease
Hit:3 http://debian-archive.trafficmanager.net/debian stretch-updates InRelease
Hit:4 http://debian-archive.trafficmanager.net/debian stretch-backports InRelease
Hit:5 http://debian-archive.trafficmanager.net/debian stretch Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  git-man libcurl3-gnutls liberror-perl libldap-2.4-2 libldap-common libnghttp2-14 libperl5.24 librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db libssh2-1 patch perl perl-modules-5.24 rename rsync
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-arch git-cvs git-mediawiki git-svn libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql ed
  diffutils-doc perl-doc libterm-readline-gnu-perl | libterm-readline-perl-perl make
The following NEW packages will be installed:
  git git-man libcurl3-gnutls liberror-perl libldap-2.4-2 libldap-common libnghttp2-14 libperl5.24 librtmp1 libsasl2-2 libsasl2-modules libsasl2-modules-db libssh2-1 patch perl perl-modules-5.24 rename rsync
0 upgraded, 18 newly installed, 0 to remove and 20 not upgraded.
Need to get 13.8 MB of archives.
After this operation, 74.7 MB of additional disk space will be used.
...
Attempting to install Kamailio...
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
--2020-09-11 22:13:05--  http://deb.kamailio.org/kamailiodebkey.gpg
Resolving deb.kamailio.org (deb.kamailio.org)... 52.213.73.177
Connecting to deb.kamailio.org (deb.kamailio.org)|52.213.73.177|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3133 (3.1K) [application/octet-stream]
Saving to: 'STDOUT'

-                                                                100%[========================================================================================================================================================>]   3.06K  --.-KB/s    in 0s

2020-09-11 22:13:06 (209 MB/s) - written to stdout [3133/3133]

OK
Extracting templates from packages: 100%
Preconfiguring packages ...
Selecting previously unselected package mysql-common.
(Reading database ... 36495 files and directories currently installed.)
Preparing to unpack .../00-mysql-common_5.8+1.0.2_all.deb ...
Unpacking mysql-common (5.8+1.0.2) ...
Selecting previously unselected package mariadb-common.
Preparing to unpack .../01-mariadb-common_10.1.45-0+deb9u1_all.deb ...
Unpacking mariadb-common (10.1.45-0+deb9u1) ...
Selecting previously unselected package galera-3.
Preparing to unpack .../02-galera-3_25.3.19-2_amd64.deb ...
Unpacking galera-3 (25.3.19-2) ...
Selecting previously unselected package libdbi-perl.
Preparing to unpack .../03-libdbi-perl_1.636-1+b1_amd64.deb ...
Unpacking libdbi-perl (1.636-1+b1) ...
Selecting previously unselected package lsof.
Preparing to unpack .../04-lsof_4.89+dfsg-0.1_amd64.deb ...
Unpacking lsof (4.89+dfsg-0.1) ...
Selecting previously unselected package libaio1:amd64.
Preparing to unpack .../05-libaio1_0.3.110-3_amd64.deb ...
Unpacking libaio1:amd64 (0.3.110-3) ...
Selecting previously unselected package libreadline5:amd64.
Preparing to unpack .../06-libreadline5_5.2+dfsg-3+b1_amd64.deb ...
Unpacking libreadline5:amd64 (5.2+dfsg-3+b1) ...
Selecting previously unselected package mariadb-client-core-10.1.
Preparing to unpack .../07-mariadb-client-core-10.1_10.1.45-0+deb9u1_amd64.deb ...
Unpacking mariadb-client-core-10.1 (10.1.45-0+deb9u1) ...
Selecting previously unselected package libconfig-inifiles-perl.
Preparing to unpack .../08-libconfig-inifiles-perl_2.94-1_all.deb ...
Unpacking libconfig-inifiles-perl (2.94-1) ...
Selecting previously unselected package libjemalloc1.
Preparing to unpack .../09-libjemalloc1_3.6.0-9.1_amd64.deb ...
Unpacking libjemalloc1 (3.6.0-9.1) ...
Selecting previously unselected package mariadb-client-10.1.
Preparing to unpack .../10-mariadb-client-10.1_10.1.45-0+deb9u1_amd64.deb ...
Unpacking mariadb-client-10.1 (10.1.45-0+deb9u1) ...
Selecting previously unselected package mariadb-server-core-10.1.
Preparing to unpack .../11-mariadb-server-core-10.1_10.1.45-0+deb9u1_amd64.deb ...
Unpacking mariadb-server-core-10.1 (10.1.45-0+deb9u1) ...
Selecting previously unselected package psmisc.
Preparing to unpack .../12-psmisc_22.21-2.1+b2_amd64.deb ...
Unpacking psmisc (22.21-2.1+b2) ...
Selecting previously unselected package socat.
Preparing to unpack .../13-socat_1.7.3.1-2+deb9u1_amd64.deb ...
Unpacking socat (1.7.3.1-2+deb9u1) ...
Setting up mysql-common (5.8+1.0.2) ...
update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Setting up mariadb-common (10.1.45-0+deb9u1) ...
update-alternatives: using /etc/mysql/mariadb.cnf to provide /etc/mysql/my.cnf (my.cnf) in auto mode
Selecting previously unselected package mariadb-server-10.1.
(Reading database ... 36967 files and directories currently installed.)
Preparing to unpack .../00-mariadb-server-10.1_10.1.45-0+deb9u1_amd64.deb ...
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(group) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
sent invalidate(group) request, exiting
sent invalidate(passwd) request, exiting
Unpacking mariadb-server-10.1 (10.1.45-0+deb9u1) ...
Selecting previously unselected package libevent-2.0-5:amd64.
Preparing to unpack .../01-libevent-2.0-5_2.0.21-stable-3_amd64.deb ...
Unpacking libevent-2.0-5:amd64 (2.0.21-stable-3) ...
Selecting previously unselected package default-mysql-server.
Preparing to unpack .../02-default-mysql-server_1.0.2_all.deb ...
Unpacking default-mysql-server (1.0.2) ...
Selecting previously unselected package ebtables.
Preparing to unpack .../03-ebtables_2.0.10.4-3.5+b1_amd64.deb ...
Unpacking ebtables (2.0.10.4-3.5+b1) ...
Selecting previously unselected package libgirepository-1.0-1:amd64.
Preparing to unpack .../04-libgirepository-1.0-1_1.50.0-1+b1_amd64.deb ...
Unpacking libgirepository-1.0-1:amd64 (1.50.0-1+b1) ...
Selecting previously unselected package gir1.2-glib-2.0:amd64.
Preparing to unpack .../05-gir1.2-glib-2.0_1.50.0-1+b1_amd64.deb ...
Unpacking gir1.2-glib-2.0:amd64 (1.50.0-1+b1) ...
Selecting previously unselected package libpolkit-gobject-1-0:amd64.
Preparing to unpack .../06-libpolkit-gobject-1-0_0.105-18+deb9u1_amd64.deb ...
Unpacking libpolkit-gobject-1-0:amd64 (0.105-18+deb9u1) ...
Selecting previously unselected package libpolkit-agent-1-0:amd64.
Preparing to unpack .../07-libpolkit-agent-1-0_0.105-18+deb9u1_amd64.deb ...
Unpacking libpolkit-agent-1-0:amd64 (0.105-18+deb9u1) ...
Selecting previously unselected package libpolkit-backend-1-0:amd64.
Preparing to unpack .../08-libpolkit-backend-1-0_0.105-18+deb9u1_amd64.deb ...
Unpacking libpolkit-backend-1-0:amd64 (0.105-18+deb9u1) ...
Selecting previously unselected package policykit-1.
Preparing to unpack .../09-policykit-1_0.105-18+deb9u1_amd64.deb ...
Unit polkit.service does not exist, proceeding anyway.
Created symlink /run/systemd/system/polkit.service → /dev/null.
Unpacking policykit-1 (0.105-18+deb9u1) ...
Selecting previously unselected package libdbus-glib-1-2:amd64.
Preparing to unpack .../10-libdbus-glib-1-2_0.108-2_amd64.deb ...
Unpacking libdbus-glib-1-2:amd64 (0.108-2) ...
Selecting previously unselected package python3-dbus.
Preparing to unpack .../11-python3-dbus_1.2.4-1+b1_amd64.deb ...
Unpacking python3-dbus (1.2.4-1+b1) ...
Selecting previously unselected package python3-gi.
Preparing to unpack .../12-python3-gi_3.22.0-2_amd64.deb ...
Unpacking python3-gi (3.22.0-2) ...
Selecting previously unselected package python3-decorator.
Preparing to unpack .../13-python3-decorator_4.0.11-1_all.deb ...
Unpacking python3-decorator (4.0.11-1) ...
Selecting previously unselected package python3-six.
Preparing to unpack .../14-python3-six_1.10.0-3_all.deb ...
Unpacking python3-six (1.10.0-3) ...
Selecting previously unselected package python3-selinux.
Preparing to unpack .../15-python3-selinux_2.6-3+b3_amd64.deb ...
Unpacking python3-selinux (2.6-3+b3) ...
Selecting previously unselected package python3-slip.
Preparing to unpack .../16-python3-slip_0.6.1-3_all.deb ...
Unpacking python3-slip (0.6.1-3) ...
Selecting previously unselected package python3-slip-dbus.
Preparing to unpack .../17-python3-slip-dbus_0.6.1-3_all.deb ...
Unpacking python3-slip-dbus (0.6.1-3) ...
Selecting previously unselected package firewalld.
Preparing to unpack .../18-firewalld_0.4.4.2-1_all.deb ...
Unpacking firewalld (0.4.4.2-1) ...
Selecting previously unselected package kamailio.
Preparing to unpack .../19-kamailio_5.3.6+bpo9_amd64.deb ...
Unpacking kamailio (5.3.6+bpo9) ...
Selecting previously unselected package libev4.
Preparing to unpack .../20-libev4_1%3a4.22-1+b1_amd64.deb ...
Unpacking libev4 (1:4.22-1+b1) ...
Selecting previously unselected package libjansson4:amd64.
Preparing to unpack .../21-libjansson4_2.9-1_amd64.deb ...
Unpacking libjansson4:amd64 (2.9-1) ...
Selecting previously unselected package kamailio-extra-modules:amd64.
Preparing to unpack .../22-kamailio-extra-modules_5.3.6+bpo9_amd64.deb ...
Unpacking kamailio-extra-modules:amd64 (5.3.6+bpo9) ...
Selecting previously unselected package libmariadbclient18:amd64.
Preparing to unpack .../23-libmariadbclient18_10.1.45-0+deb9u1_amd64.deb ...
Unpacking libmariadbclient18:amd64 (10.1.45-0+deb9u1) ...
Selecting previously unselected package kamailio-mysql-modules:amd64.
Preparing to unpack .../24-kamailio-mysql-modules_5.3.6+bpo9_amd64.deb ...
Unpacking kamailio-mysql-modules:amd64 (5.3.6+bpo9) ...
Selecting previously unselected package kamailio-tls-modules:amd64.
Preparing to unpack .../25-kamailio-tls-modules_5.3.6+bpo9_amd64.deb ...
Unpacking kamailio-tls-modules:amd64 (5.3.6+bpo9) ...
Selecting previously unselected package kamailio-websocket-modules:amd64.
Preparing to unpack .../26-kamailio-websocket-modules_5.3.6+bpo9_amd64.deb ...
Unpacking kamailio-websocket-modules:amd64 (5.3.6+bpo9) ...
Selecting previously unselected package libhtml-tagset-perl.
Preparing to unpack .../27-libhtml-tagset-perl_3.20-3_all.deb ...
Unpacking libhtml-tagset-perl (3.20-3) ...
Selecting previously unselected package liburi-perl.
Preparing to unpack .../28-liburi-perl_1.71-1_all.deb ...
Unpacking liburi-perl (1.71-1) ...
Selecting previously unselected package libhtml-parser-perl.
Preparing to unpack .../29-libhtml-parser-perl_3.72-3_amd64.deb ...
Unpacking libhtml-parser-perl (3.72-3) ...
Selecting previously unselected package libcgi-pm-perl.
Preparing to unpack .../30-libcgi-pm-perl_4.35-1_all.deb ...
Unpacking libcgi-pm-perl (4.35-1) ...
Selecting previously unselected package libfcgi-perl.
Preparing to unpack .../31-libfcgi-perl_0.78-2_amd64.deb ...
Unpacking libfcgi-perl (0.78-2) ...
Selecting previously unselected package libcgi-fast-perl.
Preparing to unpack .../32-libcgi-fast-perl_1%3a2.12-1_all.deb ...
Unpacking libcgi-fast-perl (1:2.12-1) ...
Selecting previously unselected package libdbd-mysql-perl.
Preparing to unpack .../33-libdbd-mysql-perl_4.041-2_amd64.deb ...
Unpacking libdbd-mysql-perl (4.041-2) ...
Selecting previously unselected package libencode-locale-perl.
Preparing to unpack .../34-libencode-locale-perl_1.05-1_all.deb ...
Unpacking libencode-locale-perl (1.05-1) ...
Selecting previously unselected package libhtml-template-perl.
Preparing to unpack .../35-libhtml-template-perl_2.95-2_all.deb ...
Unpacking libhtml-template-perl (2.95-2) ...
Selecting previously unselected package libhttp-date-perl.
Preparing to unpack .../36-libhttp-date-perl_6.02-1_all.deb ...
Unpacking libhttp-date-perl (6.02-1) ...
Selecting previously unselected package libio-html-perl.
Preparing to unpack .../37-libio-html-perl_1.001-1_all.deb ...
Unpacking libio-html-perl (1.001-1) ...
Selecting previously unselected package liblwp-mediatypes-perl.
Preparing to unpack .../38-liblwp-mediatypes-perl_6.02-1_all.deb ...
Unpacking liblwp-mediatypes-perl (6.02-1) ...
Selecting previously unselected package libhttp-message-perl.
Preparing to unpack .../39-libhttp-message-perl_6.11-1_all.deb ...
Unpacking libhttp-message-perl (6.11-1) ...
Selecting previously unselected package libterm-readkey-perl.
Preparing to unpack .../40-libterm-readkey-perl_2.37-1_amd64.deb ...
Unpacking libterm-readkey-perl (2.37-1) ...
Selecting previously unselected package mysql-server.
Preparing to unpack .../41-mysql-server_5.5.9999+default_amd64.deb ...
Unpacking mysql-server (5.5.9999+default) ...
Selecting previously unselected package python3-cffi-backend.
Preparing to unpack .../42-python3-cffi-backend_1.9.1-2_amd64.deb ...
Unpacking python3-cffi-backend (1.9.1-2) ...
Selecting previously unselected package python3-idna.
Preparing to unpack .../43-python3-idna_2.2-1_all.deb ...
Unpacking python3-idna (2.2-1) ...
Selecting previously unselected package python3-pyasn1.
Preparing to unpack .../44-python3-pyasn1_0.1.9-2_all.deb ...
Unpacking python3-pyasn1 (0.1.9-2) ...
Selecting previously unselected package python3-setuptools.
Preparing to unpack .../45-python3-setuptools_33.1.1-1_all.deb ...
Unpacking python3-setuptools (33.1.1-1) ...
Selecting previously unselected package python3-cryptography.
Preparing to unpack .../46-python3-cryptography_1.7.1-3+deb9u2_amd64.deb ...
Unpacking python3-cryptography (1.7.1-3+deb9u2) ...
Selecting previously unselected package python3-openssl.
Preparing to unpack .../47-python3-openssl_16.2.0-1_all.deb ...
Unpacking python3-openssl (16.2.0-1) ...
Selecting previously unselected package python3-josepy.
Preparing to unpack .../48-python3-josepy_1.1.0-2~deb9u1_all.deb ...
Unpacking python3-josepy (1.1.0-2~deb9u1) ...
Selecting previously unselected package python3-pbr.
Preparing to unpack .../49-python3-pbr_1.10.0-1_all.deb ...
Unpacking python3-pbr (1.10.0-1) ...
Selecting previously unselected package python3-mock.
Preparing to unpack .../50-python3-mock_2.0.0-3_all.deb ...
Unpacking python3-mock (2.0.0-3) ...
Selecting previously unselected package python3-urllib3.
Preparing to unpack .../51-python3-urllib3_1.19.1-1_all.deb ...
Unpacking python3-urllib3 (1.19.1-1) ...
Selecting previously unselected package python3-chardet.
Preparing to unpack .../52-python3-chardet_2.3.0-2_all.deb ...
Unpacking python3-chardet (2.3.0-2) ...
Selecting previously unselected package python3-requests.
Preparing to unpack .../53-python3-requests_2.12.4-1_all.deb ...
Unpacking python3-requests (2.12.4-1) ...
Selecting previously unselected package python3-requests-toolbelt.
Preparing to unpack .../54-python3-requests-toolbelt_0.7.0-1_all.deb ...
Unpacking python3-requests-toolbelt (0.7.0-1) ...
Selecting previously unselected package python3-tz.
Preparing to unpack .../55-python3-tz_2016.7-0.3_all.deb ...
Unpacking python3-tz (2016.7-0.3) ...
Selecting previously unselected package python3-rfc3339.
Preparing to unpack .../56-python3-rfc3339_1.0-4_all.deb ...
Unpacking python3-rfc3339 (1.0-4) ...
Selecting previously unselected package python3-acme.
Preparing to unpack .../57-python3-acme_0.28.0-1~deb9u2_all.deb ...
Unpacking python3-acme (0.28.0-1~deb9u2) ...
Selecting previously unselected package python3-configargparse.
Preparing to unpack .../58-python3-configargparse_0.11.0-1_all.deb ...
Unpacking python3-configargparse (0.11.0-1) ...
Selecting previously unselected package python3-configobj.
Preparing to unpack .../59-python3-configobj_5.0.6-2_all.deb ...
Unpacking python3-configobj (5.0.6-2) ...
Selecting previously unselected package python3-parsedatetime.
Preparing to unpack .../60-python3-parsedatetime_2.1-3+deb9u1_all.deb ...
Unpacking python3-parsedatetime (2.1-3+deb9u1) ...
Selecting previously unselected package python3-zope.hookable.
Preparing to unpack .../61-python3-zope.hookable_4.0.4-4+b2_amd64.deb ...
Unpacking python3-zope.hookable (4.0.4-4+b2) ...
Selecting previously unselected package python3-zope.interface.
Preparing to unpack .../62-python3-zope.interface_4.3.2-1_amd64.deb ...
Unpacking python3-zope.interface (4.3.2-1) ...
Selecting previously unselected package python3-zope.event.
Preparing to unpack .../63-python3-zope.event_4.2.0-1_all.deb ...
Unpacking python3-zope.event (4.2.0-1) ...
Selecting previously unselected package python3-zope.component.
Preparing to unpack .../64-python3-zope.component_4.3.0-1_all.deb ...
Unpacking python3-zope.component (4.3.0-1) ...
Selecting previously unselected package python3-certbot.
Preparing to unpack .../65-python3-certbot_0.28.0-1~deb9u2_all.deb ...
Unpacking python3-certbot (0.28.0-1~deb9u2) ...
Selecting previously unselected package certbot.
Preparing to unpack .../66-certbot_0.28.0-1~deb9u2_all.deb ...
Unpacking certbot (0.28.0-1~deb9u2) ...
Selecting previously unselected package libipset3:amd64.
Preparing to unpack .../67-libipset3_6.30-2_amd64.deb ...
Unpacking libipset3:amd64 (6.30-2) ...
Selecting previously unselected package ipset.
Preparing to unpack .../68-ipset_6.30-2_amd64.deb ...
Unpacking ipset (6.30-2) ...
Setting up libhtml-tagset-perl (3.20-3) ...
Setting up libev4 (1:4.22-1+b1) ...
Setting up kamailio (5.3.6+bpo9) ...
Created symlink /etc/systemd/system/multi-user.target.wants/kamailio.service → /lib/systemd/system/kamailio.service.
Setting up libhttp-date-perl (6.02-1) ...
Setting up libconfig-inifiles-perl (2.94-1) ...
Setting up psmisc (22.21-2.1+b2) ...
Setting up python3-selinux (2.6-3+b3) ...
Setting up python3-cffi-backend (1.9.1-2) ...
Setting up libencode-locale-perl (1.05-1) ...
Setting up libjemalloc1 (3.6.0-9.1) ...
Setting up libdbus-glib-1-2:amd64 (0.108-2) ...
Setting up socat (1.7.3.1-2+deb9u1) ...
Setting up lsof (4.89+dfsg-0.1) ...
Setting up python3-zope.event (4.2.0-1) ...
Setting up libio-html-perl (1.001-1) ...
Setting up python3-idna (2.2-1) ...
Setting up libjansson4:amd64 (2.9-1) ...
Setting up python3-six (1.10.0-3) ...
Setting up libmariadbclient18:amd64 (10.1.45-0+deb9u1) ...
Setting up python3-zope.interface (4.3.2-1) ...
Setting up libipset3:amd64 (6.30-2) ...
Setting up python3-slip (0.6.1-3) ...
Setting up libgirepository-1.0-1:amd64 (1.50.0-1+b1) ...
Setting up kamailio-websocket-modules:amd64 (5.3.6+bpo9) ...
Setting up libterm-readkey-perl (2.37-1) ...
Setting up python3-configargparse (0.11.0-1) ...
Setting up python3-zope.hookable (4.0.4-4+b2) ...
Setting up python3-pyasn1 (0.1.9-2) ...
Setting up gir1.2-glib-2.0:amd64 (1.50.0-1+b1) ...
Setting up liblwp-mediatypes-perl (6.02-1) ...
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Setting up libaio1:amd64 (0.3.110-3) ...
Setting up galera-3 (25.3.19-2) ...
Setting up python3-chardet (2.3.0-2) ...
Setting up liburi-perl (1.71-1) ...
Setting up ipset (6.30-2) ...
Processing triggers for systemd (232-25+deb9u12) ...
Setting up libhtml-parser-perl (3.72-3) ...
Setting up ebtables (2.0.10.4-3.5+b1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/ebtables.service → /lib/systemd/system/ebtables.service.
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Setting up libcgi-pm-perl (4.35-1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libhttp-message-perl (6.11-1) ...
Setting up python3-urllib3 (1.19.1-1) ...
Processing triggers for dbus (1.10.32-0+deb9u1) ...
Setting up python3-configobj (5.0.6-2) ...
Setting up libreadline5:amd64 (5.2+dfsg-3+b1) ...
Setting up python3-setuptools (33.1.1-1) ...
Setting up libevent-2.0-5:amd64 (2.0.21-stable-3) ...
Setting up python3-decorator (4.0.11-1) ...
Setting up libfcgi-perl (0.78-2) ...
Setting up python3-tz (2016.7-0.3) ...
Setting up libdbi-perl (1.636-1+b1) ...
Setting up libpolkit-gobject-1-0:amd64 (0.105-18+deb9u1) ...
Setting up python3-parsedatetime (2.1-3+deb9u1) ...
Setting up python3-cryptography (1.7.1-3+deb9u2) ...
Setting up kamailio-extra-modules:amd64 (5.3.6+bpo9) ...
Setting up python3-pbr (1.10.0-1) ...
update-alternatives: using /usr/bin/python3-pbr to provide /usr/bin/pbr (pbr) in auto mode
Setting up kamailio-tls-modules:amd64 (5.3.6+bpo9) ...
Setting up python3-dbus (1.2.4-1+b1) ...
Setting up python3-rfc3339 (1.0-4) ...
Setting up mariadb-server-core-10.1 (10.1.45-0+deb9u1) ...
Setting up libhtml-template-perl (2.95-2) ...
Setting up python3-mock (2.0.0-3) ...
Setting up libpolkit-agent-1-0:amd64 (0.105-18+deb9u1) ...
Setting up mariadb-client-core-10.1 (10.1.45-0+deb9u1) ...
Setting up python3-zope.component (4.3.0-1) ...
Setting up python3-gi (3.22.0-2) ...
Setting up libcgi-fast-perl (1:2.12-1) ...
Setting up libpolkit-backend-1-0:amd64 (0.105-18+deb9u1) ...
Setting up python3-slip-dbus (0.6.1-3) ...
Setting up python3-requests (2.12.4-1) ...
Setting up python3-openssl (16.2.0-1) ...
Setting up python3-josepy (1.1.0-2~deb9u1) ...
Setting up libdbd-mysql-perl (4.041-2) ...
Setting up python3-requests-toolbelt (0.7.0-1) ...
Setting up mariadb-client-10.1 (10.1.45-0+deb9u1) ...
Setting up policykit-1 (0.105-18+deb9u1) ...
Removed /run/systemd/system/polkit.service.
polkit.service is a disabled or a static unit not running, not starting it.
Setting up kamailio-mysql-modules:amd64 (5.3.6+bpo9) ...
Setting up firewalld (0.4.4.2-1) ...
Created symlink /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service → /lib/systemd/system/firewalld.service.
Created symlink /etc/systemd/system/multi-user.target.wants/firewalld.service → /lib/systemd/system/firewalld.service.
Setting up mariadb-server-10.1 (10.1.45-0+deb9u1) ...
Created symlink /etc/systemd/system/mysql.service → /lib/systemd/system/mariadb.service.
Created symlink /etc/systemd/system/mysqld.service → /lib/systemd/system/mariadb.service.
Created symlink /etc/systemd/system/multi-user.target.wants/mariadb.service → /lib/systemd/system/mariadb.service.
Setting up python3-acme (0.28.0-1~deb9u2) ...
Setting up python3-certbot (0.28.0-1~deb9u2) ...
Setting up default-mysql-server (1.0.2) ...
Setting up mysql-server (5.5.9999+default) ...
Setting up certbot (0.28.0-1~deb9u2) ...
Created symlink /etc/systemd/system/timers.target.wants/certbot.timer → /lib/systemd/system/certbot.timer.
Processing triggers for libc-bin (2.24-11+deb9u4) ...
Processing triggers for systemd (232-25+deb9u12) ...
Processing triggers for dbus (1.10.32-0+deb9u1) ...
Re-Configuring mysql systemd service for local or remote connection
Finished re-configuring mysql systemd service
Synchronizing state of mysql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable mysql
Failed to enable unit: Refusing to operate on linked unit file mysql.service
Synchronizing state of kamailio.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable kamailio
-e \E[37;33mINFO: creating database kamailio ...
-e \E[37;33mINFO: granting privileges to database kamailio ...
-e \E[37;33mINFO: creating standard tables into kamailio ...
-e \E[37;33mINFO: Core Kamailio tables succesfully created.
-e \E[37;33mINFO: creating presence tables into kamailio ...
-e \E[37;33mINFO: Presence tables succesfully created.
-e \E[37;33mINFO: creating extra tables into kamailio ...
-e \E[37;33mINFO: Extra tables succesfully created.
-e \E[37;33mINFO: creating uid tables into kamailio ...
-e \E[37;33mINFO: UID tables succesfully created.
Synchronizing state of firewalld.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable firewalld
success
success
success
success
success
success
success
cp: cannot stat '/opt/dsiprouter/kamailio/debian/modules/dsiprouter_536.so': No such file or directory
No dSIPRouter module for Kamailio version 536
kamailio install failed
root@Debian9-13:/opt/dsiprouter# ls -l kamailio/debian/modules
total 204
-rwxr-xr-x 1 root root 65656 Sep 11 22:11 dsiprouter_533.so
-rwxr-xr-x 1 root root 65656 Sep 11 22:11 dsiprouter_534.so
-rwxr-xr-x 1 root root 65784 Sep 11 22:11 dsiprouter_535.so
root@Debian9-13:/opt/dsiprouter#

**Comment by mackhendricks** [comment]
Was resolved.   We now have a dsiprouter_536.so library on the master branch

**Comment by DForester-FTC** [comment]
Worked great! Thanks for the quick response and resolution.
-----------------------------------
Kamailio Installation is complete!
-----------------------------------
