### ISSUE TITLE
Cant seem to get outbound working

### ISSUE THREAD

**Issue by shanehughes1990** [dOpensource/dsiprouter#263]
We are attempting to implement dsiprouter as part of our SIP pipeline, we have a PBX server pointed too dsiprouter, the endpoint is setup to point to the IP of the PBX server, and  global outbound route to point all traffic to the outbound DID from our carrier. What logs/info would you need to help diagnose this issue, PS as a side note inbound calling works as intended RTP included.

**Comment by mackhendricks** [comment]
Can you ask your question in the dSIPRouter groups.  People can help you there: https://groups.google.com/g/dsiprouter

However, if this is critical please open a paid support ticket.

**Comment by shanehughes1990** [comment]
Done here is a link to any passerby's
https://groups.google.com/g/dsiprouter/c/y3kV822aX4w
