### ISSUE TITLE
Errors from fresh install on debian 9

### ISSUE THREAD

**Issue by ISQman** [dOpensource/dsiprouter#266]
1) fresh install with option -all (or without) kamailio dont start, part of journalctl -xe:
`Sep 21 11:19:53 dsip-01 /usr/sbin/kamailio[6342]: ERROR: <core> [core/route.c:1009]: fix_actions(): bad force_send_socket argument: y.xx.x.yy:5061 (kamailio doesn't listen on it)
Sep 21 11:19:53 dsip-01 /usr/sbin/kamailio[6342]: ERROR: <core> [core/route.c:1166]: fix_actions(): fixing failed (code=-478) at cfg:/etc/kamailio/kamailio.cfg:881
Sep 21 11:19:53 dsip-01 /usr/sbin/kamailio[6342]: ERROR: <core> [core/route.c:1166]: fix_actions(): fixing failed (code=-478) at cfg:/etc/kamailio/kamailio.cfg:884
Sep 21 11:19:53 dsip-01 /usr/sbin/kamailio[6342]: ERROR: <core> [core/route.c:1166]: fix_actions(): fixing failed (code=-478) at cfg:/etc/kamailio/kamailio.cfg:885
Sep 21 11:19:53 dsip-01 /usr/sbin/kamailio[6342]: ERROR: <core> [core/route.c:1166]: fix_actions(): fixing failed (code=-478) at cfg:/etc/kamailio/kamailio.cfg:915
Sep 21 11:19:53 dsip-01 /usr/sbin/kamailio[6342]: ERROR: <core> [core/route.c:1166]: fix_actions(): fixing failed (code=-478) at cfg:/etc/kamailio/kamailio.cfg:1015`
2) no information about required package build-essential (make command not found)
3) if i install "./dsiprouter.sh install -kam -dsip" i found automatically configured !EXTERNAL_FQDN!, that point for me wrong, but its also ok, i can change it/or fix

**Comment by RichSosa28** [comment]
Hi,
Sorry to hear about the problem that you are facing. What version of debian are you using?

**Comment by RichSosa28** [comment]
Hi, sorry to hear about the problem you've encountered.  Which version of debian 9 are using?

**Comment by DForester-FTC** [comment]
Did you specify port 5061 in place of port 5060? 
y.xx.x.yy:5061
I did a fresh install on a lab vm this weekend using Debian 9.13 and left the default port number and it worked. 
{Fresh Install}
Login as user specified in the installation.
su -                             # enter root password
apt-get update -y
apt-get install -y git
apt-get upgrade -y
cd /opt
git clone https://github.com/dOpensource/dsiprouter.git
cd dsiprouter
./dsiprouter.sh install -all

**Comment by RichSosa28** [comment]
Hello, were you able to get it to work using the instructions stated above?

**Comment by mackhendricks** [comment]
No response...closing issue.
