### ISSUE TITLE
After DID Import - Kamailio will no reload

### ISSUE THREAD

**Issue by DForester-FTC** [dOpensource/dsiprouter#267]
Debian 9.13 & dSIPRouter 0.621

Imported DIDs from CSV File (160 entries) and then Reload Kamailio it showed the following error: Failed! Kamailio was NOT reloaded: Reload failed.
When you click Reload Kamailio the following is logged in /var/log/kamailio.log:
Sep 21 12:45:55 sipr-0-ce /usr/sbin/kamailio[10397]: INFO: db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Access denied for user 'kamailio'@'localhost' (using password: YES)
Sep 21 12:45:55 sipr-0-ce /usr/sbin/kamailio[10397]: INFO: db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Access denied for user 'kamailio'@'localhost' (using password: YES)
Sep 21 12:45:55 sipr-0-ce /usr/sbin/kamailio[10397]: INFO: db_mysql [km_dbase.c:84]: db_mysql_submit_query(): driver error on ping: Access denied for user 'kamailio'@'localhost' (using password: YES)
Sep 21 12:45:55 sipr-0-ce /usr/sbin/kamailio[10397]: ERROR: db_mysql [km_dbase.c:122]: db_mysql_submit_query(): driver error on query: Access denied for user 'kamailio'@'localhost' (using password: YES) (1045)
Sep 21 12:45:55 sipr-0-ce /usr/sbin/kamailio[10397]: ERROR: <core> [db_query.c:141]: db_do_query_internal(): error while submitting query
Sep 21 12:45:55 sipr-0-ce /usr/sbin/kamailio[10397]: ERROR: permissions [address.c:108]: reload_address_table(): failed to query database
Sep 21 12:45:55 sipr-0-ce /usr/sbin/kamailio[10397]: ERROR: <core> [core/parser/parse_fline.c:271]: parse_first_line(): parse_first_line: bad message (offset: 19)
Sep 21 12:45:55 sipr-0-ce /usr/sbin/kamailio[10397]: ERROR: <core> [core/parser/msg_parser.c:681]: parse_msg(): ERROR: parse_msg: message=<HTTP/1.1 500 Reload failed.
Sia: SIP/2.0/TCP 127.0.0.1:50066
Content-Type: application/json
Content-Length: 92

{
        "jsonrpc":      "2.0",
        "error":        {
                "code": 500,
                "message":      "Reload failed."
        },
        "id":   1
}>
The following was shown in the /var/log/dsiprouter.log:
[2020-09-21 12:49:18] [11961->139855097849600] [DEBUG]: Starting new HTTP connection (1): 127.0.0.1:5060
[2020-09-21 12:49:18] [11961->139855097849600] [DEBUG]: http://127.0.0.1:5060 "GET /api/kamailio HTTP/1.1" 500 92
[2020-09-21 12:49:18] [11961->139855097849600] [ERROR]: ((( EXCEPTION )))
[CLASS]: <class 'werkzeug.exceptions.HTTPException'>
[VALUE]: 500 Internal Server Error: Reload failed.
[CODE]: 500
[RESPONSE]: None
[DESCRIPTION]: Reload failed.
((( BACKTRACE )))
[FILE]: /opt/dsiprouter/gui/modules/api/api_routes.py
[LINE NUM]: 178
[FUNCTION]: reloadKamailio()
[SOURCE]: raise ex
[2020-09-21 12:49:18] [11961->139855097849600] [INFO]: 99.231.248.254 - - [21/Sep/2020 12:49:18] "GET /api/v1/kamailio/reload HTTP/1.1" 500 -
[2020-09-21 12:49:18] [11961->139855097849600] [INFO]: 99.231.248.254 - - [21/Sep/2020 12:49:18] "GET /api/v1/kamailio/reload HTTP/1.1" 500 -

I then logged out of dSIPRouter and the following was shown on the login screen: X number of file were imported. The rest of the login box appeared below that. 

What else would you like to see that would aid in troubleshooting this issue?

Regards,

Dean
![Screenshot 2020-09-21 125656](https://user-images.githubusercontent.com/58430470/93797289-09a67d80-fc0a-11ea-959c-f76eb8260db1.jpg)

**Comment by DForester-FTC** [comment]
It looks like somehow the kamailio user no longer has access to the database:
root@sipr-0-ce:/opt/dsiprouter/gui/util# systemctl status kamailio
● kamailio.service - Kamailio (OpenSER) - the Open Source SIP Server
   Loaded: loaded (/lib/systemd/system/kamailio.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-09-17 09:35:51 EDT; 4 days ago
 Main PID: 10373 (kamailio)
    Tasks: 17 (limit: 4915)
   Memory: 65.5M
      CPU: 4min 37.086s
   CGroup: /system.slice/kamailio.service
           ├─10373 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10374 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10375 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10376 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10377 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10378 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10381 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10382 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10383 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10384 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10386 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10387 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10389 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10393 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10396 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           ├─10397 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16
           └─10398 /usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 128 -M 16

Sep 21 12:45:55 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[10397]: ERROR: db_mysql [km_dbase.c:122]: db_mysql_submit_query(): driver error on query: Access denied for user 'kamailio'@'localhost
Sep 21 12:45:55 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[10397]: ERROR: <core> [db_query.c:141]: db_do_query_internal(): error while submitting query
Sep 21 12:45:55 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[10397]: ERROR: permissions [address.c:108]: reload_address_table(): failed to query database
Sep 21 12:45:55 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[10397]: ERROR: <core> [core/parser/parse_fline.c:271]: parse_first_line(): parse_first_line: bad message (offset: 19)
Sep 21 12:45:55 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[10397]: [387B blob data]
Sep 21 12:49:18 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[10397]: ERROR: db_mysql [km_dbase.c:122]: db_mysql_submit_query(): driver error on query: Access denied for user 'kamailio'@'localhost
Sep 21 12:49:18 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[10397]: ERROR: <core> [db_query.c:141]: db_do_query_internal(): error while submitting query
Sep 21 12:49:18 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[10397]: ERROR: permissions [address.c:108]: reload_address_table(): failed to query database
Sep 21 12:49:18 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[10397]: ERROR: <core> [core/parser/parse_fline.c:271]: parse_first_line(): parse_first_line: bad message (offset: 19)
Sep 21 12:49:18 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[10397]: [387B blob data]

**Comment by mackhendricks** [comment]
I think this is a bug...with OpenSSL.  This seems to only happen occasionally since we have enabled SSL by default.  Restarting Kamailio seems to solve the problem

systemctl restart kamailio

**Comment by DForester-FTC** [comment]
root@sipr-0-ce:/opt/dsiprouter/kamailio# systemctl restart kamailio
Job for kamailio.service failed because the control process exited with error code.
See "systemctl status kamailio.service" and "journalctl -xe" for details.
root@sipr-0-ce:/opt/dsiprouter/kamailio# systemctl status kamailio
● kamailio.service - Kamailio (OpenSER) - the Open Source SIP Server
   Loaded: loaded (/lib/systemd/system/kamailio.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-09-21 14:17:37 EDT; 6s ago
  Process: 1678 ExecStart=/usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f $CFGFILE -m $SHM_MEMORY -M $PKG_MEMORY (code=exited, status=255)
  Process: 1666 ExecStartPre=/opt/dsiprouter/dsiprouter.sh updatednsconfig (code=exited, status=1/FAILURE)
 Main PID: 10373 (code=exited, status=0/SUCCESS)
      CPU: 189ms

Sep 21 14:17:36 sipr-0-ce.myunityconnect.cloud systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
Sep 21 14:17:36 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Unit entered failed state.
Sep 21 14:17:36 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Failed with result 'exit-code'.
Sep 21 14:17:37 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Service hold-off time over, scheduling restart.
Sep 21 14:17:37 sipr-0-ce.myunityconnect.cloud systemd[1]: Stopped Kamailio (OpenSER) - the Open Source SIP Server.
Sep 21 14:17:37 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Start request repeated too quickly.
Sep 21 14:17:37 sipr-0-ce.myunityconnect.cloud systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
Sep 21 14:17:37 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Unit entered failed state.
Sep 21 14:17:37 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Failed with result 'exit-code'.
root@sipr-0-ce:/opt/dsiprouter/kamailio# systemctl stop kamailio
root@sipr-0-ce:/opt/dsiprouter/kamailio# systemctl start kamailio
Job for kamailio.service failed because the control process exited with error code.
See "systemctl status kamailio.service" and "journalctl -xe" for details.
root@sipr-0-ce:/opt/dsiprouter/kamailio# systemctl status kamailio
● kamailio.service - Kamailio (OpenSER) - the Open Source SIP Server
   Loaded: loaded (/lib/systemd/system/kamailio.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-09-21 14:19:09 EDT; 18s ago
  Process: 1856 ExecStart=/usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f $CFGFILE -m $SHM_MEMORY -M $PKG_MEMORY (code=exited, status=255)
  Process: 1846 ExecStartPre=/opt/dsiprouter/dsiprouter.sh updatednsconfig (code=exited, status=1/FAILURE)
 Main PID: 10373 (code=exited, status=0/SUCCESS)
      CPU: 192ms

Sep 21 14:19:09 sipr-0-ce.myunityconnect.cloud systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
Sep 21 14:19:09 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Unit entered failed state.
Sep 21 14:19:09 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Failed with result 'exit-code'.
Sep 21 14:19:09 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Service hold-off time over, scheduling restart.
Sep 21 14:19:09 sipr-0-ce.myunityconnect.cloud systemd[1]: Stopped Kamailio (OpenSER) - the Open Source SIP Server.
Sep 21 14:19:09 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Start request repeated too quickly.
Sep 21 14:19:09 sipr-0-ce.myunityconnect.cloud systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
Sep 21 14:19:09 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Unit entered failed state.
Sep 21 14:19:09 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Failed with result 'exit-code'.

Unfortunately that didn't seem to work. Kamailio is down and won't restart
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud kamailio[2240]:              udp: 10.11.0.243:5060 advertise 52.229.94.43:5060
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud kamailio[2240]:              udp: 127.0.0.1:5060
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud kamailio[2240]:              tcp: 127.0.0.1:5060
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud kamailio[2240]:              tls: 10.11.0.243:4443 advertise 52.229.94.43:4443
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud kamailio[2240]:              tls: 10.11.0.243:5061 advertise 52.229.94.43:5061
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud kamailio[2240]: Aliases:
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud kamailio[2240]:              tls: local.cluster:5061
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud kamailio[2240]:              tls: local.cluster:4443
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud kamailio[2240]:              tcp: localhost:5060
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud kamailio[2240]:              udp: localhost:5060
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud kamailio[2240]:              udp: local.cluster:5060
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: INFO: rr [../outbound/api.h:52]: ob_load_api(): unable to import bind_ob - maybe module is not loaded
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: INFO: rr [rr_mod.c:177]: mod_init(): outbound module not available
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: INFO: path [../outbound/api.h:52]: ob_load_api(): unable to import bind_ob - maybe module is not loaded
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: INFO: path [path_mod.c:151]: mod_init(): outbound module not available
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: WARNING: usrloc [usrloc_mod.c:378]: mod_init(): handle_lost_tcp option makes nothing in DB_ONLY mode
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: INFO: http_async_client [http_async_client_mod.c:222]: mod_init(): Initializing Http Async module
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: ERROR: db_mysql [km_my_con.c:163]: db_mysql_new_connection(): driver error: Access denied for user 'kamailio'@'localhost' (usin
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: ERROR: <core> [db.c:319]: db_do_init2(): could not add connection to the pool
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: ERROR: htable [ht_db.c:92]: ht_db_open_con(): failed to connect to the database
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: ERROR: <core> [core/sr_module.c:849]: init_mod(): Error while initializing module htable (/usr/lib/x86_64-linux-gnu/kamailio/mo
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: ERROR: db_mysql [km_my_con.c:163]: db_mysql_new_connection(): driver error: Access denied for user 'kamailio'@'localhost' (usin
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: ERROR: <core> [db.c:319]: db_do_init2(): could not add connection to the pool
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: ERROR: htable [ht_db.c:92]: ht_db_open_con(): failed to connect to the database
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud /usr/sbin/kamailio[2243]: INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Control process exited, code=exited status=255
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
-- Subject: Unit kamailio.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit kamailio.service has failed.
--
-- The result is failed.
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Unit entered failed state.
Sep 21 14:22:37 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Failed with result 'exit-code'.
Sep 21 14:22:38 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Service hold-off time over, scheduling restart.
Sep 21 14:22:38 sipr-0-ce.myunityconnect.cloud systemd[1]: Stopped Kamailio (OpenSER) - the Open Source SIP Server.
-- Subject: Unit kamailio.service has finished shutting down
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit kamailio.service has finished shutting down.
Sep 21 14:22:38 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Start request repeated too quickly.
Sep 21 14:22:38 sipr-0-ce.myunityconnect.cloud systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
-- Subject: Unit kamailio.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit kamailio.service has failed.
--
-- The result is failed.
Sep 21 14:22:38 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Unit entered failed state.
Sep 21 14:22:38 sipr-0-ce.myunityconnect.cloud systemd[1]: kamailio.service: Failed with result 'exit-code'.

**Comment by mackhendricks** [comment]
It looks like it can't access the database anymore...weird.  We will try to reproduce.

Try to do a:

dsiprouter resetpassword -all
sed -i -e 's/teleblock.gw_enabled = /teleblock.gw_enabled = 0/' /etc/kamailio/kamailio.cfg
systemctl restart kamailio
dsiprouter restart

**Comment by DForester-FTC** [comment]
Hi

That got things back up and running again. 

Thanks,

Dean

**Comment by DForester-FTC** [comment]
Thanks.
