### ISSUE TITLE
Removing an Endpoint Group doesn't remove the endpoint from the address table

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#269]
Steps to reproduce:

1) Create an Endpoint Group (Make sure to remember the Endpoint Group id)

2) Add an Endpoint

3) Remove the Endpoint Group

4) Check the address table

 - mysql -e "select * from address where tag like 'gwgroup:<gwgroupid>%'" kamailio

This happens in 0.621 and 0.63.

**Comment by reqlez** [comment]
I have seen weird issues with that I think when I was testing teams.

It seems like some kind of "disconnect" between gui and the DB.   I remember I was testing teams, and I was getting TWO calls into teams, meaning, the same teams server was added twice somehow in BD, but I could only see a single entry in GUI.

**Comment by devopsec** [comment]
Fixed in https://github.com/dOpensource/dsiprouter/pull/308.  
To avoid issues like this in the future we will be doing an API / GUI overhaul to separate common code into reusable modules..
