### ISSUE TITLE
SIP Providers that send a different Realm during Username/Password Auth will fail

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#270]
We have a customer that uses a SIP Provider that sends a realm during the REGISTER process that doesn't match their domain.

SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 10.30.100.1:5060;branch=z9hG4bK8c9b.4f65aa52000000000000000000000000.0
To: <sip:rdr3w5h@voice.bconnect.com>;tag=415c837a
From: <sip:rdr3w5h@voice.bconnect.com>;tag=7884291819c33b700ba0286debab419f-f2406295
Call-ID: 4815386e461970f4-22399@10.30.100.1
CSeq: 210 REGISTER
WWW-Authenticate: Digest nonce="1600943072:be7c5159fe11dde4d027fa91537909a03497440e",algorithm=MD5,realm="sip-1.pb"
Content-Length: 0

Notice that the domain is bconnect.com, but the realm is sip-1.pb.  dSIPRouter doesn't know how to handle this and doesn't send the follow-up REGISTER with the realm

**Comment by devopsec** [comment]
This seems like intended behavior based on RFC 3261.  
If the domain doesn't match one dsiprouter knows about it should not auth it.  
The phone must send the correct domain to be able to auth.
