### ISSUE TITLE
Web Interface Unresponsive

### ISSUE THREAD

**Issue by demonspork** [dOpensource/dsiprouter#273]
The Web Interface often becomes unresponsive after several days. This has been an issue across multiple installations over the past ~year when I would leave it alone for a week or 2 and when I come back the web interface is no longer loading. Calls continue to route just fine and endpoints are registered.

What logs do you need from me to troubleshoot this? I not on 0.63 yet, I think 0.621 or something like that but it is currently not responding so I figured I would be able to get better logs if it is currently broken.

**Comment by mackhendricks** [comment]
Yes...this is an issue that we have noticed.  It's due to the Python Flask engine that we use.  It started happening when we turned on TLS by default.  If you turn-off TLS you will not have this problem.   Our goal is to front-end the project with Nginx or some other webserver

**Comment by demonspork** [comment]
Alright. Cool. I was planning to front end it through a reverse proxy eventually anyways. Don't forget to check the proxy headers if you write any code that logs/uses the web user's ip address in the future :)

**Comment by pete1019** [comment]
How to fix this for now without having to reboot? Some service restart? Which ones? Thanks

**Comment by pete1019** [comment]
push
Any news?
Thanks

**Comment by mackhendricks** [comment]
A fix will be in 0.64, but you can disable https in /opt/dsiprouter/gui/settings.py file.  Set the following values to http:

DSIP_PROTO
DSIP_API_PROTO

**Comment by pete1019** [comment]
Changed to http. Rebooted. Still on https.
Ideas? Thanks

**Comment by devopsec** [comment]
Fixed in v0.64, HTTPS is now the default with no externally available HTTP endpoint, dSIPRouter is accessible through the reverse proxy (NGINX).  
In the future we will probably clean up those old settings because dSIPRouter is using unix domain sockets in the background.

**Comment by devopsec** [comment]
BTW closing PR here: https://github.com/dOpensource/dsiprouter/pull/298
