### ISSUE TITLE
Duplicate Inbound Mappings Should Provide a detailed error message

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#276]
If you attempt to enter an Inbound DID Mapping with the same DID it give an HTTP error.  It should provide error stating that the DID is already mapped to an endpoint.

**Comment by Graviton144** [comment]
I am still having issues getting DSIPRouter installed on vitualbox with Debian9, Ubunto 16 and Centos 7. In all cases Kamailio fails. Have tried all variations of the one line command i.e behind nat etc it just does not work. I have followed your youtube video also for the installation. Is there another install guide or am I missing something? Please help

**Comment by Graviton144** [comment]
Great News!!! I have been able to install on Digital Ocean Droplet with Debian 9 :)

I am using a Singapore server as I live in Sydney and they don't have a presence in Australia, this is why I want to use Vultr. Begs the question why I cant install on VirtualBox or Vultr. But now I am smiling.

If anyone has had success on vultr and the steps required that would be great and also VirtualBox.

**Comment by RichSosa28** [comment]
This issue has been validated. It can be reproduced with the following steps below:
1. Install dSIPRouter
2. Login into the web gui with the provided credentials 
3. Create an endpoint group
4. Click on "Inbound DID Mapping" and add one
5. Attempt to add another "Inbound DID Mapping" with the same DID number

Possible Solution:
A possible solution is when a user enters in the same DID and clicks the add button, the gui should state that the DID number has already been used, prompting the user to enter in a different DID.

**Comment by mackhendricks** [comment]
We will first update the Inbound Mapping page to use the Inbound Mapping API #334 .  Then we will update the client side validation to display an error message when someone attempts to add a duplicate DID.

**Comment by devopsec** [comment]
slated for 0.75, this should just propogate the error to the frontend error handler
