### ISSUE TITLE
Endpoint Groups - Username and Password - dynamic ip addresses

### ISSUE THREAD

**Issue by qmex-mp** [dOpensource/dsiprouter#277]
In Germany we have some Customers with On Premise PBX and a DSL Connection. Most of these DSL Connections have a dynamic IP and ISP forces a reconnect every 24 hours.

After some weeks now, I have 85 different IP Addresses in the dr_gateways table all for the same gwgroup.
There are a few reasons why this is problematic:
1. If we have overlapping IPs because different customer have the same ISP, calls would be billed for the wrong customer
2. Incoming Routing: Calls would be routed to wrong customer (after some trying as there is no priority)

Expected behavior:
IP Adress gets updated with the new one and not added

Used Version: 0.63

**Comment by RichSosa28** [comment]
Reproduce the issue by creating an endpoint and registering it to a softphone and then closed the softphone and reopen it.

**Comment by devopsec** [comment]
Hook into this in kam config for cleaning up registrations when they expire:

**Comment by RichSosa28** [comment]
Temporary fix contributed from qmex-mp:

else {
          xlog("L_DBG","[REGISTRAR] <$ci> adding registration address $var(received_addr) to gateways for gwgroup $avp(src_gwgroupid)\n");

         sql_query("kam", "SELECT gwid FROM dr_gateways WHERE address='$var(received_addr)' AND description LIKE '%gwgroup:$avp(src_gwgroupid)%'", "rb");

                     if ($dbr(rb=>rows) == 0) {
                              sql_query("kam", "DELETE FROM dr_gateways WHERE description LIKE '%gwgroup:$avp(src_gwgroupid)%';");
                              sql_query("kam", "INSERT INTO dr_gateways VALUES (NULL,$var(type_pbx),'$var(received_addr)',0,'','','name:autoregister,type:$var(type_pbx),gwgroup:$avp(src_gwgroupid)');");
                             sql_query("kam", "UPDATE dr_gw_lists SET gwlist=LAST_INSERT_ID() WHERE id=$avp(src_gwgroupid)");
                             jsonrpc_exec('{"jsonrpc": "2.0", "method": "drouting.reload", "id": 1}');
                        }
                        sql_result_free("rb");
              }
             exit;

**Comment by devopsec** [comment]
Please note that the above will work for single endpoints in an endpoint group, but..  
If there is more than one endpoint in the endpoint group those endpoints will be kicked out until re-REGISTERing.  
The solution to this issue is to look up the info when the registration expires, please see my previous comment:  
https://github.com/dOpensource/dsiprouter/issues/277#issuecomment-735840853

**Comment by devopsec** [comment]
I added the expiration hook that deletes the endpoints from the tables when they expire.  
Some of the more nuance issues need verified.

**Comment by devopsec** [comment]
Has this been merged in?

**Comment by RichSosa28** [comment]
Validated that this is no longer an issue.
