### ISSUE TITLE
Fusionpbx domain import no longer working

### ISSUE THREAD

**Issue by andycol** [dOpensource/dsiprouter#282]
I have installed the master branch on a vultr server and a digitalocean server
after entering the fusion details and running 
/opt/dsiprouter/gui/dsiprouter_cron.py fusionpbx sync

nothing imports
if i run a tcpdump -i any port 5432 on my fusionpbx server i do not see any requests from dsiprouter

**Comment by RichSosa28** [comment]
How did you configure fusionpbx? This should work fine.

**Comment by mackhendricks** [comment]
Closing for now because we validated that it works.  If you are still having problems please post the issue here: https://groups.google.com/g/dSIPRouter
