### ISSUE TITLE
Setup with FreePBX

### ISSUE THREAD

**Issue by arctic-ice-cool** [dOpensource/dsiprouter#29]
Hi,
After all day of trying to figure out how to add dSIProuter as a FreePBX outbound & inbound route / trunk, i figured I'd just ask here.

I've tried all sorts of standard SIP configuration, is there a guide or any advice on how to configure the FreePBX for outbound dialling & inbound calls?

All my efforts led me to basically having sngrep show me the odd packet trying to talk to dSIProuter however it didn't seem to act on it, or do anything.

The Kamailio logs didn't seem to be pickip up the traffic either, however sngrep detected the traffic hitting the server from unknown@XX.XX.XXX.XX

Thanks!

**Comment by mackhendricks** [comment]
Okay…Did you add your ip the PBX/Endpoint section and reload Kamailio by pressing the “Reload Button”.  Then you need to setup FreePBX to point at the Kamailio server.  

But, I will spin up an instance of FreePBX and test it out in a bit and write up the steps.

**Comment by arctic-ice-cool** [comment]
Oh wow I had absolutely no idea you would be so responsive! I've been working on this for over 8 hours today and although confirmed they were talking to eachother i just didnt get it working.

Not sure what the FreePBX config should be for dSIProuter and whether kamailio was working properly to be honest.

I had to reinstall dSIProuter a few times until I realised Perl was missing!

Looking forward to seeing your suggested steps and giving it one last bash!

Thanks

**Comment by arctic-ice-cool** [comment]
Im using chan_sip on FreePBX not PJsip by the way

**Comment by mackhendricks** [comment]
Which OS are you using?  Not sure why Perl was needed…But, we can do a Google Hangout if you have time versus me spending up a new environment.  Send me an email at support@dopensource.com <mailto:support@dopensource.com> and I will set one up.

**Comment by arctic-ice-cool** [comment]
Sorry Python not Perl.
It's 0.15 here now, would be more than happy to Google Hangout in around 9hrs time if thats any good to you? So 9am GMT?

I used Debian 8 and literally did Vanilla installs but it just all seemed unresponsive

I have multiple FreePBX setup and working fine but just couldn't get this to work.

I did consider looking at FusionZpbx however its quite a leap and doesn't look as popular as FreePBX

**Comment by mackhendricks** [comment]
3pm GMT will work for me.  Send me an email to support@dopensource.com <mailto:support@dopensource.com> and I will schedule the Google Hangout.

Thanks

**Comment by arctic-ice-cool** [comment]
Sure! I've sent that over now

Thanks

**Comment by kristiandg** [comment]
Any shot of having the customer PBX trunks actually register with the system (instead of putting the IP in there)? I see where I can put credentials in if I'm reaching out to their system, but I'm looking for it to be the other way (they register their system to us for trunking)?

**Comment by mackhendricks** [comment]
Carrier Registration is scheduled for 0.50 in August
