### ISSUE TITLE
MS Teams test button does not work 0.64

### ISSUE THREAD

**Issue by reqlez** [dOpensource/dsiprouter#292]
So i'm not sure if this button needs something specific to work, however, I have confirmed that I can call from Teams via dsiprouter / carrier to the PSTN okay.  Incoming from PSTN to Teams does not work but I'm still testing that and it could be unrelated ( or maybe it is ).

![image](https://user-images.githubusercontent.com/6512602/99384945-74340c80-288d-11eb-8bd6-68d84d23e884.png)
![image](https://user-images.githubusercontent.com/6512602/99384986-8746dc80-288d-11eb-9390-6b0b5f3307d1.png)

**Comment by reqlez** [comment]
Actually, I should not say that incoming calls into Teams DID do not work, they do... Teams rings but as soon as I pickup the call in teams I hear a busy signal on the "calling" phone.

**Comment by reqlez** [comment]
Wait a second... does this feature by any chance use the currently connected to hostname of the server ?  ( like if server is sip.provider.com    and that works, however, internally I connect via internal IP address to the web interface ... ) or does it actually test the right domain name specified in the domains ...

**Comment by bcmike70** [comment]
I get this when I test the domain in .064:
![image](https://user-images.githubusercontent.com/63665645/100649557-75d2eb00-32f7-11eb-8c08-5bd44d67fb74.png)

However when I do ' kamcmd dispatcher.list" from the command line it works fine.
