### ISSUE TITLE
SignalWire Trunk ACK Timeout

### ISSUE THREAD

**Issue by reqlez** [dOpensource/dsiprouter#296]
Hi.

I saw a video from May about getting a SignalWire trunk setup with dsiprouter.  I love signalwire as well, so I wanted to check it out.

I was able to setup signalwire behind a NAT with freepbx before no problem, so I know it works behind NAT.

When I tried it with dsiprouter, version .64 ( have not tried another version yet ) when I call out, after 30 seconds my call gets disconnected and I see SIP;cause=408;text="ACK Timeout" in the logs.  Another trunk works okay no problem.

So is SignalWire support "fully" here ?  Any recommendations? or it does not work behind NAT ?

**Comment by mackhendricks** [comment]
We have not tried it behind NAT.   We can reproduce it behind NAT and apply a fix

**Comment by reqlez** [comment]
okay, well, maybe there is more to it than this.  So I finally got Teams calls to work incoming as well... and I'm getting this from Teams server:

Call Controller timed out while waiting for acknowledgement."

So I think this is an overall NAT issue of having the SBC behind NAT, maybe just a bad idea ...

**Comment by mackhendricks** [comment]
Are you installed with the -servernat option.  We plan to test 0.64 with MSTeams module this week with servernat enabled.

**Comment by reqlez** [comment]
> Are you installed with the -servernat option. We plan to test 0.64 with MSTeams module this week with servernat enabled.
> […](#)
> Sent from my iPhone
> On Nov 17, 2020, at 8:55 PM, reqlez ***@***.***> wrote: ﻿ okay, well, maybe there is more to it than this. So I finally got Teams calls to work incoming as well... and I'm getting this from Teams server: Call Controller timed out while waiting for acknowledgement." So I think this is an overall NAT issue of having the SBC behind NAT, maybe just a bad idea ... — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes I am indeed.  I'm going to go thru the config options to make sure I forwarded all the ports right, but I know I forwarded 10000 to 20000 that is default, and 5060 and 5061 all UDP/TCP. I also have my router in conservative mode for state tables.

i made sure the hostname is correct, I manually requested the certs for that hostname and replaced default certs. made sure reverse DNS is all good too, the usual stuff.

What's interesting, is that... another trunk I was using, was working good.    However, it seems MS Teams AND Signalwire are both having some sort of issues with ACK ... and I'm not a SIP engineer to diagnose the protocol properly either, but, I can assist with testing for sure if you need some assistance.

**Comment by reqlez** [comment]
Also, an idea on IP addresses for SignalWire ... maybe we can do some kind of cron job or something, that will do nslookup sip.signalwire.com   and parse all the IPs from the response and insert them into the SignalWire carrier group? Maybe the use of a special name for the carrier group, like ... "SignalWire-Auto" will trigger this nslookup logic ?   not  how Kamailio works in the background, and if we can do an auto reload without breaking calls, or send admin an e-mail saying new IPs in signalwire group, do manual reload... ?  any ideas ?

**Comment by reqlez** [comment]
Just tested this again with my newly working CentOS 8 install + 0.64.

Same issue, 32 seconds call gets cut off.

**Comment by mackhendricks** [comment]
We will try to reproduce in our NAT’d environment and make changes to support to it

**Comment by reqlez** [comment]
So here is a command that parses the IPs from SignalWire and adds them into IPTABLES. We can use the above example, but to populate the database table of endpoints.  I haven't seen the DB structure yet, but I think combining this with some kind of cron task, could be viable?

dig sip.signalwire.com | egrep ^sip | awk '{ print $5 }' | xargs -n1 -I{} iptables -A INPUT -s {} -j ACCEPT

Maybe we should start a new ticket for this... and discuss developing it, I might get something going after I analyze the DB schema.
