### ISSUE TITLE
Need to add support that will generate a unique password on install

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#3]
Will generate a unique password and will display it after a successful install

**Comment by lgg** [comment]
algo:
load password from settings.py
check if password in settings.py is default -> generate new pass or use pass from settings.py

**Comment by mackhendricks** [comment]
@lgg We are generating a unique password in the latest release now, but will add in support for checking if the default password is set before generating a new password.  This will enable people to automate the install with a pre-set password.  So, I'm not closing this until that piece is done.  Marking it for the 0.40 release

**Comment by mackhendricks** [comment]
Actually...I will close this one and open a new issue for the additional feature
