### ISSUE TITLE
pbx endpoint can we change static ip to sip url 

### ISSUE THREAD

**Issue by dipenpatel235** [dOpensource/dsiprouter#31]
instead of PBX ip can we route the call/request to a sip uri ?
sip uri is our sip client. (i.e.  sip:91764323423@sip.domain.com)

Thanks

**Comment by mackhendricks** [comment]
Yes, we can put that on the roadmap.  If you need it immediately you can open a paid support ticket and we can create a patch for you.  You can purchase time and open a ticket at http://dOpenSource.com/shop.  You would need a 10 hour block of time

**Comment by dipenpatel235** [comment]
Ok...Thanks you so much..

Not urgent and I will  wait for open source as per your road map.

Suppose if I will pay then what is your charge ?

Thanks

**Comment by mackhendricks** [comment]
The pricing for 10 hours is located at http://dOpenSource/shop

**Comment by mackhendricks** [comment]
Http://dOpenSource.com/shop

**Comment by dipenpatel235** [comment]
Thanks..
It is to much high to me..I can't affordable.
So waiting for your open source .

Thanks again

**Comment by mackhendricks** [comment]
Putting this on the roadmap for 0.50.   If you can provide more justification for this we might can move the release time.

**Comment by devopsec** [comment]
The PBX api endpoint deals with the address and dr_gateways tables. Droutig module accepts hostnames and we can easily resolve host to ip for address table, there is no need for the full sip uri here, the username for for registration is added in the UAC registration fields. You can specify the same PBX if you would like to Ismailia to forward registrations to that endpoint

**Comment by devopsec** [comment]
We actually don't need to resolve the host to an ip address, Kamailio's address table permits DNS Domain Names. See reference : https://www.kamailio.org/docs/modules/5.1.x/modules/permissions.html#sec-address-permissions
