### ISSUE TITLE
Default Certificate Upload Wrong Format Type

### ISSUE THREAD

**Issue by devopsec** [dOpensource/dsiprouter#314]
When default cert is uploaded we require the format to be in DER but kamailio is expecting it to be in PEM format.

**Comment by devopsec** [comment]
In kamailio logs you will see the following error trying to parse the DER cert (should be PEM):

```
Dec 03 20:31:11 v0641-deb10.dsiprouter.org /usr/sbin/kamailio[32309]: ERROR: tls [tls_domain.c:542]: load_cert(): TLSs<default>: Unable to load certificate file '/etc/dsiprouter/certs/dsiprouter.crt'
Dec 03 20:31:11 v0641-deb10.dsiprouter.org /usr/sbin/kamailio[32309]: ERROR: tls [tls_util.h:42]: tls_err_ret(): load_cert:error:0909006C:PEM routines:get_name:no start line
Dec 03 20:31:11 v0641-deb10.dsiprouter.org /usr/sbin/kamailio[32309]: ERROR: tls [tls_util.h:42]: tls_err_ret(): load_cert:error:140DC009:SSL routines:use_certificate_chain_file:PEM lib
Dec 03 20:31:11 v0641-deb10.dsiprouter.org /usr/sbin/kamailio[32309]: ERROR: <core> [core/sr_module.c:781]: init_mod_child(): error while initializing module tls (/usr/lib/x86_64-linux-gnu/kamailio/modules/tls.so)
```

**Comment by mackhendricks** [comment]
Can you give the steps to reproduce?  I upload my certs in PEM format.

**Comment by devopsec** [comment]
1. create a domain in digital ocean
2. start key/cert creation in certbot `certbot certonly --server https://acme-v02.api.letsencrypt.org/directory --agree-tos --manual --preferred-challenges dns -d '<your-new-domain.com>'`
3. add the TXT entry in digital ocean for the new domain
4. finish key/cert creation in certbot prompts
5. copy key/certs to your local machine `rsync -rKL /etc/letsencrypt/live/<your-new-domain.com>/ tmoore@jump.dopensource.com:/tmp/certs/`
6. convert the cert from PEM to DER format (required by API) `openssl x509 -outform der -in /tmp/certs/cert.pem -out /tmp/certs/cert.crt`
7. navigate to certificates page in dsiprouter, click add, check "replace default certificate", and attach both `/tmp/certs/cert.crt` and `/tmp/certs/privkey.pem`, see attached screenshot for example
8. dsiprouter will replace the certs without issue but when kamailio is reloaded it will fail because it is expecting the cert to be in PEM format

![tmp](https://user-images.githubusercontent.com/18452447/101181169-91513500-361a-11eb-946d-cabdb785808f.png)
