### ISSUE TITLE
where is my docker ;-)

### ISSUE THREAD

**Issue by baroninn** [dOpensource/dsiprouter#318]
ERROR: Cannot locate specified Dockerfile: docker/dsiprouter/dockerfile

whatup ?

**Comment by RichSosa28** [comment]
Hello, what version of dSIPRouter are you using?

**Comment by mackhendricks** [comment]
We don't have the resources to support this.  We are looking for someone to maintain the docker version of dSIPRouter.   Please let me know if you are interested in doing so.  We would support you in this effort.  We just can't own it.
