### ISSUE TITLE
Upgrading to v0.64 

### ISSUE THREAD

**Issue by RichSosa28** [dOpensource/dsiprouter#319]
Upgrading to v0.64 fails.
Reproduce this issue by:
1. Installing v0.63 of dSIPRouter
2. Then run the following commands:
     cd /opt/dsiprouter
     git stash
     git checkout v0.64
     dsiprouter upgrade -rel 0.64

**Comment by devopsec** [comment]
The upgrade process for right now is:
1. backup your DB data and /etc/dsiprouter/ directory
2. uninstall dsiprouter completely
3. install the version you want to upgrade to 
4. restore your backups
5. fix any conflicts that come up

The `upgrade` command is not production ready yet and is on to TODO list for v0.70
