### ISSUE TITLE
RTPengine not installing - Fails Install

### ISSUE THREAD

**Issue by cordial007** [dOpensource/dsiprouter#320]
Upon running the installation script on a fresh Debian 10, RTPengine install fails.

The following was tried along with other installation methods.

apt-get update -y && apt-get install -y git && cd /opt && git clone https://github.com/dOpensource/dsiprouter.git && cd dsiprouter && ./dsiprouter.sh install -all

I have been trying for 2 days now.

Screenshot below.

   dh_builddeb
dpkg-deb: building package 'ngcp-rtpengine-recording-daemon-dbgsym' in '../ngcp-rtpengine-recording-daemon-dbgsym_9.0.1.4+0~mr9.0.1.4_amd64.deb'.
dpkg-deb: building package 'ngcp-rtpengine' in '../ngcp-rtpengine_9.0.1.4+0~mr9.0.1.4_all.deb'.
dpkg-deb: building package 'ngcp-rtpengine-daemon' in '../ngcp-rtpengine-daemon_9.0.1.4+0~mr9.0.1.4_amd64.deb'.
dpkg-deb: building package 'ngcp-rtpengine-utils' in '../ngcp-rtpengine-utils_9.0.1.4+0~mr9.0.1.4_all.deb'.
dpkg-deb: building package 'ngcp-rtpengine-kernel-source' in '../ngcp-rtpengine-kernel-source_9.0.1.4+0~mr9.0.1.4_all.deb'.
dpkg-deb: building package 'ngcp-rtpengine-kernel-dkms' in '../ngcp-rtpengine-kernel-dkms_9.0.1.4+0~mr9.0.1.4_all.deb'.
dpkg-deb: building package 'ngcp-rtpengine-iptables' in '../ngcp-rtpengine-iptables_9.0.1.4+0~mr9.0.1.4_amd64.deb'.
dpkg-deb: building package 'ngcp-rtpengine-iptables-dbgsym' in '../ngcp-rtpengine-iptables-dbgsym_9.0.1.4+0~mr9.0.1.4_amd64.deb'.
dpkg-deb: building package 'ngcp-rtpengine-daemon-dbgsym' in '../ngcp-rtpengine-daemon-dbgsym_9.0.1.4+0~mr9.0.1.4_amd64.deb'.
dpkg-deb: building package 'ngcp-rtpengine-recording-daemon' in '../ngcp-rtpengine-recording-daemon_9.0.1.4+0~mr9.0.1.4_amd64.deb'.
 dpkg-genbuildinfo
 dpkg-genchanges  >../ngcp-rtpengine_9.0.1.4+0~mr9.0.1.4_amd64.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build .
dpkg-source: info: using options from rtpengine/debian/source/options: --extend-diff-ignore=.gitreview
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
 signfile ngcp-rtpengine_9.0.1.4+0~mr9.0.1.4.dsc
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: skipped "Sipwise Jenkins Builder <jenkins@sipwise.com>": No secret key
gpg: dpkg-sign.wTiVOozV/ngcp-rtpengine_9.0.1.4+0~mr9.0.1.4.dsc: clear-sign failed: No secret key

dpkg-buildpackage: error: failed to sign .dsc file
Problem installing RTPEngine DEB's
RTPEngine install failed
root@sbc195:/opt/dsiprouter#

Any ideas how to bypass?

**Comment by RichSosa28** [comment]
Hey, what cloud provider are you using? Ran a test with digitalocean and it installed.

**Comment by cordial007** [comment]
RichSosa28, Thanks for the reponse.

I tried again on another server and it failed at same point. 

signfile ngcp-rtpengine_9.0.1.4+0~mr9.0.1.4.dsc
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: skipped "Sipwise Jenkins Builder <jenkins@sipwise.com>": No secret key
gpg: dpkg-sign.6dYakQZ5/ngcp-rtpengine_9.0.1.4+0~mr9.0.1.4.dsc: clear-sign failed: No secret key

dpkg-buildpackage: error: failed to sign .dsc file
Problem installing RTPEngine DEB's
RTPEngine install failed

The server is a VM in our rack in a datacentre in Melbourne, Australia. The VM host server is running Proxmox 6.2-15 and the VM is a KVM freshly installed Debian 10 minimum. Nothing else installed before running script. 

I just tried on a Vultr instance and you are correct it worked flawlessly.

I will try it on another VM located in another Datacenter in Sydney. I will install with standard Debian 10 not min netinstall.

**Comment by cordial007** [comment]
OK, I have succesfully installed in same VM, but with Debian 9.13.  
So there may be an issue with my old installation of Debian 10 or installing in Debian 10. I have snapshot the old VM in case i need it. Not sure if anyones wants this ticket left open or not. Please close if not.

**Comment by RichSosa28** [comment]
Hey which version of dSIPRouter where you using? Is it v0.64?

**Comment by devopsec** [comment]
@cordial007 we don't have proxmox as a deployment platform in our current testing scenario.  
This is something we may add in the future.  

As far as the signing error goes this is fixed in version 0.641  

To fix for previous version changes this line:
https://github.com/dOpensource/dsiprouter/blob/master/rtpengine/debian/install.sh#L78

To look like this:

```
dpkg-buildpackage -us -uc -sa &&
```

**Comment by mromero-convoso** [comment]
Another solution I found was to move the ".gnupg" folder within "/root" to some other location, then run the build as normal, and move the .gnupg  folder back to /root after the build completes. In my case:
```cd /root && mv .gnupg .gnupg_old && cd /usr/local/src && rm -rf ngcp* rtpengine && chef-client && cd /root && mv .gnupg_old .gnupg```
