### ISSUE TITLE
Whitelist IP List

### ISSUE THREAD

**Issue by devopsec** [dOpensource/dsiprouter#322]
This problem has been discovered multiple times, but the issue that triggered this issue is this:
OPTIONS Are Dropped On USER/PASS Authentication

When a carrier or endpoint is added using user/pass authentication OPTIONS / any non INVITE or REGISTER is denied.  
This is because the subscriber table is used for auth on INVITE and REGISTER for user/pass auth but the address table is checked for other requests.  

I suggest we add the following flag for non-routable IP's in general:  
- FLT_WHITELIST_IP

This would be used to match against the group id in the address table for non-routable IP's, allowing them to be proxied through.  
Note that this group id should **not** be valid for any routing request (requests we apply additional auth checks to) such as:
- INVITE
- REGISTER
- UPDATE
- REFER
- MESSAGE

On the frontend we should allow any carrier group or endpoint group to add IP's to this whitelist.  
Another use case for this is when a carrier has separate outbound and inbound (from their perspective) edge SBC's.  
The inbound SBC is typically where dsiprouter would route to and must be routable but dsiprouter must allow traffic from the inbound SBC as well, which is where the whitelisted IP's could be used.

**Comment by devopsec** [comment]
implemented this for a customer already, works great.  
For release I would like to tie this into GUI with an option to add whitelisted IP's to a carrier group or endpoint group.

**Comment by mackhendricks** [comment]
Great!  To keep inline with our design principles, I think we need an API for this, which the GUI will use to manipulate it.  Perhaps the endpoint /v1/whitelist/<gwgroupid|endpointgroupid>/
