### ISSUE TITLE
create MAN pages for dsiprouter CLI commands

### ISSUE THREAD

**Issue by devopsec** [dOpensource/dsiprouter#323]
We need some more descriptive documentation on the CLI commands for dsiprouter.  
I propose we create a user (1) manual page upon install of the dsiprouter command that contains more descriptive explanations / examples of the CLI usage.  

As discussed this morning @RichSosa28 I'll walk you through the entire CLI while you take notes.  
Then you can format it as a man page that will be installed with dsiprouter.  
This man page would likely be a template (like most of our static files in the repo) that will have the commands / flags generated during install script execution and the file output to proper system location.  

Note that it would be nice if we could consolidate the list of commands and options into one file that is imported in our scripts.  
The reason being is the CLI command text descriptions are defined in 2 places already and this addition would be the third (making updates 3x more of a hassle).  
Currently when a CLI command defition is added/removed/changed in `dsiprouter.sh` we have to update:  
- the help description in `dsiprouter.sh`
- the tab completion in `dsip_completion.sh`

Preferably we would have all the CLI command info stored in a single file or directory, perhaps `dsiprouter/cli/`  

Here is some documentation on man pages to get you started:

https://www.golinuxcloud.com/create-man-page-template-linux-with-examples/
https://tldp.org/HOWTO/Man-Page/q3.html
https://gist.github.com/eddieantonio/55752dd76a003fefb562

**Comment by mackhendricks** [comment]
Was committed v0.65, but it was back-ported to 0.64x
