### ISSUE TITLE
Data too long for column 'db_host' at row when using Amazon RDS databases

### ISSUE THREAD

**Issue by blackc2004** [dOpensource/dsiprouter#327]
I use an Amazon RDS instance for my FusionPBX database. When trying to add the RDS endpoint as a fusionPBX endpoint I am getting an error that the host name is too long.  The hostname is 50 chars long and I do not see anywhere in RDS to use IP or a shorter hostname. 

`Detailed Information: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'db_host' at row 1")[SQL: INSERT INTO dsip_multidomain_mapping (pbx_id, db_host, db_username, db_password, domain_list, attr_list, type, enabled) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)][parameters: (17, 'MY_HOST_NAME', 'fusionpbx', 'MY_PASSWORD', '', '', 1, 1)](Background on this error at: http://sqlalche.me/e/13/9h9h)
`

**Comment by devopsec** [comment]
Heres the filepath @RichSosa28

**Comment by RichSosa28** [comment]
This will be fixed in our 0.642 release but a quick fix for it is going to dsiprouter/gui/modules/domain/domain_mapping.sql and on line 29 increase the character count from 20 to 255 or however much you need:
`db_host` varchar(255) NOT NULL
