### ISSUE TITLE
30 min ping from carrier not being passed or ignored

### ISSUE THREAD

**Issue by jzrlost** [dOpensource/dsiprouter#352]
Upgraded to .641 and now at 30 mins the calls lose audio.  Sometimes they lose at 10-15 mins but that hasn't been consistent.  The call just sits dead with no audio until I hang up.  This wasn't happening with the older version .523.

**Comment by mackhendricks** [comment]
Can you provide a pcap? And which OS are you using?

**Comment by jzrlost** [comment]
I will try to get a pcap tonight of a call that times out.  I am running Debian 10 server.

**Comment by jzrlost** [comment]
Finally was able to pull a pcap.  It looks like the PBX is sending an ack to dsiprouter that is then passing that to the carrier, but they do not respond.  Can you verify that by looking at the pcap or is it something else I'm missing?
[30mincall_done.zip](https://github.com/dOpensource/dsiprouter/files/6194834/30mincall_done.zip)

**Comment by jzrlost** [comment]
It only seems to be effecting outbound calls.  Inbound calls through the same dsiprouter router, carrier, and pbx do not have this 30 min disconnect.  Don't remember the older version having this limit before.

**Comment by jzrlost** [comment]
Another update.  I went ahead and setup a trunk that connects directly between the PBX and the carrier.  The calls goes over the 30 min limit that seems to kick in going through the Dsiprouter.  It is something with Dsiprouter that is causing the drop after 30 mins.

**Comment by mackhendricks** [comment]
Okay...thanks for the info.  We will look at what’s causing it

**Comment by devopsec** [comment]
@jzrlost from your PCAP freepbx is the one initiating the BYE, which you can see in the attached screenshot is because it thinks the channel is dead.  
I wager a guess that your issue is:
1. your not setting RTP keep alive on freepbx or 
2. the OPTIONS messages are being dropped by dsiprouter.  

If it is 1, then you can read the freepbx documentation to find the proper settings for RTP keepalive.  
If it is 2, then you will need to wait for release v0.65 or create a pull request for https://github.com/dOpensource/dsiprouter/issues/322

**Comment by jzrlost** [comment]
We are thinking it's an issue with Dsiprouter (dropping or not passing the OPTIONS messages.  We setup another instance of Dsiprouter and used version .523 and use that as a separate trunk for outgoing only and we have not seen the issue since.  We are not sure which version of Dsiprouter this started since we jumped from .523 to .641 and that's when the problem started.  Unless it's an issue between Debian 9 and Debian 10.  We have Debian 9 using Dsiprouter .523 and Debian 10 using Dsiprouter .641.  We are using the same router/firewall, PBX and carrier.  The only thing that is different is when we pass the outbound calls through Dsiprouter .641 the calls drop at 29-30 mins.  If we route the calls through Dsiprouter .523 the calls run until we hang up.  I have been on a test call for 1 hour 21 mins right now.  And last night I had a test call go for over 2 hours.  I'm not sure what version to point the finger at, but .641 has it.  I will wait for .65 to come out and then I will do some testing.  It's odd that no one else is having the issue, but we have 2 Dsiprouter servers that do it.  Maybe if I get a change I will load up another Debian 9 and try to the .641 version.  Then I will know if it's OS related or not.  Thank for all the hard work on this project.

**Comment by jzrlost** [comment]
As for pull request #322 we are using IP authentication not user/pass authentication.

**Comment by devopsec** [comment]
Interesting, the routing has significantly changed since that version so the comparison won't really help narrow down the issue.  
I would recommend doing another traffic dump and sending us the PCAP with **all** the traffic, so we can contextualize the full picture.  
It may be an OPTIONS dropped on IP auth issue, it could be something else completly but we need more info to narrow it down.

**Comment by jzrlost** [comment]
What cli command do you want me to capture the pcap with?  I normally use sngrep -r and then save the call with f2.

**Comment by devopsec** [comment]
If you don't select any rows when hitting F2 to Save, sngrep should save the entire list of packet captures, instead of the selecting single rows

**Comment by jzrlost** [comment]
Finally, found sometime to save a full a sngrep for you.
[full_capture.zip](https://github.com/dOpensource/dsiprouter/files/6490610/full_capture.zip)

**Comment by cooeyau** [comment]
I have tested 30+ min call on my 0.641 build, different PBX, no issue.

**Comment by jzrlost** [comment]
What PBX are you using?  Are you using NAT or public IP on dsiprouter?

We are using NAT behind a Ubuntu router and for the PBX we use asterisk.  The older version works fine with all of the PBXs we have, but the newer version will drop the audio at 30 mins.

**Comment by cooeyau** [comment]
> What PBX are you using? Are you using NAT or public IP on dsiprouter?
> 
> We are using NAT behind a Ubuntu router and for the PBX we use asterisk. The older version works fine with all of the PBXs we have, but the newer version will drop the audio at 30 mins.

I am using Vodia pbx, but not using NAT install mode, so yeah little different. 

What's your network picture look like, do you have some thing upstream of FPBX 1.100 ? that's involved in the call PCAP example?
