### ISSUE TITLE
Supported Network Configurations

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#366]
This issue is going to define the network configurations that dSIPRouter will support out of the box, which are:

- **Public IP Address**: dSIPRouter sitting on a public IP address
- **ServerNAT**: dSIPRouter is installed on a server that sits behind a NAT like being installed in a Private DC, Azure, Amazon and GCP
~~- **Voice VLAN**: dSIPRouter is installed in a network configuration where all traffic has to be routed to servers that reside on the Voice VLAN.  The server may still have a Public address and another Internal IP address, but all Voice traffic must still using the Voice VLAN ip~~
~~- **Multihomed**: dSIPRouter is installed on a system with two Network cards.~~

**Comment by mackhendricks** [comment]
The logic for handling with the RTPEngine is located here:

Code Snippet goes into RTPENGINEOFFER and RTPENGINEANSWER

#!ifdef WITH_SERVERNAT
        if ($du!=$null)
                $var(destIP)=$(du{s.select,1,:});
        else
           $var(destIP)=$rd;
        xlog("L_INFO", "[RTPENGINEOFFER] <$ci> destIP: $var(destIP), $avp(vlan_subnet)");

        if ($var(destIP)=~$avp(vlan_subnet))
                $var(media-address)="VOICE_VLAN_IP_ADDR";

        else if ($var(destIP)=~$avp(local_subnet))
                $var(media-address)="INTERNAL_IP_ADDR";
        else
                $var(media-address)="EXTERNAL_IP_ADDR";

        $var(reflags)= $var(reflags) + " media-address=" + $var(media-address);
#!endif


This code snippet goes into SERVERNATDETECT

# VLAN Settings Checked - will move to it's own function
        $var(vlan_subnet) = "VOICE_VLAN_IP_NET";
        # Replace the dots with \.
        $var(vlan_subnet) = $(var(vlan_subnet){s.replace,.,\.});
        # Replace the 0 with .*
        $avp(vlan_subnet) = $(var(vlan_subnet){s.replace,*,.*});

**Comment by devopsec** [comment]
This is an excellent addition!  
Note that the subnet detection is performed via `is_in_subnet()` function now instead of assuming a /24 subnet.  

The multihomed portion needs more vetting though.

**Comment by mackhendricks** [comment]
We are having an issue on GCP in particular that the interface parameter in  /etc/rtpengine/rtpengine.conf is not being generated correctly on GCP (which is a SERVERNAT configuration).

It looks like this:

[rtpengine]
table = 0
**interface = <public_ip>**
listen-ng = 127.0.0.1:7722
port-min = 10000
port-max = 20000
log-level = 7
log-facility = local1
log-facility-cdr = local1
log-facility-rtcp = local1

But, it should look like this

[rtpengine]
table = 0
interface = <private ip>!<public ip>
listen-ng = 127.0.0.1:7722
port-min = 10000
port-max = 20000
log-level = 7
log-facility = local1
log-facility-cdr = local1
log-facility-rtcp = local1

**Comment by devopsec** [comment]
serverside NAT detection and automatic configuration on the following network types will be supported in v0.70:  
- no NAT
- ipv4 NAT
- ipv6 NAT
- ipv4 and ipv6 NAT

In all these cases we are talking about **Static NAT**, as in one-to-one IP address mapping, no dynamic NAT support.

**Comment by devopsec** [comment]
A new issue will be opened and triaged for VLAN and multihomed support

**Comment by devopsec** [comment]
we can close this one, multihomed is setup via NETWORK_MODE = 2 in settings.py, we already have the CLI options and documentation merged in for that.  
will open a new issue for VLAN support
