### ISSUE TITLE
FusionPBX Integration With Bare Metal Nginx Config

### ISSUE THREAD

**Issue by devopsec** [dOpensource/dsiprouter#367]
We implemented bare metal Nginx support for the dSIPRouter GUI in the last minor release, but have not yet implemented this for the FusionPBX integrations.  
Instead of running a local docker container with another instance of Nginx we should merge these configs into the main dSIPRouter Nginx config.  

Each FusionPBX endpoint group can be set as a node in the fusionpbx upstream and routing to them would be based on `location` in the Nginx server config.  
This handles provisioning as we already supported but we should add to this the ability to access the fusionpbx GUI's from dSIPRouter.  
This would help unify the platforms, but we would have to add a setting for the alias to reach each fusionpbx box.  
In the Nginx config it would look something like this:

```
location /fusionpbx/<YOUR_FUSIONPBX1_ALIAS_HERE> {
    proxy_pass https://<YOUR_FUSIONPBX1_HOST_HERE>;
}

location /fusionpbx/<YOUR_FUSIONPBX2_ALIAS_HERE> {
    proxy_pass https://<YOUR_FUSIONPBX2_HOST_HERE>;
}

...
```

**Comment by mackhendricks** [comment]
The provisioning configuration has been implemented on the host/bare metal Nginx.

Therefore, we will remove the Docker install and configuration from the dSIPRouter installer.
