### ISSUE TITLE
Homer Integration with CDR's

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#368]
The ability to click on the Call ID within the CDR and open a window in Homer that shows that Call.  This will make it super simple to track the details of a call.

The URL format that will open a window in Homer is: https://[HOMER HOSTNAME]/search/result?%22callid%22:**[CALLID]**%22%

Here's an example of the URL that will be generated and opened when the Call ID field of a CDR is clicked 

https://159.65.162.156/search/result?%22callid%22:%5B%22t15qrM7xvG7i65_DLXCl9A..%22%5D=

Note, if you are not already logged into homer it will prompt you to login and will then take you to the Call details.

**Comment by devopsec** [comment]
we could also send the CDR data to homer:  
- https://kamailio.org/docs/modules/devel/modules/siptrace.html#siptrace.f.hlog
- https://github.com/sipcapture/homer/wiki/Example%3A-CustomStats

**Comment by cruzer45** [comment]
Homer integration is working
