### ISSUE TITLE
adduser and groups correction

### ISSUE THREAD

**Issue by ehrenmann1977** [dOpensource/dsiprouter#371]
when i tried installing dsiprouter it checked for existing user kamailio, group kamailio and dsiprouter

please add the following lines to the script

```
useradd dsiprouter
groupadd dsiprouter
groupadd kamailio
```

**Comment by devopsec** [comment]
they created later on in the install script.  
if your installing on version v0.641 those checks were in the wrong spot in the install script and is fixed in v0.65 (not yet released)
