### ISSUE TITLE
fail to install sql server issue

### ISSUE THREAD

**Issue by ehrenmann1977** [dOpensource/dsiprouter#372]
Executing: /lib/systemd/systemd-sysv-install enable kamailio
-e \E[37;33mINFO: creating database kamailio ...
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
-e \E[37;31mERROR: Creating database kamailio failed!

**Comment by devopsec** [comment]
@ehrenmann1977 that is not enough info for us to help...  
the error message is simply saying it could not connect to the database you specified on install.
