### ISSUE TITLE
New release Flask 2.0.0 breaks install

### ISSUE THREAD

**Issue by cooeyau** [dOpensource/dsiprouter#376]
I have been building a few fresh dsiprouter box's the last few days via the script and all was well then out of nowhere it stopped working, on the surface it appears its installed but the dsiprouter service will fail to load, I was pulling my hair out. The culprit ended up being,

Flask 2.0.0 that was released May 12 2021
https://pypi.org/project/Flask/#history

I tested CentOS 7 & 8

pip3 install "Flask==1.1.2" to downgrade and all is working again.

FYI

**Comment by mackhendricks** [comment]
Thank you....we will fix this ASAP
