### ISSUE TITLE
Contact header rewrite stripping

### ISSUE THREAD

**Issue by cooeyau** [dOpensource/dsiprouter#378]
https://github.com/dOpensource/dsiprouter/blob/5713f323069a50de8d0dce8bd2953e1d142b46bf/kamailio/kamailio_dsiprouter.cfg#L1662

Hey Team,

I figured I would make an issue tracker here, so it doesn’t get lost after my google groups post
Issue,

- Contact header rewrite will strip off any options message embedded with the contact when passing through to PBX causing excessive registrations before PBX times them out.

Bria Mobile on exit or app backgrounding,
`<sip:2...@xxx.xxx.xxx.xxx:58648;rinstance=3b787f06aed2173a>;+sip.instance="<urn:uuid:651dfb4c-6e12-4098-8547-80b42c68f13f>";expires=0`

Bria Desktop Client on exit,
`<sip:2...@xxx.xxx.xxx.xxx:61011;rinstance=203dc891ecdd515c>;expires=0`

I replaced with the following to get me by, but I do not think it’s the best solution and moving forward I would imagine it needs to be more selective with what its rewriting for better support. 

`if (subst_hf("Contact", "/(.*)?<(sips?):([0-9]+)@(.*>.?)/<\2:\3@$fd>/", "f")) {`

I also noticed some softphone clients will put expires in the body and some contact so its a mixed bag

**Comment by mackhendricks** [comment]
This has been updated in 0.65.  The commit it located here:

https://github.com/dOpensource/dsiprouter/commit/87dfe1150ac4a544c14102058b26b503124c0530
