### ISSUE TITLE
"Domains" The page displays "Server Issue"

### ISSUE THREAD

**Issue by linlin2018** [dOpensource/dsiprouter#380]
![1621585018(1)](https://user-images.githubusercontent.com/36178061/119105757-3ee0c500-ba50-11eb-86a9-01306710f219.jpg)

After sSIPRouter is installed, "Domains" The page displays "Server Issue"
How to solve this problem?

Kind Regards

**Comment by linlin2018** [comment]
Detailed Information: HTTPConnectionPool(host='127.0.0.1', port=5060): Max retries exceeded with url: /api/kamailio (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f2a469fee10>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by mackhendricks** [comment]
Which OS version are you using and what version of dSIPRouter are you using?

**Comment by linlin2018** [comment]
> 您使用的是哪个操作系统版本，以及使用的是dSIPRouter哪个版本？

Centos 7.8  and  dSIPRouter v0.641(latest)

**Comment by linlin2018** [comment]
This problem was caused by Kamailio not being started

**Comment by linlin2018** [comment]
Run "./dsiprouter.sh disableservernat“ ，The Kamailio reboot failed.

**Comment by mackhendricks** [comment]
Okay…can you open an issue on this so that we can fix this issue: https://github.com/dOpensource/dsiprouter/issues <https://github.com/dOpensource/dsiprouter/issues>
