### ISSUE TITLE
Late INVITE from WebRTC phone

### ISSUE THREAD

**Issue by WEBudoGT** [dOpensource/dsiprouter#385]
On a fresh install on Debian 9, I configured FusionPBX as Endpoint and no issues on REGISTER messages using standard WSS port 4443 on dSipRouter.
Incoming call INVITES reach webphone with no issues, but when clicking call button on sipml5 and ctsSip webphones, dSipRouter gets the invite around 10 to 15 seconds after clicked.
I took wireshark traces both on client PC (MacOS) using Chrome and Firefox and on dSipRouter and noticed that no INVITE is processed as soon as the call button is clicked.
Same webphone was tested using direct registration to Asterisk with no delay at all.
Once the INVITE is processed the call session goes normal, being able to put on hold, and end it without delays.

Is this related to dSipRouter or should I check something else?

**Comment by mackhendricks** [comment]
We are not able to reproduce this issue.  Please let us know if this is still an issue
