### ISSUE TITLE
Wildcard Certificates cause MS Teams Connectivity Test to fail

### ISSUE THREAD

**Issue by danry25** [dOpensource/dsiprouter#389]
The MS Teams Connectivity Test throws `Errno -9] Address family for hostname not supported` (pictured below) when properly configured with a working (both inbound and outbound) setup for Direct Routing.

I think this relates to #271. The hostname check is also failing, and for the TLS Certificates check it is [likely failing around here](https://github.com/dOpensource/dsiprouter/blob/master/gui/shared.py#L368) since the TLS library is not handling the wildcard (eg: *.sbc.example.com) well and likely needs to be directed to the particular domain we are checking? (If I am reading this code right...)

![image](https://user-images.githubusercontent.com/1683673/121823598-26cd2180-cc5b-11eb-8a44-91982c102ecc.png)

Operating System: Debian 10.9 (64-bit)
dSIPRouter Version: Master (installed 3 days ago with -all flag)

Note: Opening this issue at @mackhendricks request based on our conversation on Friday, June 11th 2021.

**Comment by mackhendricks** [comment]
I can't reproduce this issue.   I was able to successfully execute the connectivity test.  As shown below.

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/5568984/228012960-111f6f0e-1a23-4ec8-9cf6-1c49a29749ba.png">
