### ISSUE TITLE
Update drouting table when a PBX registers with a username/password

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#39]
Added support for automatically adding the PBX ip, port and transport when it registers.  This means that it automatically gets added to the drouting.gateway table and the table is reloaded in real time

**Comment by jzrlost** [comment]
So does this mean the PBX IP, port number can be dynamic?  Do we still have to add the IP address of the PBX when setup or simply create a username and password for a new PBX?  Then when the server registers with dsiprouter it sets up the IP, port and transport.  Then if the IP address changes on the PBX and it updates it's registration the dsiprouter will update the IP, port and transport?  I can see where that would be very useful.

**Comment by mackhendricks** [comment]
Yes...this is correct..but, have to check if it picks up the transport correctly

**Comment by mackhendricks** [comment]
It looks like the transport is picked up correctly
