### ISSUE TITLE
internal and inbound calls with Kamailo

### ISSUE THREAD

**Issue by thanhdtran88** [dOpensource/dsiprouter#390]
Hi all,

I have just install the new dsiprouter and setup Pass thought PBX to Local Kamailio.
IP Phone (from internet) <=> dSIPRouter <=> Kamailio (registrar server) <=> IVR, voice gateway,...

With outbound calls, it's good except the iphone not hangup when calls end.
This is capture for outbound calls:
![example](https://user-images.githubusercontent.com/85863334/121847469-cef1f180-cd12-11eb-8fd1-f83616bfe6bc.jpg)

With inbound calls and internal calls, this isn't success.
Problem: ipphone register with contact field in my local Kamailio : sip:ext@domain When end calls, inbound calls, internal calls, Kamilio will get the contact in DB with function sip_trace(); 
this is capture for inbound calls ( i think internal calls has the same):
![inbound](https://user-images.githubusercontent.com/85863334/121847651-18dad780-cd13-11eb-800d-dbbb8dc4094d.jpg)

Can you help me solve this issue?

**Comment by thanhdtran88** [comment]
Update:
Softphone has this issue: 3CX ver 6.0.20943.0.
i try another softphone: Zoiper v2.10.12.3-mod. outbound calls can end.

**Comment by mackhendricks** [comment]
We will add the 3CX phone do our testing if another people are using that phone.  I will leave this open to collect votes for this.

**Comment by thanhdtran88** [comment]
I think problem is from my network, with some softphone, the outbound calls can end (zoiper 5, zoiper in android, eyebeam) but with another, it isn't (zoiper 3, zoiper classic). With same PC, same softphone, i try to another network, it's success.

but what about internal call and inbound calls? all softphone of my team (with another network) have same issue.
