### ISSUE TITLE
Teams Documentation

### ISSUE THREAD

**Issue by compuwizz** [dOpensource/dsiprouter#395]
There are some formatting issues with the Teams Documentation at https://dsiprouter.readthedocs.io/en/latest/use-cases.html#microsoft-teams-direct-routing

The code lines are broken and a few of the step lines are condensed.

**Comment by danry25** [comment]
This relates to my pull request #388 that was merged. The formatting does look especially messy on ReadTheDocs compared to how GitHub interpreted what I wrote: https://github.com/dOpensource/dsiprouter/blob/master/docs/source/user/use-cases.rst

**To Fix:**
- Line breaks for steps 4 to 6
- PowerShell code blocks did not format correctly

What steps would you like to see uncondensed? I am game to make another pull request to clean this up!

**Comment by danry25** [comment]
@mackhendricks Mind closing this issue? Never got additional feedback from @compuwizz beyond the changes made in #396, thinking this can be closed.
