### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by showf68** [dOpensource/dsiprouter#397]
error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wnhfw1mh/bjoern_1fbf6f32255542e9a8be5abc058c1612/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wnhfw1mh/bjoern_1fbf6f32255542e9a8be5abc058c1612/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-c_vt5c_3/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6m/bjoern Check the logs for full command output.
ERROR: Service 'dsiprouter' failed to build: The command '/bin/sh -c pip install -r ./gui/requirements.txt' returned a non-zero code: 1
r

**Comment by mackhendricks** [comment]
The docker build hasn't been worked on in a while.  I will let you know when it's ready to go.
