### ISSUE TITLE
Debian 10 Install Fails with "Kamailio install failed"

### ISSUE THREAD

**Issue by SirDMZ** [dOpensource/dsiprouter#398]
Hey dsiprouter,

I was following the https://dsiprouter.readthedocs.io/en/latest/debian_install.html#debian10-install guide on a Fresh Debian 10 install and it fails out when trying to start kamalio.

I think it wants a valid config for its first launch during install, perhaps ignore it failing or give it a valid config just to pass the test?

success
success
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'kamailio'@'localhost'
The Kamailio user already exists in the database - not creating again
ERROR 1133 (28000) at line 1: Can't find any matching row in the user table
kamailio.address: Records: 75  Deleted: 0  Skipped: 0  Warnings: 79
kamailio.dr_gw_lists: Records: 10  Deleted: 0  Skipped: 0  Warnings: 10
kamailio.dr_gateways: Records: 57  Deleted: 0  Skipped: 0  Warnings: 69
kamailio.dr_rules: Records: 1  Deleted: 0  Skipped: 0  Warnings: 2
The Kamailio mpath has been updated to: /usr/lib/x86_64-linux-gnu/kamailio/modules/
Job for kamailio.service failed because the control process exited with error code.
See "systemctl status kamailio.service" and "journalctl -xe" for details.
Kamailio install failed

**Comment by SirDMZ** [comment]
root@tls:/opt/dsiprouter# service kamailio start
Job for kamailio.service failed because the control process exited with error code.
See "systemctl status kamailio.service" and "journalctl -xe" for details.
root@tls:/opt/dsiprouter# journalctl -xe

-- The job identifier is 1269.
Jul 26 15:06:34 tls kamailio[21664]: CRITICAL: <core> [core/cfg.y:3543]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 184
Jul 26 15:06:34 tls kamailio[21664]: CRITICAL: <core> [core/cfg.y:3543]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 184
Jul 26 15:06:34 tls kamailio[21664]: CRITICAL: <core> [core/cfg.y:3546]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 184
Jul 26 15:06:34 tls kamailio[21664]: ERROR: bad config file (3 errors)
Jul 26 15:06:34 tls kamailio[21664]: WARNING: <core> [core/ppcfg.c:223]: pp_ifdef_level_check(): different number of preprocessor directives: 2 more #
Jul 26 15:06:34 tls kamailio[21664]: INFO: <core> [core/sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
Jul 26 15:06:34 tls systemd[1]: kamailio.service: Control process exited, code=exited, status=255/EXCEPTION


Looks like it's stuck on this one.
#!ifdef WITH_SERVERNAT
listen = tls:INTERNAL_IP_ADDR:SIPS_PORT advertise EXTERNAL_FQDN:SIPS_PORT

But I didn't put a -servernat on the end of the ./dsiprouter.sh install -all
so that shouldn't have been enabled?

**Comment by mackhendricks** [comment]
What version was you trying?

**Comment by SirDMZ** [comment]
Hey Mack,

git clone https://github.com/dOpensource/dsiprouter -b master dsiprouter
So the master branch.

**Comment by tmg-cr** [comment]
Having a similar issue on master branch from today. Getting the same error with and without the -servernat option specified. Also Debian 10 fresh.

Install output:

success
success
success
../../Makefile.defs:41: ../../config.mak: No such file or directory
target architecture <x86_64>, host architecture <x86_64>
make[1]: Entering directory `/tmp/kamailio/src'
making config...
make[1]: Leaving directory `/tmp/kamailio/src'
CC (gcc) [M dsiprouter.so]              mod_funcs.o
mod_funcs.c: In function ‘strsplit’:
mod_funcs.c:86:9: warning: unused variable ‘sub_count’ [-Wunused-variable]
  size_t sub_count = 0;    /* number of substrings */
         ^~~~~~~~~
mod_funcs.c: In function ‘validate_license’:
mod_funcs.c:241:17: warning: pointer targets in passing argument 1 of ‘verifyRSA’ differ in signedness [-Wpointer-sign]
  if (!verifyRSA(license, strlen(license), signature, sig_len, licensing_public_key)) {
                 ^~~~~~~
mod_funcs.c:189:5: note: expected ‘const unsigned char *’ but argument is of type ‘char *’
 int verifyRSA(const unsigned char *msg, size_t msglen, unsigned char *sig, size_t siglen, unsigned char *pubkey) {
     ^~~~~~~~~
mod_funcs.c:241:63: warning: pointer targets in passing argument 5 of ‘verifyRSA’ differ in signedness [-Wpointer-sign]
  if (!verifyRSA(license, strlen(license), signature, sig_len, licensing_public_key)) {
                                                               ^~~~~~~~~~~~~~~~~~~~
mod_funcs.c:189:5: note: expected ‘unsigned char *’ but argument is of type ‘char *’
 int verifyRSA(const unsigned char *msg, size_t msglen, unsigned char *sig, size_t siglen, unsigned char *pubkey) {
     ^~~~~~~~~
CC (gcc) [M dsiprouter.so]              mod_dsiprouter.o
In file included from mod_dsiprouter.c:20:0:
../../core/sr_module.h:208:36: error: ‘MODULE_INTERFACE_VER’ undeclared here (not in a function)
  unsigned int module_interface_ver=MODULE_INTERFACE_VER;
                                    ^
mod_dsiprouter.c:27:1: note: in expansion of macro ‘MODULE_VERSION’
 MODULE_VERSION
 ^~~~~~~~~~~~~~
mod_dsiprouter.c:44:8: error: unknown type name ‘cmd_export_t’
 static cmd_export_t cmds[] = {
        ^~~~~~~~~~~~
mod_dsiprouter.c:45:2: warning: braces around scalar initializer
  {"health_check", (cmd_function) mod_health_check, 1,
  ^
mod_dsiprouter.c:45:2: note: (near initialization for ‘cmds[0]’)
mod_dsiprouter.c:45:3: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
  {"health_check", (cmd_function) mod_health_check, 1,
   ^~~~~~~~~~~~~~
mod_dsiprouter.c:45:3: note: (near initialization for ‘cmds[0]’)
mod_dsiprouter.c:45:3: error: initializer element is not computable at load time
mod_dsiprouter.c:45:3: note: (near initialization for ‘cmds[0]’)
mod_dsiprouter.c:45:19: warning: excess elements in scalar initializer
  {"health_check", (cmd_function) mod_health_check, 1,
                   ^
mod_dsiprouter.c:45:19: note: (near initialization for ‘cmds[0]’)
mod_dsiprouter.c:45:52: warning: excess elements in scalar initializer
  {"health_check", (cmd_function) mod_health_check, 1,
                                                    ^
mod_dsiprouter.c:45:52: note: (near initialization for ‘cmds[0]’)
mod_dsiprouter.c:46:2: warning: excess elements in scalar initializer
  fixup_get_params, fixup_get_params_free, ANY_ROUTE},
  ^~~~~~~~~~~~~~~~
mod_dsiprouter.c:46:2: note: (near initialization for ‘cmds[0]’)
mod_dsiprouter.c:46:20: warning: excess elements in scalar initializer
  fixup_get_params, fixup_get_params_free, ANY_ROUTE},
                    ^~~~~~~~~~~~~~~~~~~~~
mod_dsiprouter.c:46:20: note: (near initialization for ‘cmds[0]’)
In file included from ../../core/sr_module.h:38:0,
                 from mod_dsiprouter.c:20:
../../core/route.h:59:23: warning: excess elements in scalar initializer
 #define ANY_ROUTE     (0xFFFFFFFF)
                       ^
mod_dsiprouter.c:46:43: note: in expansion of macro ‘ANY_ROUTE’
  fixup_get_params, fixup_get_params_free, ANY_ROUTE},
                                           ^~~~~~~~~
../../core/route.h:59:23: note: (near initialization for ‘cmds[0]’)
 #define ANY_ROUTE     (0xFFFFFFFF)
                       ^
mod_dsiprouter.c:46:43: note: in expansion of macro ‘ANY_ROUTE’
  fixup_get_params, fixup_get_params_free, ANY_ROUTE},
                                           ^~~~~~~~~
mod_dsiprouter.c:47:2: warning: braces around scalar initializer
  {0,0,                                             0,0,0}
  ^
mod_dsiprouter.c:47:2: note: (near initialization for ‘cmds[1]’)
mod_dsiprouter.c:47:5: warning: excess elements in scalar initializer
  {0,0,                                             0,0,0}
     ^
mod_dsiprouter.c:47:5: note: (near initialization for ‘cmds[1]’)
mod_dsiprouter.c:47:52: warning: excess elements in scalar initializer
  {0,0,                                             0,0,0}
                                                    ^
mod_dsiprouter.c:47:52: note: (near initialization for ‘cmds[1]’)
mod_dsiprouter.c:47:54: warning: excess elements in scalar initializer
  {0,0,                                             0,0,0}
                                                      ^
mod_dsiprouter.c:47:54: note: (near initialization for ‘cmds[1]’)
mod_dsiprouter.c:47:56: warning: excess elements in scalar initializer
  {0,0,                                             0,0,0}
                                                        ^
mod_dsiprouter.c:47:56: note: (near initialization for ‘cmds[1]’)
mod_dsiprouter.c:66:1: error: unknown type name ‘module_exports_t’; did you mean ‘nn_export_t’?
 module_exports_t exports = {
 ^~~~~~~~~~~~~~~~
 nn_export_t
mod_dsiprouter.c:67:3: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
   "dsiprouter", /* module name */
   ^~~~~~~~~~~~
mod_dsiprouter.c:67:3: note: (near initialization for ‘exports’)
mod_dsiprouter.c:67:3: error: initializer element is not computable at load time
mod_dsiprouter.c:67:3: note: (near initialization for ‘exports’)
In file included from mod_dsiprouter.c:20:0:
../../core/sr_module.h:195:25: warning: excess elements in scalar initializer
 #define DEFAULT_DLFLAGS 0 /**< value that signals to module loader to
                         ^
mod_dsiprouter.c:68:3: note: in expansion of macro ‘DEFAULT_DLFLAGS’
   DEFAULT_DLFLAGS,  /* dlopen flags */
   ^~~~~~~~~~~~~~~
../../core/sr_module.h:195:25: note: (near initialization for ‘exports’)
 #define DEFAULT_DLFLAGS 0 /**< value that signals to module loader to
                         ^
mod_dsiprouter.c:68:3: note: in expansion of macro ‘DEFAULT_DLFLAGS’
   DEFAULT_DLFLAGS,  /* dlopen flags */
   ^~~~~~~~~~~~~~~
mod_dsiprouter.c:69:3: warning: excess elements in scalar initializer
   cmds,         /* exported functions */
   ^~~~
mod_dsiprouter.c:69:3: note: (near initialization for ‘exports’)
mod_dsiprouter.c:70:3: warning: excess elements in scalar initializer
   params,       /* exported parameters */
   ^~~~~~
mod_dsiprouter.c:70:3: note: (near initialization for ‘exports’)
mod_dsiprouter.c:71:3: warning: excess elements in scalar initializer
   0,     /* exported rpc functions */
   ^
mod_dsiprouter.c:71:3: note: (near initialization for ‘exports’)
mod_dsiprouter.c:72:3: warning: excess elements in scalar initializer
   0,         /* exported pseudo-variables */
   ^
mod_dsiprouter.c:72:3: note: (near initialization for ‘exports’)
mod_dsiprouter.c:73:3: warning: excess elements in scalar initializer
   0,        /* exported response function */
   ^
mod_dsiprouter.c:73:3: note: (near initialization for ‘exports’)
mod_dsiprouter.c:74:3: warning: excess elements in scalar initializer
   mod_init,         /* exported initialization function */
   ^~~~~~~~
mod_dsiprouter.c:74:3: note: (near initialization for ‘exports’)
mod_dsiprouter.c:75:3: warning: excess elements in scalar initializer
   mod_child_init,  /* exported child initialization function */
   ^~~~~~~~~~~~~~
mod_dsiprouter.c:75:3: note: (near initialization for ‘exports’)
mod_dsiprouter.c:76:3: warning: excess elements in scalar initializer
   mod_destroy,     /* exported destroy function */
   ^~~~~~~~~~~
mod_dsiprouter.c:76:3: note: (near initialization for ‘exports’)
make: *** [mod_dsiprouter.o] Error 1
kamailio install failed

**Comment by mackhendricks** [comment]
This should be resolved when 0.643 is released.  Please reopen if that's not the case
