### ISSUE TITLE
"Your Operating System Version is not supported yet"  in RedHat 8

### ISSUE THREAD

**Issue by franquec** [dOpensource/dsiprouter#399]
cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.4 (Ootpa)

Executing 
yum update -y && yum install -y git && cd /opt && git clone https://github.com/dOpensource/dsiprouter.git -b v0.641 && cd dsiprouter && ./dsiprouter.sh install -all

Error: "Your Operating System Version is not supported yet"

**Comment by mackhendricks** [comment]
We don't perform testing on Red Hat 8.   But, please let us know if you would like to test it out for us and we can help set you up with our test suite.
