### ISSUE TITLE
dSIP-Router not sending bye

### ISSUE THREAD

**Issue by cjberghuis** [dOpensource/dsiprouter#408]
dSIP Router is not passing the "BYE" from the PBX to the carrier.
dSIPRouter 0.642 and the PBX is the latest FreePBX 15 using PJSIP
This screenshot is after the IP phone is hung up. Cell phone used to make the test call never hangs up.
![Capture1](https://user-images.githubusercontent.com/94921862/143066789-814e9051-7973-4a14-87d4-168a0b0f84da.JPG)
Screenshot after cell phone is hung up.
![Capture2](https://user-images.githubusercontent.com/94921862/143067820-9b142f9d-b8b8-4456-bed9-45fe7977c186.JPG)

**Comment by mackhendricks** [comment]
Please provide a PCAP so that we can review
