### ISSUE TITLE
dsiprouter changes nameserver on boot

### ISSUE THREAD

**Issue by ehrenmann1977** [dOpensource/dsiprouter#409]
i failed to install the dsiprouter but as a result each time the namesever is misconfigured to 127.0.0.53 and I have to fix it manually, I don't know where did you make changes to do it.

please help.

thank you

**Comment by mackhendricks** [comment]
What OS and verison ?  Where is it being installed on?  Cloud, VM, Physical Hardware.

**Comment by ehrenmann1977** [comment]
linux ubuntu 20.04, installed on physical hdd local

**Comment by ehrenmann1977** [comment]
Any dolugion is appreciated

**Comment by ehrenmann1977** [comment]
i found the solution it is a bug in linux
https://askubuntu.com/questions/973017/wrong-nameserver-set-by-resolvconf-and-networkmanager
