### ISSUE TITLE
can not route calls

### ISSUE THREAD

**Issue by mostafafayyaz** [dOpensource/dsiprouter#414]
hello
i have some asterisk that does not has static ip . i have a vos3000 softswitch.
my end is sending calls from vos3000 to asterisk.
i register asterisk on vos3000 via dSipRouter , but when i send calls from vos3000 to asterisk, dSipRouter reject calls via 404 code
this is the config of asterisk :

`
[general]
register => 5001:123456@voiptalk/5001
allow=ulaw,alaw

[voiptalk]
type=friend
username=5001
secret=123456
dtmfmode=rfc2833
host=myvosip
context=incoming-from-vos
outboundproxy=mydsiprouterip
port=5065
qualify=yes
`

**Comment by mackhendricks** [comment]
It's best to use our User Forums for this type of question: https://groups.google.com/forum/#!forum/dsiprouter

But, just ensure the SIP Domain is defined as voiptalk within dSIPRouter.  The default SIP Domain is sip.dsiprouter.org

**Comment by mackhendricks** [comment]
Closing this issue since we haven't got a response on this
