### ISSUE TITLE
RTPEngine doesn't start after install - you have to reboot

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#42]
After an install of dsiprouter on Debian Stretch 9.4 with the -rtpengine option you have to restart the VM for the rtpengine to start using systemd.

**Comment by devopsec** [comment]
We fixed this for centos may need to add similar for debian.
The fix on centos was here: https://github.com/dOpensource/dsiprouter/blob/master/dsiprouter.sh#L619
