### ISSUE TITLE
Microsoft Teams Silent Ringback - 183 Session Progress (SDP)

### ISSUE THREAD

**Issue by danry25** [dOpensource/dsiprouter#421]
**Describe the problem**
Incoming callers from Flowroute and BulkVS hear ringback until the call progresses to 183 Session Progress (SDP), at which point Microsoft sends us a 183 Session Progress (SDP) which we forward to the carrier, and the caller hears silence as Microsoft sends a silent audio stream.

[It appears Microsoft expects the SBC to add ringback to the audio stream.](https://answers.microsoft.com/en-us/msteams/forum/all/no-ringback-tone-on-call-transfer-using-teams-with/2b176cf8-c7cb-4850-879e-f6be6b1bd719)

**Suggested Solution**
Drop the 183 Session Progress (SDP) message rather than sending it onto the SIP carrier as dropping this seems to have no ill effects, and the ringback now plays until a Teams softphone answers or voicemail is reached.

I have tested that the code below solves this problem by adding it to [line 2622 of the kamailio config](https://github.com/dOpensource/dsiprouter/blob/master/kamailio/kamailio_dsiprouter.cfg#L2622) on an instance of dSIPRouter v0.642.
```
if (t_check_status("183") && isbflagset(FLB_DST_MSTEAMS)) {
drop();
}
```

**System Information**
dSIPRouter Versions affected: v0.63 and v0.642
Microsoft Teams clients tested: Android and iOS

**Other Information**
The 183 Session Progress (SDP) is sent when the Teams softphone starts ringing, whereas the 180 ringing status is sent as soon as Teams receives the incoming call
![Screenshot from 2022-02-22 13-00-18](https://user-images.githubusercontent.com/1683673/155270889-5d9cd901-204c-42ba-8ea4-9f5aa95c958f.png)
.

**Comment by mackhendricks** [comment]
This issue has been committed into master

**Comment by danry25** [comment]
@mackhendricks I took a look at https://github.com/dOpensource/dsiprouter/blob/master/kamailio/kamailio_dsiprouter.cfg but it appears to match the problematic Kamailio config I tried prior to opening this issue.

How did you resolve it? The only other approach I could think of was having rtpengine mix in ringback to the silent audio stream that Microsoft Teams sends us...

**Comment by mackhendricks** [comment]
Let me confirm the commit.  I might of screwed up

Mack Hendricks
