### ISSUE TITLE
SIP register rewrite header

### ISSUE THREAD

**Issue by pergolafabio** [dOpensource/dsiprouter#428]
Hi
i have an Asteriks up and running for local use... in Asteriks i have a trunk setup + some extensions, but it doesnt work on asteriks, because i need to inject an custom body in the register...

Can i use Dsiprouter for this?

I need to inject this custom body

thnx for the advice

```
REGISTER sip:10000000002@192.168.0.71:5065 SIP/2.0
Via: SIP/2.0/UDP 192.168.0.72:5060;rport;branch=z9hG4bK206682350
From: Room 2 <sip:10000000002@192.168.0.72>;tag=588337480
To: Room 2 <sip:10000000002@192.168.0.72>
Call-ID: 1549082696
CSeq: 1 REGISTER
Contact: <sip:10000000002@192.168.0.72:5060;line=39b237d1561ac46>
Content-Type: text/xml
Max-Forwards: 70
User-Agent: eXosip/3.6.0
Expires: 900
Content-Length:   165

<regXML>
<version>V2.0.0</version>
<regDevName>Room 2</regDevName>
<regDevSerial>Q123456</regDevSerial>
<regDevMacAddr>1234567890</regDevMacAddr>
</regXML>
```

**Comment by mackhendricks** [comment]
This hasn't been tested.  But, dSIPRouter is just a proxy.  So, it should allow you.  Please use our mailing list for this type of question, which can be found here:  https://groups.google.com/g/dSIPRouter
