### ISSUE TITLE
Outbound calls terminate at 32 seconds

### ISSUE THREAD

**Issue by tuxpowered** [dOpensource/dsiprouter#433]
First of all, thank you for making dSIPRouter an OSS project! I have been wanting to learn Kamailio for a long time and while looking at some past asterion videos I came across your project. 

Forgive me for being very verbose here, but I am stumped.
I have a functional PBX. (A Digium Switchvox) for our small office. Works fine, connected directly to the provider.

```
switchvox --> pfsense(nated 1:1) --> Flowroute
```

## Public IP install of dSIPRouter
I first installed dSIPRouter on a DO node. Added a DID mapping to the endpoint and calls pass inbound.
```
Flowroute --> dSIPRouter --> pfsense --> switchvox
```

## Internally installed dSIPRouter
However outbound failed.
```
switchox --> pfSense(natted 1:1) --> dSIPRouter --> Flowroute (rejected)
```

The error from Flowroute says that the TechPrefix and IP are not in ACL. (However the IP is in the ACL, as the call was passed in to the said IP, and the techprefix is included.

My Intent was to have dSIPRouter stand up in front of 2 internal PBX systems, so I decided to install a VM internally and try again.
```
swichvox --> pfSense(Natted 1:1) --> dSIPRouter --> Flowroute (fiales at 32s)
```

Okay so same endpoint config, same pbx rule call sets up and makes an outbound call, but terminates at 32 seconds.

So the one thing I noticed looking at the SIP packets, (and admittedly I am not the best), is that when calls route thru dSIPRouter, the From: header is different.

That is a call from dSIPRouter has 
```
From: <sip:92834987@dsip1.domain.com>;tag=1061faad-1b74-4b81-8a5f-2ddbb93670ae
```
while a call that success to flowroute (the direct working setup)
```
From: <sip:92834987@flowroute.ip.addr>;tag=1061faad-1b74-4b81-8a5f-2ddbb93670ae
```

I am wondering if the failure is because my outbound calls do not have the correct From Header when leaving Flowroute?

### On the public DO install. 
`./dsiprouter.sh install -kam -dsip` I did not install rtpengine as on the public side I did not believe it should be handling any media. Simply SIP processing.

* Endpoint Groups:
  * Added friendly name 
  * Added Endpoint hostname
  * Saved
* Domains
  * Added Friendly name
  * Set to Pass Thru to PBX
  * Set endpoint ID to created endpoint.
  * Saved
 * Inbound Mappings
   * Set inbound DID number
   * Selected endpoint from dropdown list
   * No forwards set.
   * Saved
 * Outbound Routes
   * Changed default (rule id 0) carrier group to Flowroute.
   * Added new route Included techprefix in the To Prefix. XXXXXX*
   * Selected Flowroute on carrier group.
   * saved.

_Should be noted that the failure happens with or without the additional route with the techprefix. I set that to test if it would actually match which it did. (tested by originally sending it to a different provider)_

### Setup on internal dSIPRouter
` ./dsiprouter.sh install -all -servernat` # Because the dSIPRouter is behind nat, and the PBX is behind NAT, I figured I might need to handle media and servernat.

It should be noted that the PBX's are on dedicated VLAN's and the dSIPRouter is on its own VLAN as well.
All other entry points were configured the same as the DO install.

## End Goal
The main reason I started looking at dSIPRouter is I saw support for STIR/SHAKEN, and that the project does is not trying to be everything under the sun. 

```

 ┌──────────────────────────────────────────────────────────────────┐
 │                                                                  │
 │                                            Desired Internal      │
 │     ┌────────┐                 ┌─────┐          Setup            │
 │     │        │                 │     │                           │
 │     │  PBX1  ├─────VLAN100─────┤     │                           │
 │     │        │                 │     │                           │
 │     └────────┘                 │     │                           │
 │                                │  p  │                           │
 │     ┌────────┐                 │  f  │                           │
 │     │        │                 │  S  │                           │
 │     │  PBX2  ├─────VLAN101─────┤  e  │       ┌────────────────┐  │
 │     │        │                 │  n  │       │                │  │
 │     └────────┘                 │  c  ├───────┼──SIP Provider  │  │
 │                                │  e  │       │                │  │
 │     ┌────────┐                 │     │       └────────────────┘  │
 │     │        │                 │     │                           │
 │     │  PBX3  ├─────VLAN102─────┤     │                           │
 │     │        │                 │     │                           │
 │     └────────┘                 │     │                           │
 │                                │     │                           │
 │                                │     │                           │
 │                                │     │                           │
 │            ┌───────VLAN300──┬──┤     │                           │
 │            │                │  │     │                           │
 │            │                │  └─────┘                           │
 │            │                │                 ┌──────────┐       │
 │    ┌───────┴┐       ┌───────┴┐                │          │       │
 │    │        │       │        ├───────────────►│  Trans   │       │
 │    │  dSIP1 ├───HA──┤  dSIP2 │                │   Nexus  │       │
 │    │        │       │        │◄───────────────┤          │       │
 │    └────────┘       └────────┘                └──────────┘       │
 │                                                                  │
 └──────────────────────────────────────────────────────────────────┘

```

Or if using public setup
```
 ┌───────────────────────────────────────────────────────────────────────────────────────────┐
 │                                                                                           │
 │                                            Desired External                               │
 │     ┌────────┐                 ┌─────┐          Setup                                     │
 │     │        │                 │     │                                ┌────────────────┐  │
 │     │  PBX1  ├─────VLAN100─────┤     │                                │                │  │
 │     │        │                 │     │                                │  SIP Provider  │  │
 │     └────────┘                 │     │                                │                │  │
 │                                │  p  │                                └────────────────┘  │
 │     ┌────────┐                 │  f  │                                                    │
 │     │        │                 │  S  │                                    ┌─────────┐     │
 │     │  PBX2  ├─────VLAN101─────┤  e  │        ┌────────────┐  ┌───────────┤  dSIP1  │     │
 │     │        │                 │  n  │        │            │  │           └──────┬──┘     │
 │     └────────┘                 │  c  ├────────┤  Internet  │  │                  │        │
 │                                │  e  │        │            ├──┤                  HA       │
 │     ┌────────┐                 │     │        └────────────┘  │                  │        │
 │     │        │                 │     │                        │           ┌──────┴──┐     │
 │     │  PBX3  ├─────VLAN102─────┤     │                        └───────────┤  dSIP2  │     │
 │     │        │                 │     │                                    └──┬────▲─┘     │
 │     └────────┘                 │     │                                       │    │       │
 │                                │     │                                       │    │       │
 │                                └─────┘                                    ┌──▼────┴──┐    │
 │                                                                           │          │    │
 │                                                                           │  Trans   │    │
 │                                                                           │   Nexus  │    │
 │                                                                           │          │    │
 │                                                                           └──────────┘    │
 │                                                                                           │
 └───────────────────────────────────────────────────────────────────────────────────────────┘
```

I am pretty sure I am just missing a few small configuration tweaks that are missing from the documentation. 
I am happy to update the documentation with the missing details, if I can figure out whats going on or if some guidance from anyone can be had.

Thank you in advance, will keep plugging at it.

**Comment by mackhendricks** [comment]
I was able to get a call over 30 seconds using Flowroute.  Notice, that' I'm using a totally different From domain

![image](https://user-images.githubusercontent.com/5568984/165928036-f108c694-f170-4638-ad70-4174520bd94f.png)

**Comment by tuxpowered** [comment]
Thank you @mackhendricks , I feel like an ID10T. The message was correct the ACL was wrong. 
It appears I only added it for outbound IP's (to receive calls) but not under the endpoints for sending calls. 

The publicly hosted dSIP on DO is working now

> Note to others... triple check your inbound _and_ outbound ACL's with your provider!
 

I still have not figured out how to properly get an internally natted setup working. I will spend some more time this week trying again.

Would it be possible, to have a publicly hosted dSIP in HA with one that is Natted?

My reason for wanting a natted version is to conserve IP addresses and be able to block some bad acting softphones. (Blocked by user-agent).
