### ISSUE TITLE
Support Peeringhub.io for SHAKEN/STIR 

### ISSUE THREAD

**Issue by compuwizz** [dOpensource/dsiprouter#436]
Now that Transnexus is supported for adding the S/S headers, would it be possible to add peeringhub.io? They are an approved Certificate Authority. I'll gather up some technical details from them to see if the signaling is close enough to what is already implemented.

**Comment by mackhendricks** [comment]
Hey Maurice (@cruzer45), can you look at the Feasibility of adding the Peeringhub.io Authenticate/Verification service to dSIPRouter.  It looks very similar to Transnexus.

**Comment by cruzer45** [comment]
Integration with Peeringhub.io was successful.
