### ISSUE TITLE
Upgrade to current release v0.644 does not work.

### ISSUE THREAD

**Issue by tuxpowered** [dOpensource/dsiprouter#441]
Tried to upgrade on test VM from 0.643 to current master with failure every time.

`./dsiprouter.sh upgrade -rel "master"` fails

Tried to update the repo first. 
```
cd /opt/dsiprouter
git checkout master
./dsiprouter.sh upgrade -rel "master"
```
Fails. 

```
root@dsip-dev:/opt/dsiprouter# ./dsiprouter.sh upgrade --release=master
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/etc/dsiprouter/gui/settings.py", line 41, in <module>
    VERSION = master
NameError: name 'master' is not defined
```

Looking for how to upgrade a production 0.643 to 0.644 (ideally on both Debian 10 and 11)

**Comment by devopsec** [comment]
The `upgrade` dsiprouter command needs some TLC...

Currently it does not:
- backup, migrate, and restore the DB
- reset settings.py or kamailo.cfg to previous settings
- handle `VERSION` properly, as you've seen

The version setting simply needs quoted for that fix:
```
setConfigAttrib 'VERSION' "$UPGRADE_RELEASE" ${DSIP_CONFIG_FILE}
```

should be:
```
setConfigAttrib 'VERSION' "$UPGRADE_RELEASE" ${DSIP_CONFIG_FILE} -q
```

The other issues with that command are harder to fix and would require some time.

Currently the recommended upgrade strategy is:
1. backup `kamailio` DB from mysql
2. backup `/etc/dsiprouter` dir
3. uninstall dsiprouter `dsiprouter uninstall -all`
4. clone new version of the repo
5. install dsiprouter
6. replace certs, uuid file, license file, and dsip private key with backed up ones
7. manually merge backed up settings in `settings.py`, `kamailio.cfg`, and `kamailio` DB

**Comment by tuxpowered** [comment]
@devopsec do you have any specifics to the  "manually merge" portion? 
`settings.py` I have already identified several new fields. I know there is a different version of `kamailio.cfg` and related files, but what would need to be 'merged' back in from the old version?

What would need to be manually merged on the database, your implication is that some manual work is required, beyond just a database restore. I am assuming that sqlalchemy alembic migration process doesn't work or is not implemented.

If you have some references to the database migrations required, and the kamailio modifications, I can likely either provide an update script that would properly tick off the boxes so that migrations can be processed going forward. 

it would be advantageous if all future upgrades follow a predefined process w/ verifiable checks and ballances.

**Comment by devopsec** [comment]
Will tackle this for v0.70 release
The DB backup/restore has to be resilient to minor schema changes.
It should also detect when it can't merge the data and warn users they need to manually merge their previous DB data.

**Comment by devopsec** [comment]
@tuxpowered Automatic upgrades were rolled out in v0.72.  
Unfortunately we had to start somewhere and only v0.70 -> v0.72 is supported.  
We have manual upgrading instructions in the documentation.  
Reference [Upgrading dSIPRouter](https://dsiprouter.readthedocs.io/en/latest/upgrade.html) for more info.
