### ISSUE TITLE
SERVERNAT Bug

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#445]
The SERVERNAT logic is executed early in the request processing cycle.   But, it should be checked again once a decision has been made to route the call because it might be routed to a local server on the same subnet versus a server on a remote subnet.  

Currently, the wrong record route is set if the request is being routed to a local SIP sever. 

I will fix this in master since this is a critical bug, but mark it for 0.70

**Comment by devopsec** [comment]
resolved in  89ab6283a42c62d625f9a0cf4d48fe76c8c0049a
