### ISSUE TITLE
JSSIP WebRTC Client Causes 500 Error 

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#446]

**Comment by yuriasa** [comment]
Hi Mack,

I have the same error when using jsSIP to call outbound and don't hang up when client terminate "SIP/2.0 478 Unresolvable destination (478/SL)"

Thanks you.

![Screen Shot 2022-07-27 at 10 09 07](https://user-images.githubusercontent.com/65381457/181153077-e9cb1ebc-280e-471e-b539-9c645c3ec592.png)
![Screen Shot 2022-07-26 at 11 34 00](https://user-images.githubusercontent.com/65381457/181153108-ec9228d1-2519-4f2e-a62a-507fc6cd1e63.png)

**Comment by mackhendricks** [comment]
@yuriasa  What version of jSSIP are you using?

**Comment by devopsec** [comment]
@cruzer45 was unable to replicate this issue using the following environment:
- jssip version 3.9.1
- freepbx version 16

Pushing this issue to v0.71 patch release
