### ISSUE TITLE
Kamailio Reload Error on Fresh install of dSIPRouter

### ISSUE THREAD

**Issue by cruzer45** [dOpensource/dsiprouter#459]
On a fresh install of dSIPRouter, clicking the Reload Kamailio button on the GUI results in the following error logs.

`Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: tls [tls_domain.c:601]: load_ca_list(): TLSc<default>: Unable to load CA list file '/etc/dsiprouter/certs/ca-list.pem' dir '/etc/dsiprouter/certs/ca'
Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: tls [tls_util.h:42]: tls_err_ret(): load_ca_list:error:0D082041:asn1 encoding routines:ASN1_STRING_type_new:malloc failure
Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: tls [tls_util.h:42]: tls_err_ret(): load_ca_list:error:0D079041:asn1 encoding routines:asn1_item_embed_new:malloc failure
Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: tls [tls_util.h:42]: tls_err_ret(): load_ca_list:error:0D079041:asn1 encoding routines:asn1_item_embed_new:malloc failure
Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: tls [tls_util.h:42]: tls_err_ret(): load_ca_list:error:0B09C041:x509 certificate routines:x509_name_canon:malloc failure
Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: tls [tls_util.h:42]: tls_err_ret(): load_ca_list:error:0D09E03A:asn1 encoding routines:x509_name_ex_d2i:nested asn1 error
Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: tls [tls_util.h:42]: tls_err_ret(): load_ca_list:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error
Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: tls [tls_util.h:42]: tls_err_ret(): load_ca_list:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error
Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: tls [tls_util.h:42]: tls_err_ret(): load_ca_list:error:0907400D:PEM routines:PEM_X509_INFO_read_bio:ASN1 lib
Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: tls [tls_util.h:42]: tls_err_ret(): load_ca_list:error:0B084009:x509 certificate routines:X509_load_cert_crl_file:PEM lib
Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: <core> [core/parser/parse_fline.c:271]: parse_first_line(): parse_first_line: bad message (offset: 18)
Sep 29 12:52:49 mrogers-signalwire-test-dsip-1 /usr/sbin/kamailio[32185]: ERROR: <core> [core/parser/msg_parser.c:747]: parse_msg(): ERROR: parse_msg: message=<HTTP/1.1 500 Error while fixing TLS configuration (consult server log)
`

**Comment by devopsec** [comment]
patched in c1e0be12cf158786064bc1f1d1c4bdf3db2159f3 and b3a9b851f5b0c095eede8d5913f102b4f62b04f0
