### ISSUE TITLE
Timeout install version 0.643

### ISSUE THREAD

**Issue by kietcaodev** [dOpensource/dsiprouter#463]
hi all,
i install dsiprouter, but link die and it not install
curl -s -f --connect-timeout 2 http://169.254.169.254/latest/dynamic/instance-identity/
![image](https://user-images.githubusercontent.com/71913797/199891022-e1f772e6-9a3b-4152-84b4-38e49af4b830.png)

**Comment by cruzer45** [comment]
Hi @kietcaodev  
Is this the same install as Issue #467 ?

**Comment by devopsec** [comment]
deplicate of #467, no OS info to work with, no response from OP, closing..
