### ISSUE TITLE
Waiting longtime when install dsiprouter 0.643

### ISSUE THREAD

**Issue by kietcaodev** [dOpensource/dsiprouter#467]
Hi support,
i install dsiprouter and kamailio with shell script on centos 7
but script run to "System repositories configured successfully" and waiting reponse long time for ~60min.
any help me, appreciate. Many thanks
######
cd /opt
git clone https://github.com/dOpensource/dsiprouter.git -b v0.643
cd /opt/dsiprouter
./dsiprouter.sh install -all
######

![image](https://user-images.githubusercontent.com/71913797/201623681-24ed8632-b4aa-426c-824f-4f63bcd25610.png)

**Comment by cruzer45** [comment]
Hi @kietcaodev ,

Does this issue still occur in a recent version of dSIPRouter installing on the latest version of CentOS?  
We typically try to support the latest stable version of the OS.

**Comment by mackhendricks** [comment]
Closing due to no reply
