### ISSUE TITLE
Server Issue (Detailed Information: list index out of range)

### ISSUE THREAD

**Issue by OsvaldoSierra** [dOpensource/dsiprouter#468]
Hi DSIProuter team! I have the next issue trying to open an endpoint from the Endpoint list. I'll share PS to show the step by step:

1) Enter to "Endpoints group"
2) Just click on "Troncal remoto" (ID=13)
![image](https://user-images.githubusercontent.com/117942475/202469880-8fc9a602-e646-4467-9de6-fa79646abbc3.png)

After click I got this error message:
![image](https://user-images.githubusercontent.com/117942475/202470031-2a7d59de-34fe-42d9-bb6e-70667d68360d.png)

Extra data: If i click the other Endpoint (ID=12) I have no problem, that Endpoint opens well.

Thank you in advance.

**Comment by mackhendricks** [comment]
@devopsec Can you please look into this.

**Comment by devopsec** [comment]
@OsvaldoSierra can you provide the following:  
- os info
- dsiprouter version
- cloud environment if applicable
- steps to reproduce your issue

For the last one in particular; what state was the system in before this issue occurred.

**Comment by OsvaldoSierra** [comment]
Hi guys. Here the info:

1) OS Info:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

2) DSIPRouter version: 0.70

3) Cloud enviroment: Huawei cloud (Hiperstack)

4) Just click on "Endpoint Groups" (Left menu) => Click on a Endpoint called "TroncalRemoto" => Next the error I've shown on my PS.

**Comment by devopsec** [comment]
@OsvaldoSierra please attach `dsiprouter.log` from when this issue occurs

**Comment by OsvaldoSierra** [comment]
[dsiprouter.log](https://github.com/dOpensource/dsiprouter/files/10248203/dsiprouter.log)

Hi team. Here I'm adding the dsiprouter.log. I've replied the error after `dsiprouter restart -debug` command. The testing time was at:

root@dsiprouter-prueba-osvaldo:~# date
Sat 17 Dec 2022 02:28:46 AM CST

**Comment by devopsec** [comment]
Issue occurs due to no `weight` validation in endpoint group api checks.  
This should not happen in normal use as the api puts in a default value.  

Below is a workaround that will allow an the `attrs` column of the `dispatcher` table to be empty:

```
diff --git a/gui/modules/api/api_routes.py b/gui/modules/api/api_routes.py
index 68f8d00..aea2c2b 100644
--- a/gui/modules/api/api_routes.py
+++ b/gui/modules/api/api_routes.py
@@ -862,9 +862,12 @@ def getEndpointGroup(gwgroupid):
             dispatcher = db.query(Dispatcher).filter(Dispatcher.setid == gwgroupid)
             if dispatcher:
                 weightList = {}
-                for item in dispatcher:
-                    weight = item.attrs.split('=')[1]
-                    weightList[item.destination[4:]] = weight
+                try:
+                    for item in dispatcher:
+                        weight = item.attrs.split('=')[1]
+                        weightList[item.destination[4:]] = weight
+                except IndexError:
+                    pass
 
             for endpoint in endpoints:
                 ep = {}
```

**Comment by devopsec** [comment]
Will commit a better solution in v0.72, the workaround is only temporary
