### ISSUE TITLE
Debian 10: DNSmasq Problem - MySQL install failed

### ISSUE THREAD

**Issue by pete1019** [dOpensource/dsiprouter#469]
Debian 10.
apt-get update -y && apt-get install -y git && cd /opt && git clone https://github.com/dOpensource/dsiprouter.git && cd dsiprouter && ./dsiprouter.sh install -all

Right after DNSmasq installation there is no internet connection anymore. And this happens:

E: Aborting install.
Failed to enable unit: Unit file mariadb.service does not exist.
Failed to restart mariadb.service: Unit mariadb.service not found.
MySQL install failed

change nameserver in /etc/resolv.conf from 127.0.0.1 to 1.1.1.1 fixes that.
I have to run ./dsiprouter.sh install -all again and it keeps installing.

**Comment by mackhendricks** [comment]
Please use our slack channel for this: https://join.slack.com/t/dsiproutercommunity/shared_invite/zt-1dtqvpyck-H9k~DYgJJ2XIFgh_rWqdPA
