### ISSUE TITLE
Internal Server Error when saving PBX's when using Google Cloud SQL Service

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#47]
I receive this error when the database for Kamailio and dSIPRouter is Google Cloud SQL Service:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

This seems to be due to the value of the strip field being an empty string.  In comparison, MySQL and MariaDB doesn't care if the string is empty - it  just puts in a default integer value of 0

**Comment by devopsec** [comment]
Is this a use case we need to consider at this point in time?
Right now our only official support is for mysql
