### ISSUE TITLE
Allow Static Networking

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#473]
Currently these settings are dynamically set, we want to have the option to override these.  
Possibly `--static-networking` flag on install

**Comment by devopsec** [comment]
This requires options on install that allow setting the network configs.  
*Note* this feature would really be for advanced users that have very specific network requirements.

**Comment by devopsec** [comment]
Will add this in v0.72  
Changes to be made:
- add `--networking=<mode>` install flag
- add `NETWORK_MODE` variable to `settings.py`
- update startup services to ignore dynamic updates when network mode is `static`
-
