### ISSUE TITLE
Fresh Install it's not displaying PBX's and Endpoints

### ISSUE THREAD

**Issue by razvanzeces** [dOpensource/dsiprouter#475]
Hello,

Just did a fresh install on my Debian 10 machine, and the PBX's and Endpoints it's not showing up as in the documentation:

![2022-12-10 00_21_44-Window](https://user-images.githubusercontent.com/56639628/206805199-9a2efff8-6bb4-4d19-80b9-fef7d564c90b.png)

Is there something that I'm not doing right? 

Also, I'm using Kamailo as the SIP Server.

Thank you

**Comment by cruzer45** [comment]
Hi @razvanzeces , Thank you for submitting this issue.
This looks more like a configuration problem than a true bug in the software.

Perhaps you can reach out to the community slack at the URL below:
dsiproutercommunity.slack.com

We also offer paid support if you prefer. You can learn more about that at the URL below:
https://dopensource.com/product-category/prepaid-support/

Cheers, Maurice
