### ISSUE TITLE
Multi-homed Support...

### ISSUE THREAD

**Issue by jzrlost** [dOpensource/dsiprouter#48]
We tried dsiprouter behind a NAT and that didn't work.  Even after 10 hours of support we could never get it to work good and solid.  That being said we decided to ditch the NAT and run dsiprouter with a public IP address.  Now we are having trouble getting it to work using 2 network cards, a public interface and a private interface.  On  the public side we have the carriers using IP authentication so that's good.  On the private side we have the PBX's and phones (phones register with the internal PBX).  We have tried 2-3 times with a clean install of Debian 9 to get this working.  All we need is for dsiprouter to pass the traffic in from the carrier (public ip/external interface to private/internal interface) to the correct PBX per DID.  Then we need it to do the opposite direction for outgoing calls.  Are trying to do something it's not designed to do?

**Comment by jzrlost** [comment]
I know we are one of "those" pain in butt always want what it wasn't designed to do customers.  LOL  We use VoIP Innovations primarily but yes, they only do the signaling and pass the RTP to other carriers.  Maybe that is where the problem arises.  We did figure out that incoming worked almost everytime, it was the outgoing that was hit or miss.  Hopefully we can get this going with a ticket so we can move past this and start getting a stable proxy/SBC.  I'm ready to give it one more shot.

**Comment by matmurdock** [comment]
Try adding mhomed=1 to you kamailio.cfg.  Seems to work for me.

Mat

**Comment by Noksee** [comment]
Did you install dsiprouter with the -rtpengine or -servernat tags to get it to work with mhomed?

**Comment by jzrlost** [comment]
We never did get multi-homed working using a WAN <--> LAN setup. We are using Dsiprouter to route by DID however, but it's single interfaced on the LAN. We use OpenSIP as the SBC between the world and Dsiprouter.

**Comment by matmurdock** [comment]
I am working on getting this working.

I got  ITSP -> WAN -> DSIP -> PBX working with rtp pass through.  The
phones were registering directly to the PBX, not going through DSIP.  The
only thing I did not have working was if a phone hung a call the bye wasn't
being sent properly to the ITSP.  It did require a few changes to the
kamailio.conf file and rtpengine.conf.  The next step is to get DSIP to
proxy the registrations as well.  I get the registrations to work but I am
have audio issues.

Mat

**Comment by Noksee** [comment]
I installed DSIP on a VM with 2 NICs (1 WAN and 1 LAN) and with the -rtpengine and -servernat flags. Rtpengine doesn't seem to have installed properly so I'll work on that tomorrow. However, I added mhomed=1 to my kamailio.cfg. Inbound and outbound calls work for PBXs registering on the WAN NIC. Inbound calls work for PBXs registering on the LAN NIC. Outbound calls are properly connected, both user agents hang up at the end of the call but there isn't any audio being transmitted on either end. Seems like an issue with RTP engine. I might also have misconfigured my trunk in Asterisk. I have the PBXs registering with username and password instead of IP. I'll change the trunk settings to see if I encounter the same issues.

**Comment by matmurdock** [comment]
So there was two things I noticed.  When I had my pbx on the lan side and
set up my trunks in Asterisk to point to the lan interface on the Dsip, the
SIP packets would work fine, but the actual RTP traffic would go out my
firewall and then to the WAN interface of DSIP.  So to have the RTP go
through the LAN interface I had to make the following changes to
rtpengine.conf as well as to a few lines in kamilio.conf.  (Externall IP
changed to protect the innocent).

[rtpengine]
table = -1
interface = internal/172.16.1.11;external/123.123.123.123   <-External IP
changed to protect the innocent.
listen-ng = 7722
port-min = 10000
port-max = 20000
log-level = 7
log-facility = local1

**Comment by jzrlost** [comment]
Noksee,
   What are the exact things you changed to get this working in the multi-homed environment?  We still have not figured out the magic settings yet.  We would like to have dsiprouter between the Internet (carriers) and the internal PBX.  Extensions are also internal with the PBX.  What did you change in kamailio.conf and in rtpengine.conf?  (carriers/Internet <-> Dsiprouter with RTPengine <-> PBX with extensions)

thx josh

**Comment by Noksee** [comment]
In kamailio.cfg I added _mhomed=1_ right after the _####### Defined Values #########_ section. 
I ran **/opt/dsiprouter/dsiprouter.sh install -rtpengine -servernat**
and **/opt/dsiprouter/dsiprouter.sh enableservernat**
I then restarted kamailio **systemctl restart kamailio**
I didn't modify anything else.  My PBX's trunk registers to dsiprouter's LAN address. I included the LAN's subnet in my Asterisk PBX's sip settings (this is important or you'll get one way audio or no audio). I don't know if this might change anything but I added my LAN NIC to the internal section of firewalld and added sip and rtp ports to the internal group.
**firewall-cmd --zone=internal --permanent --add-service=sip**
**firewall-cmd --zone=internal --permanent --add-port=10000-20000/udp**
**firewall-cmd --reload**

**Comment by jzrlost** [comment]
Noksee thanks for the info.  I loaded up .52 last night as a fresh install.  Install commands have changed and worked well.  Added mhomed=1 to the Kamailio config file.  Had to adjust the internal IP and internal net in Kamailio.cfg file also since it used the external IP info for all of the settings for some reason.  Ran the "enableservernat" command.  Verified the rtpengine.conf had the correct IP settings (had to correct since I think the info was read from kamailio.cfg or something and again had both IP addresses set as the external.  Removed the "/var/run/rtpengine.pid" as you had stated in another post.  Rebooted.
On the PBX (Asterisk) in the SIP settings I had to set up some IP addresses also, but that's for another post.
After all of that the outbound calls are working great.  The inbound calls cancel and don't seem to make it from the external interface to the internal interface at all.  At least according to sgnrep and the signalling of the sip traffic.  I will do some more checking and testing today.

**Comment by devopsec** [comment]
Great conversation on this topic, in order to support multi-homed and multi-NIC configurations we would need to update the internal IP resolution code, for python and shell scripts. Currently the internal IP is resolved from the default route which is correct for natted boxes but does not consider multiple nics.. we are also working on merging this feature into the next release
