### ISSUE TITLE
can not add PBX -Internal Server Error

### ISSUE THREAD

**Issue by zhulizhong** [dOpensource/dsiprouter#50]
when I fist time add pbx, it works. 
but after reboot few times, I try to add pbx.
the system shows error:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by mackhendricks** [comment]
Hi,

What version of DSIPRouter? Did it happen when you first added a PBX or after it was running for a while?

**Comment by mackhendricks** [comment]
Okay got...it...let me look into this

**Comment by zhulizhong** [comment]
sorry, post to wrong thread. I uninstall and reinstall, solved the problem.
