### ISSUE TITLE
[BUG] cannot set credentials

### ISSUE THREAD

**Issue by showf68** [dOpensource/dsiprouter#504]
dsiprouter setcredentials --dsip-creds=XXX:YYY
Setting credentials
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Failed setting credentials on DB

it's not possible to set the credentials

**Comment by devopsec** [comment]
Can you provide the system and dsiprouter info..  
What version or branch is this occurring on?

**Comment by showf68** [comment]
the last version, installed by git clone https://github.com/dOpensource/dsiprouter.git
on debian buster
there was also a few aother problems during installation...

**Comment by devopsec** [comment]
we are tracking this bug already and there is a patch release coming soon, v0.721.  
Keep an eye out for that release

**Comment by devopsec** [comment]
resolved in v0.721
