### ISSUE TITLE
[BUG] Your Issue Name cannot install mysqlHere

### ISSUE THREAD

**Issue by icallassakim3** [dOpensource/dsiprouter#506]
on a buster server, dsiprouter master edition

E: Failed to fetch https://deb.debian.org/debian/pool/main/m/mysql-defaults/mysql-common_5.8+1.0.5_all.deb  Temporary failure resolving 'deb.debian.org'

**Comment by devopsec** [comment]
This looks like a network / DNS issue on that server...  
I can reach the url from my box without issue

**Comment by devopsec** [comment]
closing as this is a network issue not a software issue
