### ISSUE TITLE
Installation script quits 

### ISSUE THREAD

**Issue by ecsuae** [dOpensource/dsiprouter#530]
Installing on debian 11 got error and installation script quited.Also during. installation i see messages like
envsubst: command not found
 crontab: command not found
Please advise how. to proceed with installation.

Setting up ngcp-rtpengine-daemon (9.3.1.4+0~mr9.3.1.4) ...
Failed to preset unit: Unit file /etc/systemd/system/ngcp-rtpengine-daemon.service is masked.
/usr/bin/deb-systemd-helper: error: systemctl preset failed on ngcp-rtpengine-daemon.service: No such file or directory
ngcp-rtpengine-daemon.service is a disabled or a static unit, not starting it.
Setting up ngcp-rtpengine-iptables (9.3.1.4+0~mr9.3.1.4) ...
Setting up libconfig-tiny-perl (2.26-1) ...
Setting up ngcp-rtpengine-utils (9.3.1.4+0~mr9.3.1.4) ...
Processing triggers for man-db (2.9.4-2) ...
success
success
Created symlink /etc/systemd/system/multi-user.target.wants/rtpengine.service → /etc/systemd/system/rtpengine.service.
Could not load new RTPEngine kernel module

**Comment by devopsec** [comment]
this is an old version now, please use the latest release instead (v0.73 was just re-released)
