### ISSUE TITLE
[BUG] RTPEngine install failed when installing all on Debian11

### ISSUE THREAD

**Issue by kakarata** [dOpensource/dsiprouter#533]
**Describe the bug**
Installation script ends after RTPengine failed install.

**To Reproduce**
Running the "one line" command install on Debian 11.

**Screenshots**
These are the last lines of installation scripts:
ok 884 - media playback after delete - 'answer' status
ok 885 - media playback after delete - output 'answer' SDP
ok 886 - media playback after delete - 'delete' status
ok 887 - media playback after delete - 'offer' status
ok 888 - media playback after delete - output 'offer' SDP
ok 889 - media playback after delete - 'answer' status
ok 890 - media playback after delete - output 'answer' SDP
ok 891 - media playback after delete - 'play media' status
ok 892 - media duration
rtp recv 136 49144 3903089018 2120246069 d5b4a5a3acaca3a5b7fc0a3a202d2c2324316c89bba0adaca2a7b0960c39212d2c2227321c83bea1adaca2a6bd9a063f262d2c2d263f069abda6a2acada1be831c3227222c2d21390c96b0a7a2acada0bb896c3124232c2d203a0afcb7a5a3acaca3a5b4553425232c2c2325377c8abaa0adaca3a4b1ec093b202d2c222730168cb9a1adaca2a7b29c033e212d2c22263d1a86bfa6adacada6bf861a3d26222c
ok 893 - received packet matches
rtp recv 8 49145 3903089178 2120246069 2d213e039cb2a7a2acada1b98c163027222c2d203b09ecb1a4a3acada0ba8a7c3725232c2c232534d5b4a5a3acaca3a5b7fc0a3a202d2c2324316c89bba0adaca2a7b0960c39212d2c2227321c83bea1adaca2a6bd9a063f262d2c2d263f069abda6a2acada1be831c3227222c2d21390c96b0a7a2acada0bb896c3124232c2d203a0afcb7a5a3acaca3a5b4d53425232c2c2325377c8abaa0adaca3a4b1ec09
ok 894 - received packet matches
rtp recv 8 49146 3903089338 2120246069 3b202d2c222730168cb9a1adaca2a7b29c033e212d2c22263d1a86bfa6adacada6bf861a3d26222c2d213e039cb2a7a2acada1b98c163027222c2d203b09ecb1a4a3acada0ba8a7c3725232c2c23253455b4a5a3acaca3a5b7fc0a3a202d2c2324316c89bba0adaca2a7b0960c39212d2c2227321c83bea1adaca2a6bd9a063f262d2c2d263f069abda6a2acada1be831c3227222c2d21390c96b0a7a2acada0
ok 895 - received packet matches
rtp recv 8 49147 3903089498 2120246069 bb896c3124232c2d203a0afcb7a5a3acaca3a5b4553425232c2c2325377c8abaa0adaca3a4b1ec093b202d2c222730168cb9a1adaca2a7b29c033e212d2c22263d1a86bfa6adacada6bf861a3d26222c2d213e039cb2a7a2acada1b98c163027222c2d203b09ecb1a4a3acada0ba8a7c3725232c2c23253455b4a5a3acaca3a5b7fc0a3a202d2c2324316c89bba0adaca2a7b0960c39212d2c2227321c83bea1
ok 896 - received packet matches
rtp recv 8 49148 3903089658 2120246069 adaca2a6bd9a063f262d2c2d263f069abda6a2acada1be831c3227222c2d21390c96b0a7a2acada0bb896c3124232c2d203a0afcb7a5a3acaca3a5b4d53425232c2c2325377c8abaa0adaca3a4b1ec093b202d2c222730168cb9a1adaca2a7b29c033e212d2c22263d1a86bfa6adacada6bf861a3d26222c2d213e039cb2a7a2acada1b98c163027222c2d203b09ecb1a4a3acada0ba8a7c3725232c2c232534
ok 897 - received packet matches
ok 898 - statistics - 'statistics' status
1..898
test "$(ls fake-daemon-tests-reorder-sockets)" = ""
rmdir fake-daemon-tests-reorder-sockets
make[4]: Leaving directory '/usr/local/src/rtpengine/t'
make[3]: *** [Makefile:110: daemon-tests] Error 2
make[3]: *** Waiting for unfinished jobs....
rm control_ng.strhash.c sdp.strhash.c call_interfaces.strhash.c test-const_str_hash.strhash.c
make[3]: Leaving directory '/usr/local/src/rtpengine/t'
make[2]: *** [../lib/common.Makefile:4: all] Error 2
make[2]: Leaving directory '/usr/local/src/rtpengine/t'
make[1]: *** [Makefile:42: check] Error 2
make[1]: Leaving directory '/usr/local/src/rtpengine'
dh_auto_test: error: make -j4 check returned exit code 2
make: *** [debian/rules:29: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
Problem installing RTPEngine DEB's
RTPEngine install failed

**Server Info:**
 - OS: Linux xxxxxx.tld 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux
 - Distro: Updated Debian 11
 - dSIPRouter Version: last from script.

**Comment by devopsec** [comment]
looks like the daemon tests failed, does this still occur on the re-release?

**Comment by kakarata** [comment]
hi,
I think can be related about AWS Lightsail deployment specific when installing all components. Probably because of workload installing/compiling AWS Lightsail penalices the VPS having arund 85% CPU stolen.

Then tested installing components separately, waiting in between to not consume the hole CPU burst, and all componentes including RTPengine installed and working correctly. Thanks!

**Comment by devopsec** [comment]
we also added in a swap file for low RAM deployments to allow them to compile still, sounds like this resolved
