### ISSUE TITLE
[BUG] rtpengine fails to install on Debian 11 Linode

### ISSUE THREAD

**Issue by reqlez** [dOpensource/dsiprouter#536]
**Describe the bug**
rtp engine fails to install on a fresh Debian 11 image provided by Linode team.

**To Reproduce**
Attempt to install rtpengine on above version.

**Screenshots**
`Setting up debhelper (13.3.4) ...
Processing triggers for libc-bin (2.31-13+deb11u7) ...
Processing triggers for man-db (2.9.4-2) ...
E: Unable to locate package linux-headers-grub-2.06-20-linode.img
E: Couldn't find any package by glob 'linux-headers-grub-2.06-20-linode.img'
E: Couldn't find any package by regex 'linux-headers-grub-2.06-20-linode.img'
E: Unsupported file ./ given on commandline
Problem with installing the required libraries for RTPEngine
RTPEngine install failed
`

**Server Info:**
 - OS: `Linux sbc.xxx.net 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux`
 - Distro: 
      PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
      NAME="Debian GNU/Linux"
      VERSION_ID="11"
      VERSION="11 (bullseye)"
      VERSION_CODENAME=bullseye
      ID=debian
 - dSIPRouter Version: 0.73
 - Kamailio Version: kamailio 5.5.7 (x86_64/linux)
 - RTPengine Version: 9.3.1.4+0~mr9.3.1.4 git-HEAD-934c4f0

**Additional context**
Using apt install -y linux-headers-$(uname -r) linux-image-$(uname -r) installs require headers just fine.
I commented out that section to complete the install and it was successful.

Also, after re-starting the install post-fail, password is not present, however, can be easily reset...
dSIPRouter GUI Password: <HASH CAN NOT BE UNDONE> (reset password if you forgot it)

**Comment by devopsec** [comment]
try the latest build of dsiprouter, the dependencies should be sorted out in v0.73  
if it's still failing let us know what your `/etc/apt/` directory looks like after the failure (the default install should use the official repos from debian instead of the cloud provider's repos)

**Comment by devopsec** [comment]
@reqlez is this still an issue?

**Comment by devopsec** [comment]
no response, closing as stale
