### ISSUE TITLE
Default fail2ban configuration from FusionPBX will ban DSIPRouter

### ISSUE THREAD

**Issue by ozid** [dOpensource/dsiprouter#54]
I notice that my dSIPRouter is directly listed after fews registrations requests inside jail "f2b-freeswitch" after a very fresh install of FusionPBX and dSIPRouter

**/etc/fail2ban/jail.conf**
```

[DEFAULT]
ignoreip = ip_dsipr/32
```
This solve everything

**Comment by mackhendricks** [comment]
Very good catch...we end up having to add this.  I will make this part of the FusionPBX Domain enablement seteps

**Comment by mackhendricks** [comment]
The downside is that SIP REGISTER attacks will pass thru the Proxy tot he FusionPBX server.  We will probably add Fail2Ban in an upcoming release to dSIPRouter to reduce this

**Comment by ozid** [comment]
Thanks you!
