### ISSUE TITLE
FusionPBX never receives the BYE

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#56]
Scendario

FusionPBX -> dSIPRouter -> Carrier

Outbound calls via carrier will not hangup when a BYE is sent from the Carrier.  Kamailio can't route the BYE back to FusionPBX.  The current workaround is to comment out the record_route() statement on line 681 in /etc/kamailio/kamailio.cfg.  Restart kamailio to make sure it's working.  This works without a problem if using FreePBX/Asterisk.  This is what the BYE looks like:

BYE sip:gw+f6d6b954-1a32-4efa-83d1-dddf1b09703c@104.131.160.64:5080;transport=udp;gw=f6d6b954-1a32-4efa-83d1-dddf1b09703c SIP/2.0
Record-Route: <sip:52.41.52.34;lr=on;ftag=t65t29gj44F7H;vsf=U2s0M0JsdTNiZ2Z1ZzN1PD4iclB0MC9db3MdVFc-;vst=U2s0M0JsdTNiZ2Z1ZzN1ODI0fkVsKzNfa2szeWFW>
Via: SIP/2.0/UDP 52.41.52.34:5060;branch=z9hG4bK8ed6.711fd340464ab5cc22471d6f2aecbea7.0
Via: SIP/2.0/UDP 192.168.99.184;branch=z9hG4bKsr-xL6MWFNVRAQUfgpsa7kVyGxVRcR0W7N9RGwx5G99l-lilDeqJSaZ2PZXuIhLlkwOl0I-W7s9R.M-RdUOy.l-RcMFydgSaFpbRFlXydlFacpba7R-W7p*
Via: SIP/2.0/UDP 192.168.99.184;branch=z9hG4bKsr-xL6MWFNVRAQUfgpsa7xVycsVRch-W7sLy7xCa7pilDeqJSaZ2PZXuIhLlkwkaG6CaSlYRG8nR.q0l740ucgOR5KY
From: <sip:19475176566@198.211.102.60>;tag=SDocuhd99-sNHh7+HMfA9XE8bhzHwPNxPENiPUwgAq
To: "100" <sip:FreeSWITCH@198.211.102.60>;tag=t65t29gj44F7H
Call-ID: 032729c5-f16b-1236-1c9d-42a9360df6b3
CSeq: 124537073 BYE
Max-Forwards: 67
Content-Length: 0
Route: <sip:198.211.102.60;lr>

The Kamailio error logs states this:

Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=888 a=16 n=if
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=883 a=24 n=has_totag
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: siputils [checks.c:123]: has_totag(): totag found
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=907 a=16 n=if
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=888 a=24 n=loose_route
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: rr [loose.c:112]: find_first_route(): No Route headers found
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: rr [loose.c:944]: loose_route(): There is no Route HF
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=912 a=16 n=if
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=907 a=25 n=is_method
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=929 a=16 n=if
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=912 a=25 n=is_method
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=916 a=16 n=if
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=913 a=25 n=is_method
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=914 a=24 n=handle_ruri_alias
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: nathelper [nathelper.c:1098]: handle_ruri_alias(): no alias param
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=927 a=16 n=if
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: exec: *** cfgtrace:request_route=[WITHINDLG] c=[/etc/kamailio/kamailio.cfg] l=916 a=24 n=t_check_trans
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: tm [t_lookup.c:1018]: t_check_msg(): msg (0x7f350c9caa18) id=2062 global id=2061 T start=0xffffffffffffffff
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: tm [t_lookup.c:476]: t_lookup_request(): start searching: hash=14158, isACK=0
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: tm [t_lookup.c:419]: matching_3261(): RFC3261 transaction matched, tid=e473.257c9b811386ace7ea8b62ce2ec8fe4c.0
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: tm [t_lookup.c:676]: t_lookup_request(): transaction found (T=0x7f3502d9f080)
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: tm [t_lookup.c:1087]: t_check_msg(): msg (0x7f350c9caa18) id=2062 global id=2062 T end=0x7f3502d9f080
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: tm [t_reply.c:1568]: t_retransmit_reply(): DBG: **t_retransmit_reply: nothing to retransmit**
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: <core> [core/receive.c:289]: receive_msg(): request-route executed in: 247 usec
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: <core> [core/usr_avp.c:636]: destroy_avp_list(): destroying list (nil)
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: <core> [core/usr_avp.c:636]: destroy_avp_list(): destroying list (nil)
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: <core> [core/usr_avp.c:636]: destroy_avp_list(): destroying list (nil)
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: <core> [core/usr_avp.c:636]: destroy_avp_list(): destroying list (nil)
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: <core> [core/usr_avp.c:636]: destroy_avp_list(): destroying list (nil)
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: <core> [core/usr_avp.c:636]: destroy_avp_list(): destroying list (nil)
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: <core> [core/xavp.c:446]: xavp_destroy_list(): destroying xavp list (nil)
Jun 23 09:43:21 dsiprouter-v0 /usr/sbin/kamailio[30992]: DEBUG: <core> [core/receive.c:378]: receive_msg(): cleaning up

**Comment by marc8lange** [comment]
I'm not getting a proper bye / ok from Freepbx / Asterisk in Dsip 0.51
After the Bye I get the following:
SIP/2.0 481 Call leg/transaction does not exist

One of the callers line stays connected as a result (depends on who hangs up first.

This does not happen when routing calls directly to FRreePBX, only when routing through dSip then FreePBX.

**Comment by matmurdock** [comment]
Do you get this when the pbx extension hangs up first? 

Mat

**Comment by mackhendricks** [comment]
Hey @marc8lange I just tested it with FreePBX 14 / Asterisk 13.22 and the BYE worked without an issue when the carrier sent the BYE.

But, the BYE doesn't happen when the SIP client send it.  I just fixed it...actually it was commented out for testing another use case and we didn't catch it during our final testing.   I will fix it and rebuild 0.51.  But, you can fix your install by doing the following

1. login to the host
2. vi /etc/kamailio/kamailio.cfg
3. Goto line 726 and remove the # sign
4. Save the file
5. Execute systemctl restart kamailio
6. Try the call again

![image](https://user-images.githubusercontent.com/5568984/50235823-d1b03d80-0386-11e9-9f2e-ec7fd50ff8b4.png)

**Comment by matmurdock** [comment]
Side note,  Add this to bottom of .bashrc in /root
export NCURSES_NO_UTF8_ACS=1

**Comment by marc8lange** [comment]
> Side note, Add this to bottom of .bashrc in /root
> export NCURSES_NO_UTF8_ACS=1

done after googling it...but still not entirely sure that I've achieved a different display in putty?

**Comment by matmurdock** [comment]
You need to logout and log back in.  It works in putty.

Mat

**Comment by mackhendricks** [comment]
@marc8lange 

It looks like your carrier doesn't like how dSIPRouter forwards the BYE.  Some carriers are picky.  We are using Flowroute without an issue.   What carrier are you using?

In regards to export NCURSES_NO_UTF8_ACS=1, I will create an issue and add that into the build.  I've always wondered people get letters when using putty :-)
