### ISSUE TITLE
install on raspbian stretch

### ISSUE THREAD

**Issue by Ian-morin** [dOpensource/dsiprouter#59]
What would it take to install on Raspbian stretch.  I gave it a quick try but it failed with this error:

aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/stretch

Would be nice to be able to run on raspberry Pi 3 for smaller Systems

**Comment by mackhendricks** [comment]
We don't have plans to implement this, but would love to see if other people are interested in this.  Perhaps post something in our Google Groups: https://groups.google.com/forum/#!forum/dsiprouter
