### ISSUE TITLE
[BUG] Cloud Image Created from a dSIPRouter install in AWS doesn't Start

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#603]
1. Create an EC2 instance
2. Install dSIPRouter 
3. Create an AMI image from the dSIPRouter instance
4. Create an EC2 instance from the dSIPRouter AMI

The image will not start

**Comment by devopsec** [comment]
Already fixed here: https://github.com/dOpensource/dsiprouter/pull/600
