### ISSUE TITLE
Support for pass-thru registration for FreePBX

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#65]
We currently support pass-thru registration for FusionPBX.  We need to support pass-thru for FreePBX.  Since FreePBX doesn't support multiple domains by default we need to come up with another solution.  At the very least we can implement manual domain mapping where FreePBX endpoints would register with an arbitrary domain and we would map it to a PBX and/or we could have a default domain where all PBX's without a domain will be routed to.

**Comment by mpicher** [comment]
I'm looking to do something similar... What I would envision would be that externally users would point to userid@sipdomain which would resolve to one or more dsiprouter installations. dsiprouter would then forward that registration inbound by also looking up SRV records on an internal DNS server. This way internal domains can be added just by modifying the DNS server that sits on the inside.
