### ISSUE TITLE
Use SSL/TLS

### ISSUE THREAD

**Issue by dagors** [dOpensource/dsiprouter#70]
It is possible to add the option to use certificates ssl / tls lets encrypt or some other for Kamailio and siprouter GUI, also manage it from the GUI

https://www.fredposner.com/1836/kamailio-tls-and-letsencrypt/

**Comment by devopsec** [comment]
we already built support for this after testing it will be made public :)

**Comment by mackhendricks** [comment]
@devopsec Can you have SSL/TLS enabled during install.  Please create a branch based on the master and please follow the contribution guide: https://github.com/dOpensource/dsiprouter/blob/master/docs/CONTRIBUTING.md

Please make changes in the guide as needed
