### ISSUE TITLE
README.md Update

### ISSUE THREAD

**Issue by matmurdock** [dOpensource/dsiprouter#73]
I notice there is a cdrs.sql file in the dsiprouter folder.  I think it would be a good idea to mention that that needs to be ran after the install so that cdr's will start working.  I spent a bit of time last night searching for what fields needed added and had I been more observant this would have solved my issue.  Fantastic product.  Once I get up to speed a bit more on it I hope to help out with UI.  Mainly a PHP guy, but hey good reason to learn Python.

Mat

**Comment by devopsec** [comment]
The LCR module is installed by default and imports the lcr.sql schema into mysql during install.
The module install process has been greatly improved in recent commits to dev branch as well and should automatically merge if you have any data in the tables.
