### ISSUE TITLE
Improve Security and Fraud Prevention

### ISSUE THREAD

**Issue by dagors** [dOpensource/dsiprouter#74]
Can be improve security and fraud prevention adding use of this options / modules in kamailio?

- Filter User Agent
- Sipvicious
- PIKE
- HTABLE
- PIPELIMIT
- PERMISSIONS
- TOPOH

Examples
https://www.youtube.com/watch?v=54qQewLEb3E
https://www.voztovoice.org/sites/default/files/posnerastricon2017-171005043600.pdf

**Comment by mackhendricks** [comment]
Great idea...I love Fred!  He got me into Kamailio!  

We will Filter User Agents and figure out if we want to use Fail2Ban or PIKE to stop DOS's.  I was thinking Fail2Ban since we have other services that needs to be protected.   Any thoughts on this?

**Comment by dagors** [comment]
I do not really have much knowledge about these issues, but as I see it, it is better to use Fail2Ban to protect services such as http, https, the GUI dSiprouter, ssh.

PIKE and other Kamailio modules to protect SIP connection attempts, Pike works well with DoS attacks but falls short in DDoS attacks so it is necessary to use several methods for example adding HTABLE and integrating Fail2Ban with Kamailio.

I think it is not possible to choose one or the other, both are necessary.

This is better explained in these links:
https://kb.asipto.com/kamailio:usage:k31-sip-scanning-attack
https://www.kamailio.org/wiki/tutorials/security/kamailio-security

As I see Kamailio brings by default a conditionality for scanning attacks or anti flood that can be enabled using #! Define WITH_ANTIFLOOD this method enables PIKE, HTABLE and IPBAN (default is block if more than 16 requests in 2 seconds and ban for 300 seconds).

I also believe that it is convenient to add protection against SQL injection always using Kamailio.

**Comment by mackhendricks** [comment]
We are going to implement PIKE and remove the Server Agent Header

**Comment by mackhendricks** [comment]
This has been added to master and dev branches.  It will be officially supported with 0.52
