### ISSUE TITLE
Edit PBX - Cannot Change Type

### ISSUE THREAD

**Issue by matmurdock** [dOpensource/dsiprouter#75]
When you edit a PBX entry you cannot change it from Username/Password Auth to IP Auth.  You can change it from IP Auth to Username/Password Auth.

Mat

**Comment by matmurdock** [comment]
Ok.  It looks like you can now change it from IP Auth to Username/Password Auth.  However if you change from Username/Password Auth back to IP Auth the address table is not populated with the proper record.

Mat

**Comment by mackhendricks** [comment]
This was resolved with issue #164
