### ISSUE TITLE
Deleting PBX leaves orphan DID

### ISSUE THREAD

**Issue by matmurdock** [dOpensource/dsiprouter#78]
If you delete a PBX any DID's linked to it are left in the database.  When you delete a PBX it should either prevent you from deleting if DID's are linked or remove them from the DB as well.

Mat

**Comment by devopsec** [comment]
By left in the database you are seeing inbound routes in dr_rules table correct?
I think your correct in that we should have a relationship between the mapped rule on delete as well.
If this is the case then we can do what we did for carriers and outbound routes and delete related rules but prompt the user before doing so.

**Comment by jzrlost** [comment]
We deleted a PBX and now have those numbers stuck in the database. When we try to add the number again it gives an error: Duplicate DID's are not allowed. How do we remove these numbers from the database?

**Comment by matmurdock** [comment]
I think there is an open ticket for this, however you can connect to the
MySQL db directly and delete it manually, then click the reload button in
dSIP.  Let me know if you need help.

Mat

**Comment by jzrlost** [comment]
I attempted to go in to mysql using the command line, but I'm not a mysql admin so I don't really know how to find and delete the number.  Do you know the command to find the number and delete it?  I was going to use phpmyadmin, but I'm afraid if I install it that will mess up the web server dsiprouter is using.

**Comment by jzrlost** [comment]
Disregard the last message.  I was able to figure out how to find the number and delete it in the database (good old Google).  We are good for now.  Hopefully, the next version takes care of this automatically.

**Comment by matmurdock** [comment]
Sweet!, have a happy holidays.  If you have any other questions post them.

Mat

**Comment by mdonan90** [comment]
How do you find this in the DB?

**Comment by matmurdock** [comment]
It is in the Kamailio database in the dr_rules table.

**Comment by mackhendricks** [comment]
We now have Endpoint Groups.  A DID is mapped to an Endpoint Group.  So, we should warn the user  that the Endpoint Group is linked to DID's and DO NOT allow them to delete the Endpoint Group  This should be controlled by the Endpoint API and a message should be displayed in the UI.

**Comment by RichSosa28** [comment]
Possible solution:
Warn the user that the endpoint group is being used by a inbound DID and do not let them delete unless the it is no longer used. For this to work must also update the inbound mapping rule UI to be able to point to an empty field so the user can have the option to no longer point to the endpoint group, in turn giving them the option to delete it.

**Comment by devopsec** [comment]
For carrier groups we were warning the user about mapped outbound routes (apparently that change wasn't merged in) and deleting them when their corresponding carrier group is deleted.  
We could do the same for endpoint groups but note inbound routes can have multiple endpoint groups mapped to it.  
Note that we allow hard forwarding and failover forwarding to any type of endpoint group so all endpoint groups would need checked by this query.  

We should give the user the option to either update the existing mappings, i.e.:
1. user clicks delete on carrier group or endpoint group
2. we query DB and find any inbound / outbound/ failover / hard forward routes that are mapped to that gateway group
3. modal pop ups warning user that the mapped routes will be effected "The following routes will be effected by this change: 
    ...
    Are you sure you want to continue?
4. user clicks "continue" or "cancel"
5. we remove gateway groups from existing routes and delete endpoint group selected
