### ISSUE TITLE
Example outbound routes

### ISSUE THREAD

**Issue by andrew867** [dOpensource/dsiprouter#80]
Hi!

For some reason I can't get outbound route prefixes to work. Could someone send a screenshot of their working configuration?

Thanks!

**Comment by mackhendricks** [comment]
Sure...no problem.  I will get this to you ASAP.  We need to add more doc's around this as well.

**Comment by andrew867** [comment]
I figured it out (from reading the code), when _not_ using a range you need to fill in "To Prefix" with the prefix, not "From Prefix" and not both.
