### ISSUE TITLE
GUI Enhancements

### ISSUE THREAD

**Issue by mackhendricks** [dOpensource/dsiprouter#85]
-Make all columns on all pages searchable/sortable from the top of the table.  There will be one search box, which will search all of the columns.  When the column is clicked it will sort by that column.

-Mass import of DID's.  We will have a list of DID's, one per line to import.  On the import screen we can select the PBX ID to route to as well as add a note (this note will apply to all of them and would be edited as needed after import.  A verification screen before import would be added if time permits

-Add a Note field to each DID mapped on the Inbound  DID mapping page

-Fix Pagination on all screens that has tables

**Comment by matmurdock** [comment]
Love it!

**Comment by devopsec** [comment]
100% agree, this has been on the bucket list for a little while now..
Let's move this to next release after v0.51, we have a lot of functionality changes coming in .51 so we can do cosmetics / feature changes on the next release.

Don't forget to add to the list:
- "Check All" checkbox functionality at top of pages
- "Next / Previous" index selector on page results, we aren't caching results from query yet, the selector is not functional right now. 
--> We should think about loading the first n number of results synchronous, then asynchronous loading of the rest of the results for a page.

**Comment by mackhendricks** [comment]
Taking the extra items listed by @devopsec and putting this in another ticket and closing this issue
