### ISSUE TITLE
dSiprouter does not start when it can't determine external IP

### ISSUE THREAD

**Issue by matmurdock** [dOpensource/dsiprouter#86]
Lately dSiprouter has been unable to determine the external IP.  I noticed it is trying to use ipv4.myexternalip.com to accomplish this.  When the site doesn't respond then the service won't start.  I would recommend just allow the external IP to be set in a conf file or in the database.  I ended up just modifying shared.py with my external IP so I could get things working.

Mat

**Comment by mackhendricks** [comment]
Add a command line flag to allow the the external ip address to be set.  Perhaps we use -ui-ip

**Comment by devopsec** [comment]
issue resolved, reference commit b6f4f1481ed3a36c3d6ae02cbca9a2877ddf6702

**Comment by mackhendricks** [comment]
Hey Matt,

Yes, we updated the URL because they changed it.  But, we will either provide a service that handle this or use the ip on the box.  We were trying to handle the situation when the ip was NAT’d.  But, its causing more issues then desired
