### ISSUE TITLE
Kamailio stored procedure errors (kamailio_cdrs, kamailio_rating)

### ISSUE THREAD

**Issue by YourHuckleberry** [dOpensource/dsiprouter#88]
As per syslog, repeated errors of two recurring stored procedures - kamailio_cdrs and kamailio_rating:

ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: PROCEDURE kamailio.kamailio_cdrs does not exist (1305)
ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
ERROR: sqlops [sql_api.c:264]: sql_do_query(): cannot do the query [call kamailio_cdrs()]
ERROR: db_mysql [km_dbase.c:127]: db_mysql_submit_query(): driver error on query: PROCEDURE kamailio.kamailio_rating does not exist (1305)
ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
ERROR: sqlops [sql_api.c:264]: sql_do_query(): cannot do the query [call kamailio_rating('default')]

**Comment by mackhendricks** [comment]
The kamailio_cdrs procedure is now there by default and executes correctly to create CDR's.  But, the kamailio_rating is not executing correctly because the billing_rates table is not there by default.  We need to decide if this should be an open source feature or an enterprise feature

**Comment by devopsec** [comment]
great discussion, i think we should keep billing open source. we want to support users using siremis out of the box
