### ISSUE TITLE
Adding support for registration based carriers

### ISSUE THREAD

**Issue by hcaldicott** [dOpensource/dsiprouter#9]
Is it possible to modify the interface and config script to support carriers using SIP registration?

**Comment by khorsmann** [comment]
I would use freeswitch as sbc / uac to register and route calls to it via dsiprouter as gw. The Kamailio uac is not so usable  for most registration purposes as client.

**Comment by mackhendricks** [comment]
@hcaldicott what's your use case?  Most carriers provide ip auth - at least in the US.  Is their a unique use case around this.

**Comment by mackhendricks** [comment]
This is scheduled for 0.50 release in August
