### ISSUE TITLE
Issue with RTPENGIN

### ISSUE THREAD

**Issue by TayyabTalha** [dOpensource/dsiprouter#92]
Hi,
I'm facing rtpengin issue after some days its stop working I'm not able to receive any rtp on both side. Restarting dsiprouter resolve the problem.
I'm using OS Debian GNU/Linux 9.
One thing I have notice is that you are using rtpengin version 6.1.1.1+0~mr6.1.1.1 so is there any reason to use this version or I can use latest rtpengin version.
Thank you.

**Comment by mackhendricks** [comment]
You can use another version of rtpengine.  It just needs to listen to requests on 127.0.0.1:7722

**Comment by TayyabTalha** [comment]
@mackhendricks Thank you for your reply. But can you help me in identifying the problem that why rtpenging stop sending packages.
Regards
Tayyab

**Comment by TayyabTalha** [comment]
Hi @mackhendricks,
I have figure out in rtp engin conf port max is 300000 and in firewalld you just forward 1000-2000 ports
`[rtpengine]
        table = -1
        interface = $INTERFACE
        listen-ng = 7722
        port-min = 10000
        port-max = 30000
        log-level = 7
        log-facility = local1"`
When I start facing problem these are rtp-engin logs
`Dec 14 14:03:46 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: Received command 'delete' from 127.0.0.1:44000
Dec 14 14:03:46 dsiprouter rtpengine[2549]: DEBUG: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: Dump for 'delete' from 127.0.0.1:44000: { "media-address": "<DSIPIP>", "call-id": "2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060", "received-from": [ "IP4", "<DESTNIATION IP>" ], "from-tag": "as3a88508b", "command": "delete" }
Dec 14 14:03:46 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: Scheduling deletion of call branch 'as3a88508b' (via-branch '') in 30 seconds
Dec 14 14:03:46 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: delete time = 0.000109 sec
Dec 14 14:03:46 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: Replying to 'delete' from 127.0.0.1:44000
Dec 14 14:03:46 dsiprouter rtpengine[2549]: DEBUG: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: Response dump for 'delete' to 127.0.0.1:44000: { "created": 1544796208, "created_us": 652074, "last signal": 1544796215, "SSRC": {  }, "tags": { "as3a88508b": { "tag": "as3a88508b", "created": 1544796208, "in dialogue with": "as09aa4fc2", "medias": [ { "index": 1, "type": "audio", "protocol": "RTP/AVP", "streams": [ { "local port": 21072, "endpoint": { "family": "IPv4", "address": "<DESTNIATION IP>", "port": 10338 }, "advertised endpoint": { "family": "IPv4", "address": "<DESTNIATION IP>", "port": 103 ...
Dec 14 14:03:46 dsiprouter rtpengine[2549]: DEBUG: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: ... 38 }, "last packet": 1544796208, "flags": [ "RTP", "filled" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } }, { "local port": 21073, "endpoint": { "family": "IPv4", "address": "<DESTNIATION IP>", "port": 10339 }, "advertised endpoint": { "family": "IPv4", "address": "<DESTNIATION IP>", "port": 10339 }, "last packet": 1544796208, "flags": [ "RTCP", "filled" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } } ], "flags": [ "initialized", "send", "recv" ] } ] }, "as09aa4fc2": { "tag": "as09aa4 ...
Dec 14 14:03:46 dsiprouter rtpengine[2549]: DEBUG: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: ... fc2", "created": 1544796208, "in dialogue with": "as3a88508b", "medias": [ { "index": 1, "type": "audio", "protocol": "RTP/AVP", "streams": [ { "local port": 21062, "endpoint": { "family": "IPv4", "address": "<INCOMMING DID IP>", "port": 16070 }, "advertised endpoint": { "family": "IPv4", "address": "<INCOMMING DID IP>", "port": 16070 }, "last packet": 1544796208, "flags": [ "RTP", "RTCP", "filled", "ICE" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } }, { "local port": 21063, "endpoint": {  }, " ...
Dec 14 14:03:46 dsiprouter rtpengine[2549]: DEBUG: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: ... advertised endpoint": {  }, "last packet": 1544796208, "flags": [ "RTCP", "fallback RTCP", "filled", "ICE" ], "stats": { "packets": 0, "bytes": 0, "errors": 0 } } ], "flags": [ "initialized", "send", "recv", "rtcp-mux", "ICE" ] } ] } }, "totals": { "RTP": { "packets": 0, "bytes": 0, "errors": 0 }, "RTCP": { "packets": 0, "bytes": 0, "errors": 0 } }, "result": "ok" }
Dec 14 14:03:47 dsiprouter rtpengine[2549]: DEBUG: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060/as09aa4fc2/1]: Sending ICE/STUN request for candidate pair 9riOimBRc1aM9jXi:Hac130001:1 from <DSIPIP> to 172.19.0.1:16070
Dec 14 14:03:47 dsiprouter rtpengine[2549]: DEBUG: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060/as09aa4fc2/1]: Sending ICE/STUN request for candidate pair 9riOimBRc1aM9jXi:R6d48d4de:1 from <DSIPIP> to 109.72.212.222:50087
Dec 14 14:04:01 dsiprouter rtpengine[2549]: DEBUG: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060/as09aa4fc2/1]: Sending ICE/STUN request for candidate pair 9riOimBRc1aM9jXi:Hac130001:1 from <DSIPIP> to 172.19.0.1:16070
Dec 14 14:04:01 dsiprouter rtpengine[2549]: DEBUG: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060/as09aa4fc2/1]: Sending ICE/STUN request for candidate pair 9riOimBRc1aM9jXi:R6d48d4de:1 from <DSIPIP> to 109.72.212.222:50087
Dec 14 14:04:16 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: Call branch 'as3a88508b' (via-branch '') deleted, no more branches remaining
Dec 14 14:04:16 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: Final packet stats:
Dec 14 14:04:16 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: --- Tag 'as3a88508b', created 0:48 ago for branch '', in dialogue with 'as09aa4fc2'
Dec 14 14:04:16 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: ------ Media #1 (audio over RTP/AVP) using unknown codec
Dec 14 14:04:16 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: --------- Port  <DSIPIP>:21072 <>   <DESTNIATION IP>:10338, SSRC 0, 0 p, 0 b, 0 e, 48 ts
Dec 14 14:04:16 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: --------- Port  <DSIPIP>:21073 <>   <DESTNIATION IP>:10339 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 48 ts
Dec 14 14:04:16 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: --- Tag 'as09aa4fc2', created 0:48 ago for branch '', in dialogue with 'as3a88508b'
Dec 14 14:04:16 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: ------ Media #1 (audio over RTP/AVP) using unknown codec
Dec 14 14:04:16 dsiprouter rtpengine[2549]: INFO: [2fed084e3710a592052c06b14a354590@<DESTNIATION IP>:5060]: --------- Port  <DSIPIP>:21062 <>  <INCOMMING DID IP>:16070, SSRC 0, 0 p, 0 b, 0 e, 48 ts
`
I think port is above firewall rule as you can see in last line of logs <DSIPIP>:21062
Thanks in advance.
