### ISSUE TITLE
Adding outbound routes to v0.51 not working

### ISSUE THREAD

**Issue by andrew867** [dOpensource/dsiprouter#93]
I am using branch v0.51 for FusionPBX domain support.

Currently when I add an outbound route it works if I only specify the gateways. If I add a "To Prefix" (it was working in the previous release, see #80 ) the route disappears from the list.

**Comment by andrew867** [comment]
It actually doesn't matter what I enter for an outbound route, when I refresh the page they are gone. Even if I modify the default route it stops showing up.

**Comment by mackhendricks** [comment]
Got you…can you tell us what you put in exactly and we will test it and fix it.  We are finishing up our testing and Inbound/Global Outbound routes is on list for the next couple days.  We plan to release 0.51 by the weekend.  We have fixed a bunch of bugs around PBX and Domain.  

Mack Hendricks / Head of Support / dOpenSource
web: http://dopensource.com <http://dopensource.com/>
support: +888-907-2085
dSIPRouter <http://dsiprouter.org/> - GUI focused on implementing Kamailio to provide SIP Trunking and PBX Hosting Services

**Comment by andrew867** [comment]
Manually inserting the row into the database works fine:

**Comment by mackhendricks** [comment]
Yes, I see the issue.  We will fix this issue.
